### ISSUE TITLE
Blank build args are handled incorrectly

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1023]
### Current Behavior

Setting a non-valued build arg like this:

```yaml
buildArgs:
  CONTAINER: ${modules.base.outputs.local-image-name}
  TAG: ${modules.base.version}
  # this gets pulled from an env var
  CHECKOUT_KEY:
```

Or explicitly, like this:

```yaml
buildArgs:
  CONTAINER: ${modules.base.outputs.local-image-name}
  TAG: ${modules.base.version}
  # this gets pulled from an env var
  CHECKOUT_KEY: !!null
```

results in a Docker command incorrectly emitting `"null"` as a string like this:

```
docker build -t snapshot:v-69e99e5246 --build-arg CONTAINER=base --build-arg TAG=v-dac401d9dd --build-arg CHECKOUT_KEY=null /Users/eronarn/Code/investment_automation/.garden/build/snapshot
```

### Expected behavior

The expected Docker command is instead:

```
docker build -t snapshot:v-69e99e5246 --build-arg CONTAINER=base --build-arg TAG=v-dac401d9dd --build-arg CHECKOUT_KEY /Users/eronarn/Code/investment_automation/.garden/build/snapshot
```

This is special syntax in Docker builds: https://docs.docker.com/engine/reference/commandline/build/

> You may also use the --build-arg flag without a value, in which case the value from the local environment will be propagated into the Docker container being built:

### Your environment

```
[eronarn@Jamess-MacBook-Pro investment_automation]$ garden version
0.10.2
```
