### ISSUE TITLE
Unhandled exception viewing logs

### ISSUE THREAD

**Issue by elthrasher** [garden-io/garden#1068]
### Current Behavior

When clicking "Logs" on the daskboard, it spins forever, and I see this in my console:

<img width="1032" alt="Screen Shot 2019-08-02 at 8 51 18 AM" src="https://user-images.githubusercontent.com/1909440/62380140-8f52ff80-b516-11e9-9280-7ba2fc9fec36.png">

The line of code throwing this error appears to be: https://github.com/garden-io/garden/blob/master/garden-service/src/plugins/kubernetes/util.ts#L67

I am using the stable/mysql helm chart which doesn't have a selector key in the spec. I logged the object to my console:

```JavaScript
{ apiVersion: 'extensions/v1beta1',
  kind: 'Deployment',
  metadata:
   { name: 'mysql',
     namespace: 'local',
     labels:
      { app: 'mysql',
        chart: 'mysql-1.3.0',
        release: 'mysql',
        heritage: 'Tiller' },
     annotations: {} },
  spec: { template: { metadata: [Object], spec: [Object] } } }
```

Here's from my garden.yml:

```yaml
kind: Module
type: helm
name: mysql
description: Mysql deployment via helm
chart: stable/mysql
values:
  mysqlRootPassword: password
  initializationFiles:
    oauth-db.sql: |-
      CREATE DATABASE IF NOT EXISTS oauth;
```

### Expected behavior

Exceptions are caught. Logs can be viewed.

### Reproducible example

```yaml
kind: Project
name: oauth2
environments:
  - name: local
    variables:
      namespace: local
providers:
  - name: local-kubernetes
    environments: [local]
    namespace: local
    
---
# mysql
kind: Module
type: helm
name: mysql
description: Mysql deployment via helm
chart: stable/mysql
values:
  mysqlRootPassword: password
  initializationFiles:
    oauth-db.sql: |-
      CREATE DATABASE IF NOT EXISTS oauth;
```

### Workaround

Get logs via kubectl :(

### Suggested solution(s)

🔜  https://github.com/microsoft/TypeScript/issues/16#issuecomment-515160784

### Your environment

docker-for-desktop mac

`garden version`
`0.10.3`
`kubectl version`
```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}```
`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
