### ISSUE TITLE
Provide a way to configure per-service hostnames when using nip.io

### ISSUE THREAD

**Issue by davestephens** [garden-io/garden#1072]
## Bug / Feature Request
The nip.io integration is a nice feature (if a little lacking in documentation :smile:), but when running more than one service that need to serve from `/`, it causes problems. 

Consider the following config:
```
kind: Project
name: awesome
```
and
```
services:
  - name: service_one
    ingresses:
      - path: /
        port: http

[- snip -]

services:
  - name: service_two
    ingresses:
      - path: /
        port: http
```

### Current Behavior

Currently, both ingress objects in Kubernetes will be set with the same nip.io hostname like `awesome.192.168.39.189.nip.io`, so it's totally random which service you end up hitting if you hit the url. 

### Expected behavior

It would be nice if garden made use of the nip.io subdomain feature, and created ingress hostnames such as the following:

```
service_one.awesome.192.168.39.189.nip.io
service_two.awesome.192.168.39.189.nip.io
```
...and created the ingress objects accordingly.

Perhaps the module `name` field could be used for the subdomain part of the domain?

### Reproducible example

Use the https://github.com/garden-io/garden/blob/master/examples/multiple-modules/ example, and change the path to `/` for the ingress path on both services.

### Workaround

Using Nodeports

### Your environment

`garden version`: 0.10.3

`kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
`docker version`
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:54 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:14:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by edvald** [comment]
This one's a little tricky, design-wise. We used to automatically set hostnames but that turned out to be unexpected/unintuitive in other situations. People will often want multiple services on the same hostname, for example. But we can see if we can think of a nice way to do this. 

In the meantime, the way to achieve this would be to explicitly set the `hostname` on each ingress, and set the relevant hostnames in your `/etc/hosts` file.

**Comment by davestephens** [comment]
Thanks for your input on this.

Another idea I had was to rewrite the URLs with the ingress controller (per the [nginx docs](https://kubernetes.github.io/ingress-nginx/examples/rewrite/)), which would also be a reasonable solution. 

My config looks like this:
```
    ingresses:
      - path: "/service_one(/|$)(.*)"
        port: http
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
```
...sadly garden fails on validating the `path:` field:

```
$ garden deploy service_one
Deploy 

Error validating module service_one (/garden.yml): key .services[0][ingresses][0][path] must be a valid relative uri
```

So it seems garden is being a little over-zealous and failing on a valid path spec. If I remove the `(/|$)(.*)` from the `path:` field, then manually re-add it into the ingress object after deploying, it works great :smile: 

With documentation I feel this could be a good solution - what are your feelings on this?

**Comment by eysi09** [comment]
We now allow regexes in the ingress path.

**Comment by zvictor** [comment]
I am trying to achieve something similar to what was described in this issue.
The plan is to first define the `defaultHostname` in each provider, and then consume it in the service's `hostname`:

```yaml
providers:
  - name: local-kubernetes
    defaultHostname: 127.0.0.1.nip.io
    environments:
      - development
```

```yaml
    ingresses:
      - path: /
        hostname: storage.${providers.<provider-name>.outputs.default-hostname}
        port: http
```

It works fine as long as I hard code the value of `<provider-name>`, but how can I make it dynamic?

----

as a side note, the docs seems to have a broken link.
the first result for `hostname` throws a `Uncaught Error: No page for this search result`

![image](https://user-images.githubusercontent.com/181076/69868827-3a987900-12ab-11ea-9e5d-2ce8c06d4d3d.png)

**Comment by edvald** [comment]
Hey @zvictor. Our templating currently doesn't allow dynamic values for individual keys, although we definitely would like to support that. What you can do in the meantime is to use a ternary expression based on the name of the environment, as opposed to the provider name, e.g. `${environment.name == "local" ? providers.local-kubernetes.outputs.default-hostname : providers.kubernetes.outputs.default-hostname}`. That's quite verbose, but should do the job until we make some relevant enhancements to our template and variable handling.

**Comment by edvald** [comment]
Oh and we'll look into that docs issue. Seems to be an issue with Gitbook, which we use for our docs site.

**Comment by zvictor** [comment]
I see, but then it's better to just ignore the `defaultHostname` altogether and store a variable in the environment, no?

```yaml
# garden.development.env
hostname=127.0.0.1.nip.io
```

```yaml
    ingresses:
      - path: /
        hostname: storage.${var.hostname}
        port: http
```
