### ISSUE TITLE
Permit to get values from files when using helm module

### ISSUE THREAD

**Issue by thomasboni** [garden-io/garden#1098]
It would be great to add an option which permit to use external yaml file to get helm chart values.

My use case: currently, I don't use garden and I have a helm chart for my API, with default value file and one value file per environment (testing, stage, production...) I use the right value file depending of environment on which I want to deploy. Now, I want to try to add garden in this workflow and use for example my values file `my_api.testing.yaml` in helm deployment. 

As suggest by @edvald on slack: an option `valuesFile` should be ok. But, the possibility to specify a valuesFile depending of the current environment will be even better. For example:

```
kind: Module                            
name: my-api                          
description: ...
type: helm                              
chart: my-chart                               
valuesFiles:
  - environment: testing
    file: my-api.testing.yaml
  - environment: stage
    file: my-api.stage.yaml
  - environment: prod
    file: my-api.prod.yaml   
```

We should add the possibility to declare a `default` value too, in case of user doesn't want to specify one file for each environment. 

One thing annoy me with this implementation: environments names will be used in both files: project and module and modification of them in project file will need the modification on module project too.
