### ISSUE TITLE
openfaas modules does not support env

### ISSUE THREAD

**Issue by dcharbonnier** [garden-io/garden#1136]
None of the setup env variable are available in the function.
```
kind: Module
description: thumbnail serverless function
name: thumbnail-function
type: openfaas
lang: node
env:
  MINIO_ACCESS_KEY: ${var.minio-access-key}
  MINIO_SECRET_KEY: ${var.minio-secret-key}
  write_debug: true
  combine_output: false
dependencies:
  - minio
```
