### ISSUE TITLE
"ENOENT: no such file or directory" for helm module

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1235]
### Current Behavior

Garden errors with `ENOENT: no such file or directory, open myproject/.garden/build/kafka/cp-helm-charts/garden-values.yml`

This is the project layout:

```
myproject
   |---- kafka
           |--- garden.yml
           |--- cp-helm-charts // checked out from https://github.com/confluentinc/cp-helm-charts
```

and this is the relevant config file:

```
kind: Module
description: Apache Kafka
type: helm
name: kafka
chartPath: ./cp-helm-charts
values:
  persistence:
    enabled: false
```
