### ISSUE TITLE
Unhandled exception when variable is removed while on `garden dev`

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1257]
### Current Behavior

When running `garden dev`, if you remove a variable from the project config which is used in a module config you will get an unhandled exception like the following:

```sh
✔ providers                 → Getting status... → Done

🕑  Waiting for code changes...

🌻  Garden dashboard and API server running on http://localhost:61685
(node:28818) UnhandledPromiseRejectionWarning: Error: Invalid template string ${var.test-variable}: Unable to resolve one or more keys.
    at /Users/emanuele/code/garden/garden-service/src/template-string.ts:80:11
    at Generator.next (<anonymous>)
    at fulfilled (/Users/emanuele/code/garden/garden-service/build/src/template-string.js:12:58)
(node:28818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected behavior

Handle exceptions

### Reproducible example
garden.yml
```yaml
kind: Project
name: project-variables
variables:
  # This variable is referenced in the module configs, and overridden in the local project below
  service-replicas: 3
  frontend-service-name: the-frontend
environments:
  - name: local
    providers:
      - name: local-kubernetes
    variables:
      # We only want one replica of each service when developing locally
      service-replicas: 1
```

```yaml
kind: Module
name: frontend
description: Frontend service container
type: container
services:
  - name: ${var.frontend-service-name}
    replicas: ${var.service-replicas}   # <- Refers to the variable set in the project config
    ports:
      - name: http
        containerPort: 8080
[..]
```

Run `garden dev`
While deployed, comment out the variable `frontend-service-name` from the project config.
### Your environment

`garden version` 0.10.11

`kubectl version`

`docker version`
