### ISSUE TITLE
Kubernetes context errors aren't presented to the end user

### ISSUE THREAD

**Issue by Eronarn** [garden-io/garden#1283]
### Current Behavior

If someone tries to use a Garden environment with a Kubernetes context that they don't have access to, the error message is indistinguishable from a connectivity problem to the Kubernetes cluster (which we frequently see if someone isn't on our VPN):

```
Failed resolving provider kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to connect to Kubernetes cluster. Please make sure it is running, reachable and that you have the right context configured.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Failed resolving one or more provider configurations:
- kubernetes: Unable to connect to Kubernetes cluster. Please make sure it is running, reachable and that you have the right context configured.

See error.log for detailed error message
```

The actual error message is only in the error.log:

```
<snip>
  ingressHttpPort: 80
  ingressHttpsPort: 443
  setupIngressController: false
  path: /home/XXX/quantopian/qexec
  deploymentRegistry:
    hostname: '127.0.0.1:5000'
    namespace: staging
message: "Command failed with exit code 1 (EPERM): /home/XXX/.garden/tools/kubectl/804c71b3e6ad5976/kubectl --context=stg-admin@staging versionClient Version: version.Info{Major:\"1\", Minor:\"16\", GitVersion:\"v1.16.0\", GitCommit:\"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77\", GitTreeState:\"clean\", BuildDate:\"2019-09-18T14:36:53Z\", GoVersion:\"go1.12.9\", Compiler:\"gc\", Platform:\"linux/amd64\"}could not get token: AccessDenied: User: arn:aws:iam::XXX:user/XXX is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXX:role/XXX\n\tstatus code: 403, request id: XXX\nUnable to connect to the server: getting credentials: exec: exit status 1"
```

### Expected behavior

The IAM error message gets surfaced to the end user without having to read through error.log

### Suggested solution(s)

There should be different errors for a lack of connectivity to the API, failure to authenticate to the API, and lack of authorization to use the API. That way we don't need to go back to developers or have them read through a verbose error.log

### Your environment

(sorry, I'm not on their laptop, I don't have versions other than "the most recent Garden")
