### ISSUE TITLE
docs: varfile prefixed with unneeded dash in project config yaml

### ISSUE THREAD

**Issue by normanzb** [garden-io/garden#1295]
In <https://docs.garden.io/reference/config#project-yaml-schema>, it says:
```
environments:
  - providers:
      - name:
        environments:
  - varfile: garden.<env-name>.env
    variables: {}
    name:
```

I think that dash in front of varfile is unneeded, I think this error is because of the `.name` check here:
https://github.com/garden-io/garden/blob/master/garden-service/src/docs/config.ts#L302
I never used `JOI` before, but it seems to me checking the `name` property here should be changed to:

```
const isFirstChild = parent && parent === prevDesc
```
