### ISSUE TITLE
Set default storageClass to 'do-block-storage' for DigitalOcean host

### ISSUE THREAD

**Issue by Tails** [garden-io/garden#1325]
_**Note**: this is a host-specific request. I would understand if host (type)-specific configurations would be too much to create defaults for. However, I feel it's warranted since DigitalOcean is one of the major provides that people are bound to use._

## Bug
Deploying to DigitalOcean host does not work with defaults.

### Current Behavior
When initiating the cluster using ```garden plugins kubernetes cluster-init```, it hangs on creating the NFS provisioner.

### Expected behavior
I expect the initialisation to work without my interference.

### Reproducible example
- Create a DigitalOcean hosted Kubernetes account at https://www.digitalocean.com/products/kubernetes/. 
- Deploy kubernetes cluster as described here: https://www.digitalocean.com/docs/kubernetes/how-to/create-clusters/
- Run ```garden plugins kubernetes cluster-init``` on any example project. (OpenFaas in my case)

### Workaround
Use ```storageClass: do-block-storage``` for all NFS entries like so:

``` yaml
providers:
  - name: kubernetes
    environments: [remote]
    context: digitalocean
    namespace: digitalocean-openfaas
    defaultHostname: identifier.k8s.ondigitalocean.com
    buildMode: kaniko
    storage:
      builder:
        storageClass: do-block-storage
      nfs:
        storageClass: do-block-storage
      registry:
        storageClass: do-block-storage
      sync:
        storageClass: do-block-storage
```

Tested on both Linux (Ubuntu 18) and MacOS.

### Suggested solution(s)
Use ```do-block-storage``` by default when deploying to a Digitalocean host. 

### Your environment

`garden version`
0.10.14

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"archive", BuildDate:"2019-10-21T09:32:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
