### ISSUE TITLE
Confusion over `local-openfaas` provider

### ISSUE THREAD

**Issue by ozburo** [garden-io/garden#1358]
Hopefully I'm not the only one confused by this and we can get some clarification for everyone concerned.

The Docs refer to a "local-openfaas" provider much like it refers to a "local-kubernetes" provider: are we supposed to use the "local-openfaas" when running local developments/clusters?

I tried setting "local-openfaas" as my provider:

```
kind: Project
name: my-project
environments:
  - name: local
    providers:
      - name: local-kubernetes
      - name: local-openfaas
```

But I get an error "Cannot read property 'install' of undefined"; however when I use regular "openfaas" it runs.

I'm using an up-to-date Docker of Mac running K8s 1.14.8 with fresh reseted cluster/disk.
