### ISSUE TITLE
how to take advantage of multi-stage dockerfiles?

### ISSUE THREAD

**Issue by zvictor** [garden-io/garden#1359]
Currently, the modules in my [garden project](https://github.com/feats/hello-garden) use one single image each. Ideally, I would like to dynamically change these images depending on, for instance, if garden is running tests on them or deploying to production instead.

I noticed that I can use `build.targetImage` to select the right image of [my multi-stage Dockerfiles](https://github.com/feats/hello-garden/blob/master/src/frontend/Dockerfile), but that would apply to all cases and not dynamically as I wish.

--- 

What I am dreaming about is something like this:

```yml
...
type: container
name: frontend
tests:
  - name: unit
    args: [npm, run, test:unit]
    targetImage: tests
hotReload:
  targetImage: development
  sync:
    - target: /app
services:
  - name: frontend-svc
    targetImage: production

```

* Can I achieve something similar to this with garden?
* If not, what would be the recommended way to, let's say, have `nodemon` and `cypress` available while developing and testing but not while deploying to production?
