### ISSUE TITLE
In-cluster builds fail to push to garden registry with microk8s clusters

### ISSUE THREAD

**Issue by khaled** [garden-io/garden#1380]
### Current behavior

Pushes to the in-cluster registry installed by garden fails.

### Expected behavior

Pushes succeed!

### Reproducible example

Any example with in-cluster building.  I used in-cluster docker in my trials.

### Workaround

I suspect this has to do with `hostPort` (which the registry proxy appears to use) not being properly supported by microK8s.

I worked around this by performing the following steps:

* Modified `/var/snap/microk8s/current/args/kube-apiserver` on the cluster node, adding `--service-node-port-range 5000-32767` (it defaults to `30000-32767`).

* Modified `/var/snap/microk8s/current/args/docker-daemon.json` on the cluster node, adding `localhost:5000` to the list of insecure-registries.

* Restarted both the kube apiserver and the docker daemon:

	```bash
	sudo systemctl restart snap.microk8s.daemon-apiserver.service
	sudo systemctl restart snap.microk8s.daemon-docker.service
	```

* Delete the registry proxy DaemonSet:

	```
	kubectl delete ds/garden-registry-proxy -n garden-system
	```
		
* Created a NodePort service on port 5000, pointing to the registry:

	```yaml
	apiVersion: v1
	kind: Service
	metadata:
	  name: garden-docker-registry-nodeport
	  namespace: garden-system
	spec:
	  type: NodePort
	  ports:
	    - name: registry-port
	      nodePort: 5000
	      port: 5000
	      protocol: TCP
	      targetPort: 5000
	  selector:
	    app: docker-registry
	```
	
### Suggested solution(s)

It might simplify things to be able to use the microk8s registry addon, which listens on a host port of 32000, instead of garden installing its own.  MicroK8s is pre-configured with 32000 as an insecure registry.

### Your environment

```
$ garden --version

0.10.15
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```
```
$ microk8s.docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:56:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Tue Feb 12 22:47:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
