### ISSUE TITLE
Feature Request: pod annotations

### ISSUE THREAD

**Issue by vranystepan** [garden-io/garden#1388]
I'd like to use garden with DAPR. However, I'd need to put some annotations to the spec.template.annotations of the Deployment resource:

```yaml
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "node-subscriber"
        dapr.io/port: "3000"
```

Is there any way how to configure pods' annotations?

**Comment by edvald** [comment]
Hey @vranystepan! The only way right now is to use your own manifests, via the `kubernetes` module type (https://docs.garden.io/reference/module-types/kubernetes). That gives you full flexibility, but in turn a bit more manual work.

We will be adding options to modify the auto-generated manifests soon though. Basically we're adding some escape hatches via kustomize and JSON patches, so you should be able to achieve most things you'd like.

DAPR seems interesting btw. Have you been using it for a while?

**Comment by vranystepan** [comment]
Thanks, it actually works pretty well!

I'm using something like this and I'm pretty happy :) 

```yaml
kind: Module
name: backend-image
description: Go service container
type: container
image: backend
tests:
  - name: unit
    args: ["echo", "works!!"]
---
kind: Module
name: backend
description: Go service container
type: kubernetes
build:
  dependencies:
    - name: backend-image
manifests:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend-${modules.backend-image.version}
      labels:
        app: backend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: backend
      template:
        metadata:
          labels:
            app: backend
        spec:
          containers:
          - name: main
            image: ${modules.backend-image.outputs.deployment-image-name}:${modules.backend-image.version}
            ports:
            - containerPort: 80
```

Regarding DAPR, it's still in alpha but it's actually pretty cool tool! Now I'm preparing slides and demo for CNCF meetup in Prague so I'd like to put things together and show some real flow with Garden :)

Anyways, feel free to close this issue. And sorry for disrupting you! 
Thanks for the work you are doing!
