### ISSUE TITLE
Improve invalid domain error message when configuring cert-manager

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1487]
### Current Behavior

Reported by Daniel Killenberger on community slack.

When configuring the cert-manager integration you are required to specify a hostname.
The integration will fail to validate the `hostnames` field when using wildcard domains. This is expected becuase we currently only support the LE HTTP-01 challenge which doesn't allow wildcard domains but the message can be improved to provide more info.

This is the error message:

`Error validating provider configuration (/garden.yml): key .tlsCertificates[0][hostnames][0] must be a valid hostname`

### Reproducible example

Example of a failing configuration in the `garden.yml`:
```yaml
defaultHostname: ${local.env.GARDEN_NAMESPACE}.dev.domain.com
setupIngressController: nginx
certManager:
  install: true
  email: daniel@domain.com
  issuer: acme
  acmeChallengeType: HTTP-01
  acmeServer: letsencrypt-staging
tlsCertificates:
  - name: staging-tls-certificate
    managedBy: cert-manager
    hostnames:
      - ‘*.dev.domain.com’
      - dev.domain.com
    secretRef:
    name: tls-certificate
    namespace: ${local.env.GARDEN_NAMESPACE}
```

### Suggested solution(s)

Improve the error message.

### Your environment

`garden version`

`kubectl version`

`docker version`
