### ISSUE TITLE
garden run test <module> <test> locks when referencing invalid secret

### ISSUE THREAD

**Issue by DanielKillenberger** [garden-io/garden#1513]
### Current Behavior

`garden run test <module> <test>` completely locks its process after `Getting build status for v-xxxx Done(took **0.7sec)` if a key within a secret is not available on kubernetes.
It uses 0% cpu and the process cannot be terminated with ctrl+c; only after terminating the garden process from system monitor the terminal is usable again.

This does not happen with `garden dev` for example which throws an error that a key within the secret is undefined.

### Expected behavior

`garden run test <module> <test>` should fail gracefully if secret referenced in garden.yml does not exist.

### Reproducible example

Define a test for a container module with environment variable that refers a secret which doesn't exist.

The exact config that failed for me was the following:

```
name: api
kind: Module
description: API Service
type: container
include:
  - packages/api/**
  - packages/service-contracts/**
  - package*.json
  - lerna.json
dockerfile: packages/api/Dockerfile
hotReload:
  sync:
    - source: ./packages/api/dist
      target: /app/packages/api/dist
tests:
  - name: it-postgres
    command: [lerna, run, test:it:postgres]
    dependencies:
      - cloudsql-proxy
    env:
      PGHOST: cloudsql-proxy
      PGDATABASE: postgres
      PGPORT: 5432
      PGUSER: 
        secretRef:
          name: cloudsql-db-credentials
          key: username
      PGPASSWORD:
        secretRef:
          name: cloudsql-db-credentials
          key: password

```
The key `username` wasn't defined in the secret `cloudsql-db-credentials`.

### Workaround

Fix the faulty secret reference.

### Your environment
MacOS
`garden version`: 0.11.0
