### ISSUE TITLE
Unable to target local helm chart with chartPath in a helm module

### ISSUE THREAD

**Issue by popul** [garden-io/garden#1550]
### Current Behavior

I want to use chartPath for helm local charts, but it fails when i run `garden run module foo-helm  `

![image](https://user-images.githubusercontent.com/2310967/73165487-25499a80-40f4-11ea-8ae6-f9fb5bb458bf.png)

### Expected behavior

Be able to target a subfolder when working with local helm charts

### Reproducible example
Folder structure:
```
- garden.yml
- foo/
  - Chart.yaml
```

garden.yml content

```yaml
kind: Module
description: foo-helm description
type: helm
name: foo-helm
chartPath: ./foo
```

chart.yaml content:
```yaml
apiVersion: v2
name: foo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0
```

### Workaround

Move garden.yml in chart folder

### Your environment

`garden version` : 0.11.1

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`
````
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          commit: d736ef14f0288d6993a1845745d6756cfc9ddd5a
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by eysi09** [comment]
It might be that Garden is not finding the chart because it's using the default [`include`](https://docs.garden.io/module-types/helm#include) value for Helm modules.

It basically defaults to `["*", "charts/**/*", "templates/**/*"]` if not set explicitly by the user.

The issue here is that we should be always make sure that the `chartPath` value is included. To verify, could you try setting the `include` field and see if that fixes it? At least it's a better workaround than moving the `garden.yml` file.

E.g.:

```yaml
kind: Module
description: foo-helm description
type: helm
name: foo-helm
include: ["foo"]
chartPath: ./foo
```

**Comment by popul** [comment]
This one works  (using default include values) 👍 

File structure
```
- garden.yml
- charts/
  - foo/
    - Chart.yaml
```
with this garden.yml content:
```yaml
kind: Module
description: foo-helm description
type: helm
name: foo-helm
chartPath: ./charts/foo
```

But this configuration not 👎 
```
- garden.yml
- foo/
    - Chart.yaml
```
with this garden.yml content:
```yaml
kind: Module
description: foo-helm description
type: helm
name: foo-helm
include: ["foo"]
chartPath: ./foo
```
