### ISSUE TITLE
Unexpected error when templating with ternary operator and ||

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1563]
## Bug

Noticed two issues when using a ternary operator and a `||` in template strings.

### Current Behavior

Firstly, the following template string:

```yaml
TEST_OUTPUT: "${runtime.tasks.echo-hello ? runtime.tasks.echo-hello.outputs.log : 'default'}"
```

will fail with:

```console
Invalid template string ${runtime.tasks.echo-hello ? runtime.tasks.echo-hello.outputs.log : 'default'}: Circular reference detected when
resolving key  (runtime -> runtime.tasks.echo-hello)
```

Secondly, the following template string:

```yaml
TEST_OUTPUT: "${runtime.tasks.no-task.outputs.log || 'default'}"
```

fails with:

```console
Unable to resolve one or more runtime template values for service 'backend': ${runtime.tasks.no-task.outputs.log}
```

**if** `no-task` doesn't exist.

Finally the error isn't very helpful if the `dependencies` field is not set. It's the same as above.

### Expected behavior

Should work.

### Reproducible example

```yaml
kind: Module
name: frontend
type: container
tasks:
  - name: echo-hello
    args: ["echo", "hello"]
...

---

kind: Module
name: backend
type: container
services:
  - name: backend
    ...
    env:
      TEST_OUTPUT: "${runtime.tasks.echo-hello ? runtime.tasks.echo-hello.outputs.log : 'default'}" # FIXME
      TEST_OUTPUT: "${runtime.tasks.echo-hello.outputs.log || 'default'}" # And FIXME
    dependencies: ["echo-hello"]
```

### Workaround

N/A
