### ISSUE TITLE
Garden fails to validate config when setting a duplicate variable 

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1572]
### Current Behavior

If I the same variable twice by mistake in the project `garden.yml`, Garden will complain it coulnd't parse the config file as a valid YAML.

### Expected behavior

I want Garden to tell me there is a duplicate variable.

### Reproducible example

```yaml
# project garden.yml

kind: Project
name: demo-project
# defaultEnvironment: "remote" # Uncomment if you'd like the remote environment to be the default for this project.
environments:
  - name: local
  - name: remote
providers:
  - name: local-kubernetes
    environments: [local]
  - name: kubernetes
    environments: [remote]
    # Replace these values as appropriate
    context: gke_garden-dev-200012_europe-west1-b_garden-dev-1
    namespace: demo-project-testing-${local.env.USER || local.username}
    defaultHostname: ${local.env.USER || local.username}-demo-project.dev-1.sys.garden
    buildMode: cluster-docker
variables:
  test-var: true
  test-var: true

```
garden validate output:

```sh
$ g validate
Could not parse garden.yml in directory /Users/emanuele/code/garden/examples/demo-project as valid YAML
```

### Workaround

None

### Suggested solution(s)

We could tackle this in two ways:
- Detect the duplicate variable and print a warning/error message with the name of the variable.
- Use the last occurence of the variable (but I'd suggest to print out a warning nevertheless).

If the proposed solutions are not feasible, we could potentially list few options of why a config file is not valid in the error message or link to a troubleshooting page.
