### ISSUE TITLE
Helm fails to build when there are external dependencies in the helm chart

### ISSUE THREAD

**Issue by jmaroeder** [garden-io/garden#1620]
## Bug
When attempting to build a helm module with external dependencies in its `Chart.yaml` file, the build fails. It appears that this is due to the lack of a call to `helm dependency update` prior to running `helm template`.

### Current Behavior

```
Failed building flow-fundamentals. Here is the output:
Command "~/.garden/tools/helm3/dd4668d875bedaf5/darwin-amd64/helm --kube-context minikube --namespace flow template flow-fundamentals --namespace flow --values
XXX/.garden/build/flow-fundamentals/charts/flow-fundamentals/garden-values.yml
XXX/.garden/build/flow-fundamentals/charts/flow-fundamentals" failed with code 1:

Error: found in Chart.yaml, but missing in charts/ directory: postgresql
```

### Expected behavior

The build to succeed.

### Reproducible example

```yaml
# module garden.yml
kind: Module
type: helm
name: flow-fundamentals
repositoryUrl: XXX
chartPath: charts/flow-fundamentals
```    
```yaml
# Chart.yaml
apiVersion: v2
name: flow-fundamentals
# ...
dependencies:
- name: postgresql
  version: 8.3.3
  repository: https://kubernetes-charts.storage.googleapis.com/
```

### Workaround

None found yet. I was able to run the failing command manually and add the `--dependency-update` flag, and it succeeded, but every time `garden` attempts to rebuild it wipes out the `charts` directory

### Suggested solution(s)

Run `helm template` with the `--dependency-update` flag

### Additional context

N/A

### Your environment

`garden version`: `0.11.3`

`kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
