### ISSUE TITLE
hotReload sync source must be a relative path

### ISSUE THREAD

**Issue by marekaf** [garden-io/garden#1656]
## Bug
Hello garden maintainers <3 

I run into an issue. I'm getting this error:

### Current Behavior
```
Error validating module 'box' (/garden.yml): key .hotReload.sync[0][source] must be a relative path (may not be an absolute
path), key .hotReload.sync[0][source] must be a relative sub-path (may not contain '..' segments or be an absolute path)
```
### Expected behavior

The docs mention an absolute path though
 https://docs.garden.io/guides/hot-reload

```
  hotReload:
    sync:
      - source: /foo
        target: /app/foo
      - source: /bar
        target: /app/bar
```

### Reproducible example
```
kind: Module
name: box
description: Frontend service container
type: container
hotReload:
  sync:
  - source: /src/
    target: /src/
```
### Suggested solution(s)

I'd just edit the documentation accordingly

### Your environment

```
 ~  garden version
0.11.5
 ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:31:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-aae39f", GitCommit:"aae39f4697508697bf16c0de4a5687d464f4da81", GitTreeState:"clean", BuildDate:"2019-12-23T08:19:12Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
 ~  docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

thanks for all the great work! <3
