### ISSUE TITLE
[FEATURE]: postSyncCommand scoped to sync targets

### ISSUE THREAD

**Issue by elliott-davis** [garden-io/garden#1726]
### Background / Motivation

I have assets that use gulp, webpack and Go to compile. Ideally I'd be able to specify a script or command for each of them to execute if I modify files in their respective directories

### What should the user be able to do?

Provide a postSyncCommand with the list of targets to sync so that postSyncCommands are associated with targets rather than the syncing process as a whole.

### Why do they want to do this? What problem does it solve?

Having to have a script identify what files changed and execute the correct script is a pain. It would be a lot nicer to list a postSyncCommand with the files I'm syncing for changes.

### Suggested Implementation(s)

Currently the API looks like:
```
hotReload:
  sync:
    - target: /app
      source: src/app
    - ....
```

I'd propose that gets changed to:

```
hotReload:
  sync:
    - target: /app
      source: src/app
      postSyncCommand:
        - some_script.sh
    - ....
```

I think it would be possible to update [this](https://github.com/garden-io/garden/blob/86ee925cfa3fa975aee86b5189737293c86f2c77/garden-service/src/plugins/kubernetes/hot-reload.ts#L311-L323) to exist in [this block](https://github.com/garden-io/garden/blob/86ee925cfa3fa975aee86b5189737293c86f2c77/garden-service/src/plugins/kubernetes/hot-reload.ts#L301-L309) which would facilitate this behavior. 

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
