### ISSUE TITLE
persistentvolumeclaim dependencies not working

### ISSUE THREAD

**Issue by wojtkowiak** [garden-io/garden#1731]
### Current Behavior

```yml
kind: Module
type: persistentvolumeclaim
name: storage
description: Main storage for storing backtesting data.
dependencies: 
 - nfs-pv
```

`Error validating module 'storage' (/garden.yml): key .dependencies must be a string`

Hmm somebody needs to make up his mind about this :)

changed to:

```yml
kind: Module
type: persistentvolumeclaim
name: storage
description: Main storage for storing backtesting data.
dependencies: "nfs-pv"
```

`Error validating configure persistentvolumeclaim output from provider local-kubernetes: key .moduleConfig.serviceConfigs[0][dependencies] must be an array`

### Expected behavior

A way to use `dependencies` with `persistentvolumeclaim`

### Reproducible example

The example is above

### Additional context

Sorry if that's me just wanting something weird, not exactly a k8 expert here

### Your environment

garder/docker/kubectl at the newest
