### ISSUE TITLE
Building `openfaas-system` fails if hostname is missing

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1758]
### Current Behavior

If a hostname is missing for the OpenFaaS provider, `garden deploy` fails with:

```console
Deploy 🚀

✔ providers                 → Getting status... → Done
✖ openfaas--system          → Building version v-a1b48b8644...

Failed building openfaas--system. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
unacceptable kind of an object to dump [object Undefined]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 deploy task(s) failed!

See error.log for detailed error message

```

This is because the JSON representation of the schema has `ingress.host` set to undefined:

```js
  ingress: {
    enabled: true,
    hosts: [
      {
        host: undefined,
        serviceName: 'gateway',
        servicePort: 8080,
        path: '/function/'
      },
      {
        host: undefined,
        serviceName: 'gateway',
        servicePort: 8080,
        path: '/system/'
      }
    ]
  },
```

which causes the `yaml.safeDump` call to throw, here: https://github.com/garden-io/garden/blob/master/garden-service/src/util/util.ts#L303

### Expected behavior

Hostname should not be set to `undefined`. And validated if required but missing.

### Reproducible example

Use this:

```yaml
kind: Project
name: openfaas
environments:
  - name: local
providers:
  - name: local-kubernetes
    environments: [local]
  - name: openfaas
    gatewayUrl: "https://system.o6s.io/"
    faasNetes:
      install: false
```

### Workaround

Set the hostname for the `openfaas` provider: https://docs.garden.io/reference/providers/openfaas#providers-hostname

**Comment by pbaezab** [comment]
Thanks @eysi09 

Now the error is in the stack.yml, is genarated without https :(

```
Failed deploying service 'hello-function' (from module 'hello-function'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command "/Users/pbaezab/.garden/tools/faas-cli/05fea03138d1aee5/faas-cli-darwin deploy -f stack.yml" failed with code 1:

Here's the full output:

Deploying: hello-function.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Is OpenFaaS deployed? Do you need to specify the --gateway flag?
Put https://system.o6s.io:80/system/functions: http: server gave HTTP response to HTTPS client

Function 'hello-function' failed to deploy with status code: 500

Deploying: hello-function.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Is OpenFaaS deployed? Do you need to specify the --gateway flag?
Put https://system.o6s.io:80/system/functions: http: server gave HTTP response to HTTPS client

Function 'hello-function' failed to deploy with status code: 500
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 deploy task(s) failed!

See error.log for detailed error message
```

The final stack.yml file is:


```
provider:
  name: faas
  gateway: 'http://system.o6s.io:80'
functions:
  hello-function:
    lang: node
    handler: .
    image: 'hello-function:v-d531d662e2'
    environment:
      GARDEN_VERSION: v-d531d662e2
      GARDEN_DEPENDENCIES: >-
        [{"moduleName":"hello-function","name":"hello-function","type":"build","version":"v-d531d662e2"},{"moduleName":"openfaas--system","name":"openfaas--system","type":"service","version":"v-f416d942b3"}]
```
