### ISSUE TITLE
Artifacts are duplicated when using multiple source/target tuples with different targets 

### ISSUE THREAD

**Issue by lucas-sonnabend** [garden-io/garden#1781]
## Feature Request

It looks like at the moment garden only supports a single artifact target properly, I would like to define several source/target tuples, each copying artifacts from the source to a distinct target.

At the moment when you declare several targets and sources all artifacts go into all target directories

### Background / Motivation
I defined artifacts like this
```
    artifacts:
      - source: /tests/cypress/videos_copied/*
        target: test-results/cypress/videos
      - source: /tests/cypress/logs/*
        target: test-results/cypress/logs
      - source: /tests/cypress/snapshots/*
        target: test-results/cypress/snapshots
```
And I ended up with logs, snapshots and videos in all target directories, which made it really annoying to explore them

The documentation should also reflect this behaviour 

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
