### ISSUE TITLE
Garden dev using +700MB memory

### ISSUE THREAD

**Issue by GavinRay97** [garden-io/garden#1786]
## Bug

![image](https://user-images.githubusercontent.com/26604994/78832279-f46dc780-79b8-11ea-844d-f4c28fde8e49.png)

![image](https://user-images.githubusercontent.com/26604994/78832460-4ca4c980-79b9-11ea-93a1-0bedf2aeb790.png)

### Current Behavior

After updating to v0.11.11 from v0.11.5 (last working version until recently due to strange Docker experimental command bug), I noticed that in `htop` Garden was at the top of my memory usage. I might be mistaken, but I have 8GB RAM and so often have to check and be cautious about memory + CPU usage due to frequent freezes during development. I don't recall `garden` ever being near the top of my resource list before.

Is there any possibility something could have increased memory usage in recent releases?

### Your environment

Ubuntu 19.10, Garden v0.11.11, Microk8s

`kubectl version`
```go
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`
```yaml
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by edvald** [comment]
Hmm. Thanks for flagging this @GavinRay97. Not sure what exactly might be causing this. 

Just to get some points of reference, would you mind checking the memory usage at the older release with the same project, and perhaps as well checking how high it goes when running e.g. `garden deploy` (without `--watch`)? That would be super helpful. 

My first suspicion (because it's come up before) is something to do with file watching on linux, but I'm not quite sure yet.

**Comment by GavinRay97** [comment]
Video running `garden dev` vs `garden deploy` with `htop` open:
https://streamable.com/bosun6

Difference between the two is roughly ~3.5-3.8% memory usage with `deploy`, and 12-14% memory usage with `dev` (8GB RAM, so this time it went above 1GB memory peaking at around 1,100MB)

Will edit with another video of `v0.11.5` in a second.

**Comment by edvald** [comment]
Ok. That strongly indicates that it's the watcher. So, we lean on https://github.com/paulmillr/chokidar for the file watching, which AFAICT does its very best to manage memory consumption but it's tough on linux because of OS limitations basically.

That said, you could most likely improve this by excluding files from being scanned and watched, using the `modules.exclude[]` field in your project config. From prior context I'm assuming you have a bunch of `node_modules` directories in there. Explicitly adding those might help. For example:

```yaml
kind: Project 
name: my-project:
...
modules:
  exclude:
    - node_modules/**/*
      **/node_modules/**/*
      some-specific-dir/node_modules/**/*
```

Of course, set those specific paths depending on your exact setup. We've so far been a little cautious with automatically excluding directories like this, because there's a lot of cases to consider, but perhaps we could revisit that. That is, if that turns out to be the issue.
