### ISSUE TITLE
Mounting secrets as volumes for the container module type

### ISSUE THREAD

**Issue by LeoDupont** [garden-io/garden#1793]
Hello

I'm trying to provide a Google Cloud service account key file to my services, following this tutorial: https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform

I've already created a Kubernetes secret from my key file ([Step 4](https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform#step_4_import_credentials_as_a_secret)):
```bash
kubectl create secret generic pubsub-key --from-file=key.json=PATH-TO-KEY-FILE.json
```

But now I don't know how I could provide a secret file in a volume and how I could mount this volume to my Garden services ([Step 5](https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform#step_5_configure_the_application_with_the_secret)).  In the tutorial, the Deployment looks like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
spec:
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: subscriber
        image: gcr.io/google-samples/pubsub-sample:v1
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
```

Do you know how I could achieve these `volumes` and `volumeMounts` parts in a Garden module?
