### ISSUE TITLE
Image pull in maven-container does not use imagePullSecret

### ISSUE THREAD

**Issue by padamson-r7** [garden-io/garden#1809]
### Current Behavior
Image pull using a `container` module will successfully pull the image from my private repo where as maven-container will fail due to lack of authentication.

### Expected behavior
i would like Image pull to work in maven-container as it does in container modules.

### Reproducible example
The project below contains an image pull secret and 2 modules which reference a private image.
In the working and failing cases, I delete the image before deploying that module.
The image pull secret already exists in the default namespace.
```
kind: Project
name: temp
environments:
- name: local
  providers:
  - name: maven-container
  - name: local-kubernetes
    imagePullSecrets:
    - name: ecr-staging


---

kind: Module
name: works
type: container
image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden
services:
- name: works

---

kind: Module
name: breaks
type: maven-container
image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden
services:
- name: breaks

# force maven module to fall back to image pull
useDefaultDockerfile: false
# required field but not used in pull scenario
jarPath: foo.jar

```
Working case: (container module)
I delete the image and when garden deploys it will use the secret to successfully pull the image from ECR
```
$ docker image rm  xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden
$ garden deploy works
Deploy 🚀

✔ providers                 → Getting status... → Done
✔ works                     → Getting build status for v-f62050d85e... → Done (took 0 sec)
⠦ works                     → Deploying version v-f62050d85e...
   ℹ works                     → Deployment/works-v-f62050d85e: Pulling image "xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden"
✔ works                     → Deploying version v-f62050d85e... → Done (took 13 sec)
   ℹ works                     → Resources ready
```

Failing case: (maven-container module)
I delete the image and when garden deploys it attempts to pull the image but fails due to no authentication
```
$docker image rm xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden

$ garden deploy breaks
Deploy 🚀

✔ providers                 → Getting status... → Done
✖ breaks                    → Pulling image xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden...

Failed building breaks. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to run docker command: Command "docker pull xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app:garden" failed with code 1:

Error response from daemon: pull access denied for xxxxx.dkr.ecr.us-east-1.amazonaws.com/license-app, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and
 try again.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 deploy task(s) failed!
```

### Workaround

pre-authenticating manually using `aws ecr get-login` command before attempting to pull

### Your environment

`garden version`
0.11.11

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
