### ISSUE TITLE
Garden resolves template strings for environments that aren't in use

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1814]
### Current Behavior

Garden resolves template strings for environments other than the one in use. This can cause issues, for example when some environment expects an env var that is not set in the _current_ environment. 

For example, a `ci` environment might have the following config:

```yaml
environments:
  - name: ci
     variables: ${local.env.SOME_VAL}
```

This will cause Garden to throw:

```console
Invalid template string ${local.env.SOME_VAL}: Could not find key SOME_VAL under local.env.
```  

for all envs that don't export `SOME_VAL`.

### Expected behavior

Garden shouldn't resolve template strings for environments other than the one in use.

### Reproducible example

In for example the `demo-project`, add the following to the project level `garden.yml`:

```yaml
kind: Project
name: demo-project
environments:
  - name: local
  - name: remote
  - name: bad-env
    variables:
      not-set: ${local.env.NOT_SET}
providers:
  # ...
```

and run a Garden command with `--env local|remote`. 

### Workaround

Use a fallback value, for example:

```
not-set: ${local.env.NOT_SET || ""}
```

or make it optional:

```
not-set: ${local.env.NOT_SET}?
```

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

Latest `master`
