### ISSUE TITLE
Garden resolves template strings for disabled modules

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1815]
Flagging this here for visibility and so that we can discuss fixes and workarounds.

## Problem

Currently, Garden attempts to resolve template strings for modules, services, tests, and tasks, even if they are disabled. 

For example, let's say we have two environments, `dev` and `staging`, and a database module that we only use in `dev` (perhaps we have a persistent cloud db for `staging`). 

Our `garden.yml` would then need to look like this:

```yaml
kind: Project
name: my-project
variables:
  db-password: fake-pwd # <--- This variable is only used in `dev` but we still need to give it a fake value here for all other environments 
environments:
  - name: dev
    variables:
      db-password: admin1234 # <--- Here we actually set the value
  - name: staging
providers:
  # ...

---

kind: Module
type: container
disabled: "${environment.name != 'dev'}" # <--- Only used in the dev environment
name: postgres
# ...
services:
  env:
    DB_PASSWORD: ${var.db-password} # <--- Here we consume the variable, but only in dev
```

For large projects, we'd end up creating a lot of fake variables. 

In my opinion, a bigger issue is that if we accidentally remove the actual value from `environments.dev`, Garden will just fallback to the default `fake-pwd` value and still try to deploy the database but with the wrong `DB_PASSWORD` set.

Similarly, if we enable the `postgres` module in another environment, say `qa`, but forget to add the `db-password` variable to the `qa` environment definition, Garden will still deploy, again with the `fake-pwd` password.

It would great to be able to lean on the Garden template resolution system in the examples above and know that if some values are missing, Garden will fail fast. Beyond that, it feels awkward to set a bunch of fake values that never get used.

## Workarounds

Use a default fallback variable like described above, or make the variable optional where it's consumed:

```yaml
services:
  env:
    DB_PASSWORD: ${var.db-password}? # <--- This is optional because of the ?
```

or set a fallback where it's consumed:

```yaml
services:
  env:
    DB_PASSWORD: "${var.db-password || XXXXXX}"
```

## Further Discussion

I haven't looked into how the templating system could handle this, so I can't really propose a solution at the moment. But I'm assuming we could partially resolve disabled modules. I'm also assuming there's a lot more to it. For example, how do we handle module outputs from disabled modules?

Also, how do we handle other disabled entities? For example a disabled test within an enabled module.

Finally, is there a case to be made for default values? Modules (and other entities) aren't directly coupled to their environments, and could be disabled for other reasons. So I guess you could argue that if a modules needs a variable, it should always be defined. You could then proceed to disable/enable it, either based on environment or other factors, without having to move a bunch of variables around.
