### ISSUE TITLE
Missing documentation for services[].ports[].hostPort

### ISSUE THREAD

**Issue by mnpenner** [garden-io/garden#1825]
### Current Behavior

[`services[].ports[].hostPort`](https://docs.garden.io/reference/module-types/container#services-ports-hostport) is undocumented.

### Expected behavior

Document all the things.

### Reproducible example

Click the link.

### Workaround

Dive into the source code to figure out how it works?

### Suggested solution(s)

Add some documentation.

### Additional context

I'm trying to figure out how to expose MariaDB to my host machine for testing. Not sure if I'm supposed to use `hostPort` or `ingress` or what. Ingress seems funny because it's not HTTP.

### Your environment

Chrome 81

**Comment by eysi09** [comment]
Hi @mnpenner! 

You're right, this field is missing documentation. We're actually deprecating it because it's generally advised against using it, from the [K8s docs](https://kubernetes.io/docs/concepts/configuration/overview/):

> Don’t specify a `hostPort` for a Pod unless it is absolutely necessary. When you bind a Pod to a `hostPort`, it limits the number of places the Pod can be scheduled, because each `<hostIP, hostPort, protocol>` combination must be unique. If you don’t specify the `hostIP` and `protocol` explicitly, Kubernetes will use `0.0.0.0` as the default `hostIP` and `TCP` as the default `protocol`.

> If you only need access to the port for debugging purposes, you can use the apiserver proxy or kubectl port-forward.

> If you explicitly need to expose a Pod’s port on the node, consider using a NodePort Service before resorting to `hostPort`.

So in your case, you should be able to reach the DB by creating an `ingress`.

**Comment by mnpenner** [comment]
@eysi09 You sure? [This](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/) says:

> Ingress does not support TCP or UDP services

But it does propose an alternative solution. Maybe I'll try that. Port-forwarding would probably also work for dev.

**Comment by tobiasmcnulty** [comment]
I couldn't find a way to get this working either. Here's what we ended up doing instead:

```
# hostPort does not appear to work in Garden (and is deprecated), so we need add it ourselves.
# https://docs.garden.io/reference/module-types/container#services-.ports-.hostport
kind: Command
name: expose-mysql
description:
  short: Patch the garden Deployment to expose the MySQL port.
exec:
  command:
    - kubectl
    - -n
    - db-default
    - patch
    - deployment
    - mysql
    - --patch
    - '{"spec": {"template": {"spec": {"containers": [{"name": "mysql", "ports": [{"containerPort": 3306, "hostPort": 3306, "name": "mysql", "protocol": "TCP"}]}]}}}}'

```
