### ISSUE TITLE
Modules that reference runtime task output ignore concurrency limits

### ISSUE THREAD

**Issue by padamson-r7** [garden-io/garden#1832]
### Current Behavior

A module that references the runtime output of a task will not obey concurrency limits set by the task graph.

### Expected behavior

GARDEN_TASK_CONCURRENCY_LIMIT should be respected, or the default of 6 should be respected if not set.

### Reproducible example

run the command `GARDEN_TASK_CONCURRENCY_LIMIT=1 garden deploy` in the following project.
You will see that it deploys many services in parallel, i've seen 11 to 15 at once while testing this example.

If you remove the `FOO` environment variable referencing the task runtime output, the same command will deploy all the apps one at a time.

Without the limit set, the default of 6 still does not apply.

(The `sleep` healthcheck emulates waiting for an app to go healthy; there's no code running in the container apart from a tiny web server to keep the container live.)

```
kind: Project
name: temp
environments:
- name: local
  providers:
  - name: local-kubernetes

---

kind: Module
name: setup
type: exec
tasks:
  - name: host
    command: [echo, foo]
include: []

---

kind: Module
name: helloworldx16
type: container
image: crccheck/hello-world:latest

services:
- name: one
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: two
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: three
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: four
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: five
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: six
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: seven
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: eight
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: nine
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: ten
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: eleven
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: twelve
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: thirteen
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: fourteen
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: fifteen
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

- name: sixteen
  dependencies:
    - host
  env:
    FOO: ${runtime.tasks.host.outputs.log}
  healthCheck:
    command: [sleep, "5"]

```

### Your environment

`garden version`
0.11.13

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
