### ISSUE TITLE
helm tasks ignores set timeouts

### ISSUE THREAD

**Issue by lucas-sonnabend** [garden-io/garden#1837]
### Current Behavior

When I set a timeout (either 5s or 600s) on the helm module level or the task level, and run a helm task, it times out roughly after 5 minutes 

### Expected behavior

The timeout should be respected

### Reproducible example
change the vote/garden.yml in the vote-helm example and run it as `garden run task blabla`
```
kind: Module
description: Helm chart for the voting UI
type: helm
name: vote
serviceResource:
  kind: Deployment
  containerModule: vote-image
dependencies:
  - api
values:
  image:
    repository: ${modules.vote-image.outputs.deployment-image-name}
    tag: ${modules.vote-image.version}
  ingress:
    enabled: true
    paths: [/]
    hosts: [vote-helm.local.app.garden]
tests:
  - name: integ
    args: [npm, run, test:integ]
    timeout: 60
    dependencies:
      - api
tasks:
  - name: blabla
    args: ["sleep", "360"]
    timeout: 5
```

### Workaround

No idea, actually

### Suggested solution(s)

properly wire through the timeouts.

### Your environment

`garden version`
0.11.14
