### ISSUE TITLE
[FEATURE]: Native cache-from support

### ISSUE THREAD

**Issue by elliott-davis** [garden-io/garden#1874]
### Background / Motivation

Our docker images are "chonky". They take around 10 minutes to build if we're not using cache. When we're iterating on garden and rebuilding we get to take advantage of the basic docker caching, which is nice, until we have to stop garden. It would be nice to be able to specify a cache-from image to initially build from so when we're doing an initial build it doesn't take quite so long.

### What should the user be able to do?

A user should be able to specify a cache image for a module to build from: Ex:
```
kind: Module
type: container
name: php
description: PHP Monolith
build:
  targetImage: "${(local.env.PHP_DEBUG || 'false') == 'false' ? 'local' : 'debug'}"
  cacheFrom: "some-image:latest
...
```
### Why do they want to do this? What problem does it solve?

This eliminates long startup times due to extra long builds.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
