### ISSUE TITLE
Remote exec modules do not trigger rebuild of dependant modules in dev mode

### ISSUE THREAD

**Issue by elepedus** [garden-io/garden#1876]
### Current Behavior

I've got 2 exec (remote, linked) modules that generate jar files, a container module that copies them into an image, and a helm module which uses that image. Changing the Java sources in dev mode triggers a rebuild of the jar files, but the container isn't rebuilt, and the helm release remains unchanged.

### Expected behavior

Modifying the local code of a linked remote module should trigger dependants in the same way it would if the modules were local.

### Reproducible example
This is my config file:

```yaml 
kind: Project
name: auth
environments:
  - name: local
providers:
  - name: local-kubernetes
    environments: ['local']
  - name: maven-container
    environments: ['local']
dotIgnoreFiles: [.gardenIgnore]
---
kind: Module
name: psn-idp-jar
type: exec
build:
  command:
    - mvn
    - package
include:
  - src/**/*
  - pom.xml
repositoryUrl: git@gitlab.com:my-org/idp-auth-psn-provider.git#develop
---
kind: Module
name: xbl-idp-jar
type: exec
build:
  command:
    - mvn
    - package
include:
  - src/**/*
  - pom.xml
repositoryUrl: git@gitlab.com:my-org/idp-auth-xbl-provider.git#develop
---
kind: Module
type: container
name: custom-kc
build:
  dependencies:
    - name: xbl-idp-jar
      copy:
        - source: target/*
          target: target
    - name: psn-idp-jar
      copy:
        - source: target/*
          target: target
---
kind: Module
type: kubernetes
name: local-com-tls-secret
manifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: local-com-tls
    data:
      tls.crt: "${var.tls_crt}" # set this in a garden.env gitignored file, should be base64 encoded
      tls.key: "${var.tls_key}" # set this in a garden.env gitignored file, should be base64 encoded
    type: kubernetes.io/tls
---
kind: Module
description: Keycloak Auth service
type: helm
name: keycloak
chart: codecentric/keycloak
build:
  dependencies:
    - custom-kc
values:
  keycloak:
    image:
      repository: custom-kc
      tag: ${modules.custom-kc.version}
    persistence:
      dbPassword: ${var.dbPassword} # set this in a garden.env gitignored file
valueFiles:
  - values.yaml
timeout: 180
---
```
And this is my Dockerfile
```dockerfile
FROM jboss/keycloak:10.0.0
COPY target/idp-auth-xbl-provider.jar /opt/jboss/keycloak/standalone/deployments
COPY target/idp-auth-psn-provider.jar /opt/jboss/keycloak/standalone/deployments
COPY target/classes/theme-resources/base/admin/partials/* /opt/jboss/keycloak/themes/base/admin/resources/partials/
```

After linking the modules, running `garden dev` and modifying the sources triggers the exec modules, but not the dependant container module or its dependant helm module.

### Workaround

I merged the modules into a monorepo.

### Your environment
`garden version`
0.11.14

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
