### ISSUE TITLE
[FEATURE]: Allow builds to depend on services.

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#1919]
### Background / Motivation

I have an `exec` module that uses Maven to build a library which I then want to deploy to a 'private' Maven repository. I need to ensure that this repo service is up and running (i.e deployed) before building the `exec` module, as it'll otherwise fail. Currently, we can only specify build dependencies for `exec` modules, meaning there's no straight-forward way to accomplish this. 

### What should the user be able to do?

IMO, users should be able to specify build dependencies on services, to accommodate cases like these. One can theoretically work around this issue using `tasks`, but it's hacky. 

### Why do they want to do this? What problem does it solve?

In accommodating certain edge-cases (especially when dealing with 'legacy'/'non-cloud-native' technologies) the `exec` module is often the simplest way to build code without having to somehow fit it inside a container. Larger systems are bound to have one or more 'non-application' services that need to be up and running before the `exec` module in question can be built/fetch its requirements. 

### Suggested Implementation(s)

The following should be possible:

```
kind: Module
type: container
image: <some-service>
name: repository
service:
  - name: repository-service
---
kind: Module
type: exec
name: library
build:
  - command: [echo, "foo"]
     dependencies:
       - name: repository-service
``` 

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

Though I think it's quite specific, it does enable a number of integrations that would be painful to implement right now.
