### ISSUE TITLE
Workflows don't respect different environment invocations

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#1924]
### Reproducible example

`git clone https://github.com/garden-io/example-reference-framework`
`garden deploy --env=potsdam <- this should deploy all services`
`garden run workflow customer-preview-env` <- this should walk through each environment and run deploy (with the command in step 2 being the second command executed in the workflow).
The workflow in question:
```
---
kind: Workflow
name: customer-preview-env
steps:
  - name: berlin-deploy
    description: deploys the Berlin environment
    command: [deploy, --env=berlin]
  - name: frankfurt-deploy
    description: deploys the Frankfurt environment
    command: [deploy, --env=frankfurt]
  - name: potsdam-deploy
    description: deploys the Potsdam environment
    command: [deploy, --env=potsdam]
```        
Instead this step of the workflow produces:
```
Running workflow customer-preview-env 🏃‍♂️
Running step 1/3 — deploys the Berlin environment
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
   Deploy 🚀
   ✔ providers                 → Getting status... → Cached
      ℹ Run with --force-refresh to force a refresh of provider statuses.
   ℹ Service service-a is disabled
   ✔ service-b                 → Getting build status for v-08df681141... → Done (took 0 sec)
   ✔ service-c                 → Getting build status for v-cda0400114... → Done (took 0 sec)
   ✔ service-b                 → Deploying version v-08df681141... → Already deployed
   ✔ service-c                 → Deploying version v-cda0400114... → Already deployed
   Done! ✔️
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Step 1/3 completed in 1.88 Sec
Running step 2/3 — deploys the Frankfurt environment
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
   Deploy 🚀
   ℹ Service service-a is disabled
   Done! ✔️
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Step 2/3 completed in 0.09 Sec
Running step 3/3 — deploys the Potsdam environment
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
   Deploy 🚀
   ℹ Service service-a is disabled
   Done! ✔️
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Step 3/3 completed in 0.08 Sec
Workflow customer-preview-env completed successfully. Total time elapsed: 2.08 Sec.
```
Step 1 is correct, step 2 and 3 aren’t. service-a shouldn’t be disabled in both cases, and if you run their individual commands, they work as expected.
I suspect the following is happening:
Each environment has a varfile specified with the services that should be disabled:
```
# set to `true` to DISABLE the service!
service-a=true
service-b=false
service-c=false
```
The file above disables service a. This values are referenced in the modules like so:
```
kind: Module
type: container
name: service-a
disabled: ${var.service-a}
image: nginxdemos/hello
services:
  - name: service-a
```
What I think is happening here, is that Garden executes the first step of the workflow, but then doesn’t read the values from the var file in the second step. Maybe this is an issue with the variable hierarchy, but I would assume each step in the workflow is  separate invocation of Garden, or the variables should at least be reset? Especially since I’m **explicitly** specifying an environment.

I tried splitting the steps up into multiple separate workflows:
```
ind: Workflow
name: customer-preview-env-berlin
steps:
  - name: berlin-deploy
    description: deploys the Berlin environment
    command: [deploy, --env=berlin]
---
kind: Workflow
name: customer-preview-env-frankfurt
steps:
  - name: frankfurt-deploy
    description: deploys the Frankfurt environment
    command: [deploy, --env=frankfurt]
---
kind: Workflow
name: customer-preview-env-potsdam
steps:
  - name: potsdam-deploy
    description: deploys the Potsdam environment
    command: [deploy, --env=potsdam]
```
But even when invoking them specifically, it appears the `--env=` flag of the step's command is not respected. For example, running `garden run workflow customer-preview-env-frankfurt` produces:
```
Running workflow customer-preview-env-frankfurt 🏃‍♂️

Running step 1/1 — deploys the Frankfurt environment
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
   Deploy 🚀

   ✔ providers                 → Getting status... → Cached
      ℹ Run with --force-refresh to force a refresh of provider statuses.
   ℹ Service service-a is disabled
   ✔ service-c                 → Getting build status for v-cda0400114... → Done (took 0 sec)
   ✔ service-b                 → Getting build status for v-08df681141... → Done (took 0 sec)
   ✔ service-c                 → Deploying version v-cda0400114... → Already deployed
   ✔ service-b                 → Deploying version v-08df681141... → Already deployed

   Done! ✔️
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Step 1/1 completed in 1.67 Sec
```
Though when I invoke the step's command (`garden deploy --env=frankfurt`) I get:
```
Deploy 🚀

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
ℹ Service service-b is disabled
✔ service-a                 → Getting build status for v-be2753dd99... → Done (took 0 sec)
✔ service-c                 → Getting build status for v-cda0400114... → Done (took 0 sec)
✔ service-c                 → Deploying version v-cda0400114... → Already deployed
✔ service-a                 → Deploying version v-be2753dd99... → Already deployed

Done! ✔️
```
(Which is the result I'm expecting). 

### Current Behavior

Even though I'm specifying a different environment in each step, Garden doesn't appear to be reading the varfile associated with that environment.

### Expected behavior

Whenever Garden is invoked in a workflow, it should initialize the environment properly.

### Your environment

`garden version`
0.12.0

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

`docker version`
Not using.
