### ISSUE TITLE
[FEATURE]: Conditionally disable steps in workflows

### ISSUE THREAD

**Issue by noizwaves** [garden-io/garden#1927]
### Background / Motivation

In our usage of Garden, we need to run a task after deploying services. Before Garden 0.12, we would invoke `garden` CLI twice in a `deploy.sh` script. With 0.12, we upgraded to use Garden Workflows 🙌.

Now, we have a need to run this task conditionally. For my specific use case, it is conditional on whether a user has selected to deploy a specific application.

### What should the user be able to do?

I could see it being useful for steps in Garden workflows to be conditionally disabled.

### Why do they want to do this? What problem does it solve?

We've worked around this by making the task name conditional. In the case where the task should not be run, we instead run a `noop` task:

```
name: deploy
kind: Workflow
steps:
  - name: deploy-services
    command: [deploy]
  - name: initialize-database
    command: [run, task, "${local.env.APP_SELECTED == 'true' ? 'db-init' : 'noop-task'}"]
```

### Suggested Implementation(s)

I imagine a new key in the step definition called `disabled` (to match the existing `disabled` option on other modules/services). It would look something like this:

```
name: deploy
kind: Workflow
description: deploy all applications
steps:
  - name: deploy-services
    command: [deploy]
  - name: initialize-database
    command: [run, task, db-init]
    disabled: ${var.environment == 'production'}
```

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
