### ISSUE TITLE
[FEATURE]: Resolve & validate workflow configs in more commands.

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#1931]
## Feature Request

For all commands that resolve module configs, also resolve & validate workflow configs.

Reported by @baspetersdotjpeg.

### Background / Motivation

Currently, workflow configs are only being validated on-demand, i.e. when `garden.getWorkflowConfigs()` is called. This is only done by the `run workflow` and `get config` commands.

For example, adding this invalid workflow config to a project:
```yaml
kind: Workflow
name: invalid
steps:
  - command: [test]
triggers: # <--- should be an array, not a map
  events: [push, pull-request]
  environment: test-environment
```
and running `garden deploy` won't result in any errors. Running `garden run workflow invalid` or `garden get config` will throw a validation error.

### What should the user be able to do?

When a user runs the `build`, `deploy`, `test` or `dev` commands (and, more generally, any command that would throw an error when one or more module configs is invalid), an error message should be thrown if one or more workflow configs in the project is invalid.

### Why do they want to do this? What problem does it solve?

Getting this feedback earlier is convenient for the user.

### Suggested Implementation(s)

Add `await garden.getWorkflowConfigs()` calls to the relevant commands.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
