### ISSUE TITLE
Test artifacts not copying

### ISSUE THREAD

**Issue by jfri3d** [garden-io/garden#1946]
## Bug
Test artifacts are **not** being copied locally.

### Current Behavior
Test is successfully run without extracting the tarball or copying to local artifact directory. Looks like it fails silently before reaching the [runner](https://github.com/garden-io/garden/blob/a783adc02a31cd9dac89f945aa3115033f7ed488/garden-service/src/plugins/kubernetes/run.ts#L303).

### Expected behavior
Test artifacts **are** copied locally!

### Reproducible example
A full working example can be created (if necessary) but it is easier to just attach some relevant parts of my stack.

1) _abbreviated_ **garden.yaml**
```
kind: Module
type: container
name: functional-testing
tests:
  - name: spawner
    command: ["/bin/sh","-c"]
    args: ["coverage run ..."]
    env: {
      COVERAGE_FILE: "/app/.coverage"
    }
    artifacts:
      - source: /app/.coverage
        target: ./coverage/spawner
```

2) triggering tests
```
$ garden test functional-testing -n spawner --log-level 5 --force

...
...

ℹ Remaining tasks 1
ℹ tasks                     → Processing task test.functional-testing.spawner.ff584ad0-c693-11ea-8923-51392d05c2ab
Currently in progress [test.functional-testing.spawner.ff584ad0-c693-11ea-8923-51392d05c2ab]
ℹ functional-testing        → Running spawner tests
   Getting 'testModule' handler for module 'functional-testing' (type 'container')
Resolving provider kubernetes
   Calling testModule handler for module functional-testing
   Starting Pod test-functional-testing-spawner-41b08d with command 'sh -c mkfifo /tmp/output && cat /tmp/output && sleep 86400'
   Spawning '/Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a/kubectl --context=XXX namespace=joshfri run test-functional-testing-spawner-41b08d --image=XXX --restart=Never -i --overrides {"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}},"spec":{"containers":[{"name":"main","image":"XXX","env":[{"name":"GARDEN_VERSION","value":"v-bb8fb4b250"},{"name":"GARDEN_DEPENDENCIES","value":"[]"},{"name":"COVERAGE_FILE","value":"/app/.coverage"}],"volumeMounts":[],"command":["sh","-c","mkfifo /tmp/output && cat /tmp/output && sleep 86400"]}],"imagePullSecrets":[],"volumes":[]}} --quiet' in /Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a
   Execing '/Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a/kubectl --context=XXX --namespace=joshfri exec -i test-functional-testing-spawner-41b08d -c main -- sh -c tar --help' in /Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a
   Execing '/Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a/kubectl --context=XXX --namespace=joshfri exec -i test-functional-testing-spawner-41b08d -c main -- sh -c exec >/tmp/output; "/bin/sh" "-c" "coverage run ..."' in /Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a
   Execing '/Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a/kubectl --context=XXX --namespace=joshfri exec -i test-functional-testing-spawner-41b08d -c main -- sh -c cd / && touch .DS_Store && tar -c -f - $(ls app/.coverage 2>/dev/null) .DS_Store' in /Users/jfriedman/.garden/tools/kubectl/b57d7033ebdf2a5a
   tar: got file app/.coverage
   tar: got file .DS_Store
✔ functional-testing        → Running spawner tests → Success (took 22.4 sec)
✔ tasks                     → Completed task test.functional-testing.spawner.ff584ad0-c693-11ea-8923-51392d05c2ab (took 22.377 sec)
ℹ Remaining tasks 0
ℹ Remaining tasks 0

```

### Workaround
Using PVCs.

### Your environment

```
$ garden version
0.12.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

```

**Comment by eysi09** [comment]
Hi @jfri3d 

This would happen if the source is actually missing, i.e. `-source: /app/some-file-that-doesnt-exist`.

Is `.coverage` a file or a dir? If it's a file, should it be `.coverage.py` (sorry, not super familiar with Python)? If a dir could you try `- source: /app/.coverage/*`?

**Comment by jfri3d** [comment]
Thanks for the reply @eysi09 

Hmmm a bit confused. The source is the result of running distributed tests with coverage (an intermediate result) and tar does find it - `tar: got file app/.coverage`. Is there some voodoo surrounding files needing an extension in Garden?

The file does exist. Exec’d into the running container to verify. Also now have the same code working with a PVC.

**Comment by eysi09** [comment]
Ok understood. If there's a file called `.coverage` there it should of course work. Just wanted to verify that this wasn't an issue with the path or that the file wasn't there. 

I haven't been able to reproduce this on my end. I tried this with a very similar setup but just not using `coverage`. Any chance you could whip up a simple standalone repro for me? That would make it much easier to debug this.

**Comment by jfri3d** [comment]
Looks like hidden files are not handled...

1) Created the following simplistic modules for testing (`garden.yaml`)

```yaml
kind: Module
type: container
name: a
description: tests basic functionality - SUCCESS
image: alpine:latest
tests:
  - name: int
    command: ["/bin/sh","-c"]
    args: ['touch /tmp/a.blah']
    artifacts:
      - source: /tmp/a.blah
        target: out
---
kind: Module
type: container
name: b
description: tests target directory - SUCCESS
image: alpine:latest
tests:
  - name: int
    command: ["/bin/sh","-c"]
    args: ['touch /tmp/b.blah']
    artifacts:
      - source: /tmp/b.blah
        target: ./out
---
kind: Module
type: container
name: c
description: tests source file without extension - SUCCESS
image: alpine:latest
tests:
  - name: int
    command: ["/bin/sh","-c"]
    args: ['touch /tmp/c']
    artifacts:
      - source: /tmp/c
        target: ./out
---
kind: Module
type: container
name: d
description: tests hidden source file without extension - FAILED
image: alpine:latest
tests:
  - name: int
    command: ["/bin/sh","-c"]
    args: ['touch /tmp/.d']
    artifacts:
      - source: /tmp/.d
        target: ./out
---
kind: Module
type: container
name: e
description: tests hidden source file with extension - FAILED
image: alpine:latest
tests:
  - name: int
    command: ["/bin/sh","-c"]
    args: ['touch /tmp/.e.blah']
    artifacts:
      - source: /tmp/.e.blah
        target: ./out
---
kind: Module
type: container
name: f
description: tests hidden source file with extension - FAILED
image: alpine:latest
tests:
  - name: int
    command: ["/bin/sh","-c"]
    args: ['touch /tmp/.f.blah']
    artifacts:
      - source: /tmp/*.blah
        target: ./out
```

2) run tests

```bash
$ garden test a,b,c,d,e,f

Running tests 🌡️

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
✔ d                         → Getting build status for v-1da07140ab... → Done (took 0 sec)
✔ e                         → Getting build status for v-5c9c48a8d1... → Done (took 0 sec)
✔ f                         → Getting build status for v-578356745c... → Done (took 0 sec)
✔ b                         → Getting build status for v-e4e46197cd... → Done (took 0 sec)
✔ c                         → Getting build status for v-0178f12d95... → Done (took 0 sec)
✔ a                         → Getting build status for v-f491ceed27... → Done (took 0.1 sec)
✔ f                         → Running int tests → Success (took 6.7 sec)
✔ e                         → Running int tests → Success (took 6.7 sec)
✔ d                         → Running int tests → Success (took 8 sec)
✔ b                         → Running int tests → Success (took 6.5 sec)
   → Artifact: .garden/artifacts/out/b.blah
✔ c                         → Running int tests → Success (took 7.6 sec)
   → Artifact: .garden/artifacts/out/c
✔ a                         → Running int tests → Success (took 7.7 sec)
   → Artifact: .garden/artifacts/out/a.blah
```

3) missing artifacts :sad-pepe:

```bash
$ ll .garden/artifacts/out

total 0
drwxr-xr-x   5 jfriedman  staff   160B Jul 16 11:27 .
drwxr-xr-x  17 jfriedman  staff   544B Jul 16 11:35 ..
-rw-r--r--   1 jfriedman  staff     0B Jul 16 11:35 a.blah
-rw-r--r--   1 jfriedman  staff     0B Jul 16 11:35 b.blah
-rw-r--r--   1 jfriedman  staff     0B Jul 16 11:35 c
```
