### ISSUE TITLE
[FEATURE]: Allow mounting GE secrets to files.

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#1952]
### Background / Motivation

When using GE, I'd like to be able to mount a secret to file. This makes storing credentials files in GE easier and more helpful.

### What should the user be able to do?

It would be super useful to be able to specify which secret to mount to which file in the `exec` Provider.
Something like:
```yaml
providers:
  - name: kubernetes
     ...
  - name: exec
    environments: [staging]
    mountFiles:
      - path: "./gcloudAuth.json"
        value: ${secrets.gcloud-dev-json}
    initScript: "/bin/sh ./loginGCloudServiceAccount.sh"
```

### Why do they want to do this? What problem does it solve?

Makes it easier to configure my GE projects.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
