### ISSUE TITLE
Unable to run docker command: Cannot read property 'spawnAndWait' of undefined

### ISSUE THREAD

**Issue by padamson-r7** [garden-io/garden#2002]
### Current Behavior
In the following example there are 2 identical modules, except one is `container` and the other is `maven-container`.
The `this-works` container module deploys successfully and the `this-fails` maven-container module fails with the following error:

`Unable to run docker command: Cannot read property 'spawnAndWait' of undefined`

### Expected behavior

In 11.3 the maven-container variety worked.
When `useDefaultDockerfile` was set to false it would correctly fall back to pulling the container image.

### Reproducible example

```
kind: Project
name: temp
environments:
- name: local
  providers:
  - name: local-kubernetes
    setupIngressController: false
  - name: maven-container

---
  kind: Module
  description: Fallback to image pull using maven-container module
  type: maven-container
  name: this-fails
  #repositoryUrl: omitted to force fall back to image pull when combined with useDefaultDockerfile: false

  #MAVEN
  jarPath: blah/app.jar # required but not used in this example

  # DOCKER
  image: crccheck/hello-world:latest
  useDefaultDockerfile: false

  services:
    - name: this-fails

---

  kind: Module
  description: Fallback to image pull using regular container module
  type: container
  name: this-works
  image: crccheck/hello-world:latest

  services:
    - name: this-works

```

```
$ garden deploy
Deploy 🚀

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
✔ this-works                → Getting build status for v-f5f609f805... → Done (took 0 sec)
 this-fails                → Getting build status for v-f30dfbf54d...

Failed building this-fails. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to run docker command: Cannot read property 'spawnAndWait' of undefined
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✔ this-works                → Deploying version v-f5f609f805... → Done (took 3.4 sec)
   ℹ this-works                → Resources ready
1 deploy task(s) failed!

See error.log for detailed error message

$ kc get pods
NAME                                      READY   STATUS    RESTARTS   AGE
this-works-v-f5f609f805-88b6544c7-4bvqg   1/1     Running   0          9s
```

### Your environment

`garden version`

`kubectl version`

`docker version`
