### ISSUE TITLE
[QUESTION] copy artifacts from containers?

### ISSUE THREAD

**Issue by ThisGuyCodes** [garden-io/garden#2007]
I'm attempting to use the "copy from a build dependency" feature, and I'm unclear how this interacts with container modules?

What I want is to copy an artifact (specifically a .jar file) out of the build container and make it available to another container module. However the copy command is requiring a relative path, which confuses me.

Is there a way to do the copy I'm attempting? Or am I misunderstanding this feature.

**Comment by eysi09** [comment]
Hi @ThisGuyCodes! 

Apologies for the late reply. For artifacts, the `artifacts.source` path must be an absolute path in the container you're copying from. The `artifacts.target` path is relative to the project level `.garden/artifacts` dir. 

For example, if the `.jar` gets created in the build dir of your container, it could look something like this:

```yaml
kind: Module
name: my-java-container
# ...
tasks:
  - name: build-jar
    command: [mvn, build] # or whatever the command is
    artifacts:
      - source: /app/build/**
        target: "my-java-container/build"
```

In this case, all the contents of the `/app/build` dir in the running container get copied to `.garden/artifacts/my-java-container/build`. 

Unfortunately there's currently no Garden native way to copy the artifact to the source dir. What you can do is have a local exec module has a task that depends on the above task and does they copying.

Something like:

```yaml
kind: Module
name: copy
type: exec
local: true
tasks:
  - name: copy-jar-to-src
    command: [./copy-jar.sh]
    dependencies:
      - build-jar
```

Now if you run `garden run task copy-jar-to-src`, it'll first build the jar in `my-java-container` and then copy it as specified by the `copy-jar` script. Note that the script will need account for the possibility of there being several files in the `.garden/articfacts/my-java-container/build` dir, due to previous task runs.

Here's also a section from our docs on task artifacts: https://docs.garden.io/using-garden/tasks#task-artifacts

Here's an example of such a script from our own project:

```bash
migrations_source_path=".garden/artifacts/api/migrations"
migrations_dest_path="api/src/migrations"
latest_migration=`ls -t $migrations_source_path|head -n 1`
cp $migrations_source_path/$latest_migration $migrations_dest_path
```

Note also that unfortunately it's not possible to do this as a part of the build, since builds can't have a dependency on tasks, and it's quite tricky to support on our end. 

So currently, generating the `.jar` would need to be done "manually" (via `garden run task") and before running `garden build` or `garden deploy`.
