### ISSUE TITLE
[FEATURE]: Terraform workspace support

### ISSUE THREAD

**Issue by Pacobart** [garden-io/garden#2024]
### Background / Motivation

We use terraform workspaces to manage state across multiple deployment environments. Currently, this requires running a custom `exec` module with the commands to create/select workspaces.
```
kind: Module
type: exec
name: tf-tasks
local: true
exclude: ['*']
tasks:
  - name: tf-workspace-init
    command: ["terraform workspace new ${var.deployEnv} || terraform workspace select ${var.deployEnv}"]
```

### What should the user be able to do?

In the terraform module allow setting the workspace name statically or via variable.

### Why do they want to do this? What problem does it solve?

When using the `exec` module the commands don't always run as intended causing us to manually run commands prior to using `garden` commands. This feature also aligns with terraform being a first class citizen in garden.

### Suggested Implementation(s)

```
kind: Module
type: terraform
name: tf-infra
autoApply: true
allowDestroy: true
workspaceName: ${var.deployEnv}
include: ['*']
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by elijah-roberts** [comment]
@Pacobart  I also ran into this issue and resolved it this way:

```
---
kind: Module
type: exec
name: tf-tasks
local: true
exclude: ['*']
tasks:
  - name: tf-workspace-set
    command: ["echo ${var.deployEnv} > .terraform/environment"]
---
kind: Module
type: terraform
name: tf-infra
autoApply: true
allowDestroy: true
include: ['*']
dependencies:
  - tf-workspace-set
```

Based on the recommendation here: https://support.hashicorp.com/hc/en-us/articles/360043550953-Selecting-a-workspace-when-running-Terraform-in-automation
Basically this works because of the order of operations for garden and terraform....
garden does the initial init which for the s3 backend, defaults to default workspace.
The dependency for my terraform step, ensures that I update .terraform/environment after the init (so I do not run into trouble using a workspace that had not been defined yet), but before my plan/apply so that my state is actually stores in S3 env/${var.deployEnv}...

This satisfies my goal, of having a user install just garden, pull down a repo, and run garden deploy... with out having to manage, kubectl, terraform, etc dependencies...

this all said... first class support for workspaces would be good, and is still a valid feature... and you may end up implementing it in a similar way by managing the .terrform/environment file directly...
