### ISSUE TITLE
BUG: Unable to run garden tools command inside exec modules

### ISSUE THREAD

**Issue by elijah-roberts** [garden-io/garden#2032]
### Current Behavior
Here is what I am trying to do:

```
---
kind: Module
type: exec
name: tf-tasks
local: true
exclude: ['*']
tasks:
  - name: tf-workspace-init
    command: ["garden tools terraform-0-12-26 -- workspace new ${var.deployEnv} || garden tools terraform-0-12-26 -- workspace select ${var.deployEnv}"]
```

However I get the following error:

```
Failed running task tf-workspace-init in module tf-tasks. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
internal/modules/cjs/loader.js:983
  throw err;
  ^
Error: Cannot find module '/Users/ejr/code/scratch/garden/demo-web-py/build/terraform/tools'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

moving the exec module into my root garden.yml causes a similar error...

### Expected behavior

I should be able to run the garden tools commands inside of an exec module command, to run out of band tasks for tools such as terraform, kubectl, etc... 

### Reproducible example

Any task running garden tools command

```
---
kind: Module
type: exec
name: tf-tasks
local: true
exclude: ['*']
tasks:
  - name: tf-workspace-init
    command: ["garden tools <tool> <args>"]
```

### Workaround

my specific use case was resolved by doing the following:

```
---
kind: Module
type: exec
name: tf-tasks
local: true
exclude: ['*']
tasks:
  - name: tf-workspace-set
    command: ["echo ${var.deployEnv} > .terraform/environment"]
```

and by passing the garden tools commands all together... 

### Suggested solution(s)

Not sure... 

### Additional context

Slack conversation link: https://kubernetes.slack.com/archives/CKM7CP8P9/p1598982704073300

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:**  EKS

* **Garden Version** 0.12.3
