### ISSUE TITLE
local volume mount not working for tests

### ISSUE THREAD

**Issue by lucas-sonnabend** [garden-io/garden#2092]
### Current Behaviour

I've added volume mounts to a test of a container module to module directories and files, but I never saw the content inside the container running the test.

Background: I want to run (conf)tests on certain files for a lot of modules. So I want to have a base image to run the tests, and then for each module mount some files and run the test on those.

### Expected behaviour

See the content of mounted directories/files inside the container.

### Reproducible example

extract of garden.yaml:
```
---
kind: Module
name: notifications-policy-checker
type: container
image: python:3.8-slim
tests:
  - name: local-config-test
    command: ["sleep", "10000"]
    volumes:
      - name: "local-env"
        containerPath: "/config/local.env"
        hostPath: "local.env"
      - name: "helm-values"
        containerPath: "/config/helm"
        hostPath: "helm"
include:
  - helm/values.yaml
  - local.env
```
I ran the tests, waited for the pod to be up and exec-ed into it. `config/local.env` was created as an empty directory, and `config/helm` was empty, too.

The hostPath values are relative to the root of the module, and the exist under `.garden/build/notifications-policy-checker/`. I also tried with `${local.env.PWD}/local.env` as the host path (because relative path apparently don't work for docker volume mounts, but that also didn't work.

### Workaround

Because the tests I want to run are conftests we can use the conftest module instead. But that needs an exec module to get the inputs in the right format, and that exec module needs extra dependencies (python and certain modules installed). So my plan was to have both the initial transform and the conftest inside a docker container, where I can control the dependencies.

### Suggested solution(s)

No idea unfortunately

### Your environment

macOS:
```
$ sw_vers -productVersion
10.15.6
```
kubernetes on EKS (although that shouldn't be relevant here)

```
$ garden version
0.12.5
```

**Comment by eysi09** [comment]
Hi @lucas-sonnabend! 

The `hostPath` field refers to the path on the actual VM that the node runs on, not a path on your local file system. So you can't really populate these volumes like this. See also the official [K8s docs](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath). 

One solution to your problem would be to use your own docker image that extends the python image you're using and add these files via the Docker COPY/ADD directives.

**Comment by ManAnRuck** [comment]
is it possible to get somehow the current directory path via variable, script or somehow to use the current path in templates?
this would help to mount an absolute path

**Comment by eysi09** [comment]
You mean via template strings? Something like `dir: ${path.cwd}`?

**Comment by ManAnRuck** [comment]
Yes, exactly! 😃
@stefreak  gave me a hint about `${local.projectPath}` in another topic and that solved it for me.

```yaml
- volumes:
  - name: some-path
    hostPath:
      path: $local.projectPath}/sources/
      type: Directory
```
