### ISSUE TITLE
Providing namespace and environment argument to plugin commands, with defaultNamespace to null, fails

### ISSUE THREAD

**Issue by wyrie** [garden-io/garden#2093]
### Current Behavior

If your environment has it's defaultNamespace value set to null, plugin commands will fail even when provided with the --env argument

```
garden plugins kubernetes uninstall-garden-services --env=test.remote
Project no-project does not specify environment remote
```

```
garden tools kubectl --env=test.local -- api-resources --api-group="keda.k8s.io" -o name
Project no-project does not specify environment local
```

### Expected behavior

When providing a valid namespace and environment value with the --env argument the commands should pass validation and execute.

### Reproducible example

garden.yaml
```
---
kind: Project
name: my-project
dotIgnoreFiles: [.gardenignore]
environments:
  - name: local
    defaultNamespace: null
  - name: remote
    defaultNamespace: null
...
```
`garden tools kubectl --env=test.local -- get po`

### Workaround

Temporarily add a value to defaultNamespace and rerun command without the namespace
`garden tools kubectl --env=local -- get po`

### Additional context

See this community Slack link:  https://kubernetes.slack.com/archives/CKM7CP8P9/p1601541582031300

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS and docker-desktop 

`garden version`
0.12.6
