### ISSUE TITLE
[FEATURE]: namespace labels (for istio)

### ISSUE THREAD

**Issue by to266** [garden-io/garden#2096]
### Background / Motivation

Deploying garden and istio

### What should the user be able to do?

Add labels to the garden-created `app-namespace`

### Why do they want to do this? What problem does it solve?

Currently have to rely on a local exec task that essentially runs
```bash
sleep 5 && kubectl label namespace ${providers.kubernetes.outputs.app-namespace} istio-injection=enabled --overwrite
```

The sleep is required to give garden itself time to create the namespace, in case the task happens to run before the namespace creation

### Suggested Implementation(s)

in the root `garden.yml` I would expect either the kubernetes provider have `namespaceLabels` key (which I guess supports everything) or a more custom `enableIstioInjection: true`.

### How important is this feature for you/your team?

Somewhere between these two (depends on how reliable the `sleep 5` part is):
 - 🌵 Not having this feature makes using Garden painful
 - 🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Thanks for the future request!

Exposing `namespaceLabels` seems reasonable. In the meantime, it's also possible to workaround this by using an `exec` provider that has a dependency on the `kubernetes` provider and runs an init script. Like so:

```yaml
  - name: kubernetes
    environments: [ci]
    # ...
  - name: exec
    environments: [ci]
    dependencies: [kubernetes]
    initScript: >
      kubectl label namespace ${providers.kubernetes.outputs.app-namespace} istio-injection=enabled --overwrite
```
