### ISSUE TITLE
cert-manager integration ignores secretRef's namespace

### ISSUE THREAD

**Issue by LeoDupont** [garden-io/garden#2098]
### Current Behavior

I have this Garden project, leveraging the [cert-manager integration](https://docs.garden.io/advanced/cert-manager-integration):

```yaml
kind: Project
name: my-cloud

defaultEnvironment: dev
environments:
  - name: dev
    defaultNamespace: dev

providers:
  - name: kubernetes
    environments: [dev]
    context: gke_redacted_context
    buildMode: cluster-docker
    setupIngressController: false # using Istio
    certManager:
      install: false # installed manually
      email: my@redacted-email.com
      issuer: acme
      acmeChallengeType: HTTP-01
      acmeServer: letsencrypt-staging
    tlsCertificates:
      - name: dev-cert-01
        managedBy: cert-manager
        hostnames:
          - my.redacted.domain.com
        secretRef:
          name: dev-tls
          namespace: istio-system # <= this is the ignored bit
```

> (Not related to Garden, but for the records and for other Istio users, I'd like to mention the fact that the acme-solver ingress created didn't play well with my Istio gateway, but I managed to work around that by adding a route in my Istio VirtualService for `/.well-known` to the acme-solver service... this isn't good for automatic certificate renewal, but that's another topic).

The bug is that the `dev-tls` secret is not created in the `istio-system` namespace, but rather in the Garden project's namespace, that is `my-cloud-dev`.

Incidentally, the HTTPS traffic was not working at all and it took me a while to realize the secret was simply not in the right Kubernetes namespace. 

### Expected behavior

I was expecting the `dev-tls` secret to be created in the `istio-system` namespace, and not the current project's namespace.

### Workaround

After [exporting the secret](https://www.revsys.com/tidbits/copying-kubernetes-secrets-between-namespaces/) from `my-cloud-dev` to `istio-system`, the HTTPS traffic worked out. 

But that's not great for automatic certificates renewal.

### Suggested solution(s)

It seems that the `secretRef.namespace` property is ignored somehow. But I don't know in which situations.

### Your environment

* **OS:** Windows 10 Pro 2004
* **How I'm running Kubernetes:** GKE
* `garden version`: 0.12.6

Please tell me if I can provide more info.
