### ISSUE TITLE
Deployment of Kubernetes module with CRD manifest fails on first time

### ISSUE THREAD

**Issue by tvollstaedt** [garden-io/garden#2122]
## Bug

I'm using a Garden helm module (Traefik) which defines a bunch of CRD's. I'm also using another Garden Kubernetes module which deploys manifests with these CRD's. The kubernetes module has the helm module as dependency.

### Current Behavior

While the above setup works fine, the very first deployment (empty kubernetes environment) fails due to a Kubernetes 404 error (within the build phase). Subsequent Deployments are not failing.

### Expected behavior

First deployment succeeds without any error.

### Reproducible example

CRD's created by traefik helm chart need to be removed upfront and/or use a clean kubernetes cluster.

```yaml
kind: Project
name: example
providers:
  - name: local-kubernetes
    setupIngressController: null
    namespace: example
---
# Only required on bare metal environments, skip it if you are using an external load balancer
kind: Module
name: metallb
namespace: metallb
description: MetalLB provides a load balancer service to the cluster
type: helm
repo: https://charts.bitnami.com/bitnami
chart: metallb
values:
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 127.0.0.1/32
---
kind: Module
type: helm
description: Traefik Edge Router
name: api-gateway
chart: traefik
repo: https://containous.github.io/traefik-helm-chart
dependencies:
  - metallb
---
kind: Module
type: kubernetes
name: mw-strip-api-prefix
description: Strips the prefix path of api services
exclude: ["**/*"]
manifests:
  - apiVersion: traefik.containo.us/v1alpha1
    kind: Middleware
    metadata:
      name: mw-strip-api-prefix
    spec:
      stripPrefixRegex:
        regex: ["/api/[a-z0-9]+/"]
dependencies:
  - api-gateway
```

```bash
$ garden deploy
Deploy

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
✔ metallb                   → Building version v-95b526728f... → Done (took 3.1 sec)
✔ api-gateway               → Building version v-228cf86a52... → Done (took 1.8 sec)
✔ mw-strip-api-prefix       → Building version v-572187264f... → Done (took 0 sec)

Failed getting status for service 'mw-strip-api-prefix' (from module 'mw-strip-api-prefix'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
StatusCodeError from Kubernetes API - 404 - "404 page not found
"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✔ metallb                   → Deploying version v-95b526728f... → Done (took 19.1 sec)
   ℹ metallb                   → Resources ready
✔ api-gateway               → Deploying version v-228cf86a52... → Done (took 20.2 sec)
   ℹ api-gateway               → Resources ready
1 deploy task(s) failed!
```

### Workaround

Deploy twice.

### Suggested solution(s)

Dont treat the Kubernetes 404 response as an deployment error.

### Additional context

As even after `garden delete environment` and removing caches (`rm -rf .garden`) the error is not reproductible, I have the assumption that the CRD's are not cleaned / removed from the cluster, even after a `garden delete environment`. I'm not sure if this is expected behaviour (but it would probably be an issue with helm anyways).

### Your environment

* **OS:** Windows 10
* **How I'm running Kubernetes:** Docker Desktop on WSL2

`garden version`

0.12.9
