### ISSUE TITLE
Proper TLS and domain/hostname support 🔒

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#214]
## Ze problem

In order to properly support remote Kubernetes deployments, we have to implement
proper support for TLS, and improve our overall handling of hostnames and ingress.

### Hostnames

Currently, all services are automatically assigned a hostname. This is all well and
fine for local development, and we can keep that as the default behavior - if no
hostname is specified for an endpoint, we create a hostname using the configured
ingress hostname for the provider and the service name as a subdomain
(e.g. `my-service.my-project.local.app.garden` or `bla.foo.some-user.app.garden`).

However, this may not fit all use cases (plus it's rather verbose). Existing apps may
depend on working with particular hostnames, or demand that they all use the same
hostname but different paths.

Further, auto-generating hostnames can cause problems with SSL certificates if they're
manually configured. Users may have their own certs and they may not be wildcard certs.

So, we need to allow users to specify a particular hostname for each service. Plus,
the hostname may need to be different depending on the environment. We'll need to come
up with a clean way to specify variables differently based on the environment configuration.

### Certificates

For TLS to work reliably in different Kubernetes deployments, we should use standard K8s
primitives - namely, a certificate needs to be attached to each Ingress resource.
It may or may not be the same certificate, depending on what the hostname setup is.

This tends to be a rather tedious part of getting environments up and running. Managing
certificates is no fun, even though things like Let's Encrypt and ACME make it more
palatable.

At the minimum, we need to offer users some way to configure these certificates.
Better, however, would be to do a lot of the work automatically, at least in the cases where
developers aren't using custom domains.

Another problem is the difficulty in running secure ingress in localhost setups.
Generating certificates in a hosted platform is one thing, but generating certificates for
a localhost deployment can't be done via a standard Let's Encrypt/ACME flow unless the
user controls the domain and we allow for an array of different validation methods.

## So, what to do?

For sure we want to allow setting the hostname for each service, or at least the subdomain.
We could separate the issue into first allowing a custom subdomain, and do custom domains
as a separate feature. We'll need in either case to add some logic to make sure endpoints
don't conflict as well.

We can put a pin in automated local TLS for now, but perhaps later we can offer a service
to claim and generate `local.garden`/`local.app.garden` certificates.

For remote deployments we can start by allowing users to configure certificates but only
allow a single domain for all services. That simplifies the implementation somewhat.
We can also allow this for local TLS, so that users can configure a custom domain and
certificate.

So, to break it down, I suggest we implement the following (starting with 1 and 2):

### 1 - Configurable domain and subdomain

We remove the `hostname` key from endpoint configs and add `domain` and `subdomain`
keys instead:

```yaml
module:
  type: container
  services:
  - name: my-service
    command: [npm, start]
    ports:
    - name: http
      containerPort: 8080e
    endpoints:
      # (optional) defaults to first configured domain
    - domain: mydomain.com
      # (optional) defaults to service name
      # can also be set to null to use just the base domain
      subdomain: some-subdomain
      paths: [/foo]
      port: http
```

This is to clarify the difference between domain/subdomain/hostname (the hostname
being compiled from domain and subdomain), and to set the API for multiple domains.

### 2 - Change K8s ingress hostname to domains and add secrets config for TLS

I'd suggest doing multiple domains in a separate step since it adds some complexity,
but we don't want to change the configuration APIs multiple times.

One constraint to note is that certificates need to be wildcard certificates in
most cases, since this does not include a mechanism to auto-generate certificates.

We use standard K8s mechanics to store the TLS certs/keys, and just reference the
secrets in the config.

```yaml
project:
  name: my-project
  environments:
  - name: dev
    providers:
    - name: kubernetes
      ingressDomains:
      - name: mydomain.com
        tlsSecretRef:
          name: my-domain-tls
          namespace: kube-system
      - name: otherdomain.com
        tlsSecretRef:
          name: other-domain-tls
          namespace: kube-system
```

### 3 - Add support for ACME TLS (Let's Encrypt)

This is a lot of work to set up behind the scenes, but it would allow us to automatically
issue a certificate for each domain and subdomain. The API for users would be fairly
simple:

```yaml
project:
  name: my-project
  environments:
  - name: dev
    providers:
    - name: kubernetes
      ingressDomains:
      - name: mydomain.com
        acmeEmail: bob@mydomain.com
      - name: otherdomain.com
        acmeEmail: bob@mydomain.com
```

However, the implementation would be rather complex and I'm not sure we want to get into
all that. This would also not work for local deployments, whereas 2) can also be configured
for `local-kubernetes`.

Another complication is _renewals_. We'd need to automate that process as well, and that's
by nature difficult to implement effectively and securely. And lastly, there's the issue
of rate limits, which we'd need to consider when issuing a bunch of certs for multiple users
in a cluster.

Thoughts?
