### ISSUE TITLE
Port conflicts with headless services

### ISSUE THREAD

**Issue by justicel** [garden-io/garden#2176]
### Current Behavior

Using a helm chart that specifies a headless service seems to often result in port conflict errors. This does not seem to occur with services that don't have a headless service. Using the helm chart for rabbitmq for instance seems to introduce this error.

Error is below:

⏳  Processing...
Error: bind EADDRINUSE 127.0.0.1:4369
    at listenOnMasterHandle (net.js:1380:18)
    at rr (internal/cluster/child.js:132:12)
    at Worker.<anonymous> (internal/cluster/child.js:99:7)
    at process.onInternalMessage (internal/cluster/utils.js:47:8)
    at process.emit (events.js:327:22)
    at process.emit (/snapshot/project/tmp/pkg/cli/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

### Expected behavior

Expect rabbitmq to be able to start.

### Reproducible example

Example rabbitmq garden.yml:

```
  ---
  kind: Module
  description: Rabbitmq default stack
  type: helm
  name: rabbitmq
  repo: https://charts.bitnami.com/bitnami
  chart: rabbitmq
  version: "8.6.1"
  serviceResource:
    kind: StatefulSet
    name: '{{ template "rabbitmq.fullname" . }}'
  values:
    fullnameOverride: rabbitmq
    auth:
      username: default
      password: 'rabbitpAssw0rd'
      erlangCookie: NaTCCqW0Azv29WKsngoAdhI9W2FVXjt3
    clustering:
      rebalance: true
    ingress:
      enabled: true
      hostName: rabbitmq.local.app.garden
      annotations:
        kubernetes.io/ingress.class: nginx
    volumePermissions:
      enabled: true
    forceBoot:
      enabled: true
```

### Your environment

* **OS:**  OSX/macOS
* **How I'm running Kubernetes:**  docker-desktop

`garden version`
0.12.11
