### ISSUE TITLE
Getting 403 on garden deploy for ingress-controller while following getting started tutorial

### ISSUE THREAD

**Issue by samirspatel** [garden-io/garden#2177]
### Current Behavior
`garden deploy` causes a 403

### Expected behavior
It works

### Reproducible example
Follow the intro and get to step 4 https://docs.garden.io/getting-started/4-deploy-and-test

```
garden deploy
Deploy 🚀

 providers                 → Preparing environment...
    local-kubernetes          → Configuring...
   ✔ providers                 → Getting status... → Cached
      ℹ Run with --force-refresh to force a refresh of provider statuses.
   ✔ providers                 → Getting status... → Cached
      ℹ Run with --force-refresh to force a refresh of provider statuses.
   ✔ default-backend           → Getting build status for v-63466f0842... → Done (took 0 sec)
   ✖ ingress-controller        → Building version v-ec25112937...
   ✔ default-backend           → Deploying version v-63466f0842... → Already deployed

Failed resolving provider local-kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
local-kubernetes — an error occurred when configuring environment:
Error: Command "/Users/samirpatel/.garden/tools/helm/4d13a6c3bb98b810/darwin-amd64/helm --kube-context docker-desktop pull stable/nginx-ingress --untar --untardir
/var/folders/r0/vqtrb1_x3ylc0vs7l38ndlrh0000gn/T/tmp-47363-oD0EbCZvUKQ0 --version 1.26.2" failed with code 1:

Error: failed to fetch https://kubernetes-charts.storage.googleapis.com/nginx-ingress-1.26.2.tgz : 403 Forbidden

Error: failed to fetch https://kubernetes-charts.storage.googleapis.com/nginx-ingress-1.26.2.tgz : 403 Forbidden
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- local-kubernetes

See error.log for detailed error message
```

### Additional context

**project.garden.yml**
```
kind: Project
name: demo-project
environments:
  - name: default
providers:
  - name: local-kubernetes
```

**frontend/garden.yml**
```
kind: Module
type: container
name: frontend
dockerfile: Dockerfile
services:
  - name: frontend
    ports:
      - name: http
        containerPort: 8080
    ingresses:
      - path: /hello-frontend
        port: http
      - path: /call-backend
        port: http
    dependencies:
      - backend
tests:
  - name: unit
    args: [npm, test]
  - name: integ
    args: [npm, run, integ]
    dependencies:
      - frontend

```

**backend/garden.yml**
```
kind: Module
type: container
name: backend
dockerfile: Dockerfile
services:
  - name: backend
    ports:
      - name: http
        containerPort: 8080
        servicePort: 80
    ingresses:
      - path: /hello-backend
        port: http
```

### Your environment
Docker desktop 3.0.3 Local Kubernetes Cluster

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version` `0.12.11`
