### ISSUE TITLE
Can't use local env vars in template strings in workflow steps

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2235]
### Current Behavior

I'm getting a validation error when using local env vars in workflow steps, see repro below. 

### Reproducible example

Create a workflow like this:

```yaml
kind: Workflow
name: run-tests
steps:
  - name: run-tests
    skip: ${local.env.SKIP != ''}
    command: [test]
```

Run `garden validate` and observe the error:

```console
Error validating workflow: key .steps[0][skip] must be a boolean
```

### Workaround

This only seems to be an issue with local env vars so the following should work:

```yaml
kind: Project
variables:
  skip: ${local.env.SKIP}

---

kind: Workflow
name: run-tests
steps:
  - name: run-tests
    skip: ${var.SKIP != ''}
    command: [test]
```
  
### Additional context

This was written in a hurry, @thsig feel free to elaborate.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
