### ISSUE TITLE
Deploy hangs at "Attempting to initialize EnterpriseAPI client" when a remote source is linked

### ISSUE THREAD

**Issue by LeoDupont** [garden-io/garden#2252]
### Current Behavior

I have a Garden project with several remote sources.
I usually have no problem deploying the project with either linked or unlinked sources.

But for one new remote source, I have a problem: the deployment hangs at the very first stage if the source is linked to a local directory (it works well if not linked though):

```
> garden link source my-new-service ../my-new-service -l debug
Link source

Attempting to initialize EnterpriseAPI client.
i my-new-service             → Fetching from https://user:pwd@bitbucket.org/my-org/my-new-service.git#feature-branch
√ my-new-service             → Fetching from https://user:pwd@bitbucket.org/my-org/my-new-service.git#feature-branch
Linked source my-new-service
Something went wrong while checking for the latest Garden version.

> garden deploy -l debug
Deploy 

Attempting to initialize EnterpriseAPI client.
```

And it doesn't progress further even after one hour.

If I cancel the deployment and try to unlink the source, it hangs too. So I have to delete the `.garden` folder to do another test.

Also, you'll notice the `Something went wrong while checking for the latest Garden version.` message. 
I get this same message even when the deployment works correctly.
I updated my Garden CLI to the latest version (0.12.16), and the cluster with `garden plugins kubernetes cluster-init`.

### Reproducible example

I don't know what causes this error, so here is a redacted copy of my remote source's `garden.yml`. Although it is based on the same scheme as my other modules:

```yml
kind: Module
type: container
name: my-new-module
description: Problematic module

services:
  - name: my-new-service
    args: ["node", "./server.js"]

    ports:
      - name: http
        containerPort: 8080
        servicePort: 80

    env:
      SERVICE_NAME: my-new-service
      CONTAINER_PORT: 8080
      ENV: ${var.env}

---
kind: Module
type: kubernetes

name: my-new-service-routing-module
description: For Istio's VirtualService

files:
  - routing.yml
```

And my Garden project's `garden.yml`:

```yml
kind: Project
name: my-cloud

defaultEnvironment: dev

environments:
  - name: dev
    defaultNamespace: dev
    variables:
      env: dev

  - name: prod
    defaultNamespace: prod
    variables:
      NODE_ENV: production
      env: prod

providers:
  - name: kubernetes
    environments: [dev]
    context: gke_redacted_context_dev
    buildMode: cluster-docker
    setupIngressController: false

  - name: kubernetes
    environments: [prod]
    context: gke_redacted_context_prod
    buildMode: cluster-docker
    setupIngressController: false

sources:

  - name: my-working-service
    repositoryUrl: https://oauth2:token@gitlab.com/my-org/my-working-service.git#master

  - name: my-new-service
    repositoryUrl: https://user:pwd@bitbucket.org/my-org/my-new-service.git#feature_branch
```

### Your environment

* **OS:** Windows 10 Home 20H2 19042.804
* **How I'm running Kubernetes:** GKE

`garden version`: 0.12.16

Let me know what more info I can provide to debug this.
Thank you.
