### ISSUE TITLE
Increasing the sync storege size fails initial setup

### ISSUE THREAD

**Issue by Chipcius** [garden-io/garden#2260]
## Bug
K8s error
```
failed to provision volume with StorageClass "garden-system-nfs-v2": error validating options for volume: insufficient available space 517649367040 bytes to satisfy claim for 524288000000 bytes
```

### Current Behavior

When storage sync is set to any larger than 100GB value it fails to provision

### Expected behavior

Provisioning a garden setup with any size sync storage should provision successfully. 

### Reproducible example

`project.garden.yaml`
```
kind: Project
name: test
environments:
  - name: dev
    defaultNamespace: "u-${local.username}"
providers:
  - name: kubernetes
    buildMode: kaniko
    setupIngressController: nginx
    context: garden-dev
    storage:
      sync:
        size: 500000
    environments:
      - dev
defaultEnvironment: "dev"
```

### Workaround

1. Provision the Garen with the default values for sync size
2. Set the desired sync disk size and re-run the Garden provisioning

NFS provisioning stays at 10G but if you open up the container the underlying mount actually updates to the desired size
![image](https://user-images.githubusercontent.com/1033039/108707844-86ff5280-7508-11eb-862f-79f55fe0a564.png)

### Suggested solution(s)

Fix the inconsistency where the NFS request is bigger than the available space in the NFS provisioner

### Your environment

* **OS:** Ubuntu 20.04.1 LTS
* **How I'm running Kubernetes:** AWS EKS
* **Garden version:** 0.12.16
