### ISSUE TITLE
Missing files from docker image

### ISSUE THREAD

**Issue by csgergo123** [garden-io/garden#2299]
### Current Behavior

It seems sometimes the garden.io builds incorrectly the docker image. Somehow one file is missing from the image that is there in the source folder in my machine. Files are missing according to the error log. The missing file is not always the same.

`garden build` -> The build is successful.
`garden deploy` -> The deploy process sometimes works fine, sometimes fails with a custom error (because of the missing files). Moreover, when the deployment process is fine too, sometimes the running pod crashes because of the same error. So either shows the error already during deployment or in the running container after deployment.

It's important to mention that sometimes everything works great, and then after a few minutes this error occurs, even though nothing changes in the source code that can cause it. It seems random to me.

If I see in the container what is built from the image what the garden.io built, I really can't find the files there that should be there.

### Workaround

Need to run the `garden deploy` or `garden dev` more than once. It can be up to 10.

### Your environment

* **OS:** Windows 10
* **Garden.io version:** 0.12.18
* **How I'm running Kubernetes:** Remote cluster
* **buildMode:** cluster-docker

**Comment by edvald** [comment]
Hey @csgergo123. That's quite odd. We'd need quite a bit more information to go on though to try and debug. Can you share the configuration for the module in question?

**Comment by ITHedgeHog** [comment]
I run in to something with sounds like the same issue, when I'm debugging next and it happens I'll grab some repo steps (The project is opensource, so hopefully you can replicate).

I have a work around at the moment, which is to make a whitespace change to the Docker file and save it - it seems to resolve it.

**Comment by csgergo123** [comment]
Hey @edvald .
I have a repo called admin.

Most of the times the process going well. But sometimes the node application crashes.
Right now the exact error is:

> Error: Cannot find module '../../db/knexfile'".

Screenshot. https://ibb.co/bBrYC9b
This screenshot clearly shows that all the files are in the original directory, but the container which was launched from the faulty image is missing the knexfile.

The application seaches the knexfile in the right place but the file is not there.
I tried running on both remote kubernetes cluster and local docker too. I tried rerun from the built image.
Screenshot. https://ibb.co/GRbsnNB

Sometimes the knexfile is missing, sometimes the whole db directory, sometimes completely different file. It seems random to me.
Screenshot.  https://ibb.co/KG8CspG

Then when I edit something (even a whitespace) in a file and rebuild and redeploy with garden occasionally working well for a while.

I copy some files to help to debug.

### /garden.yml
```
kind: Project
name: admin
defaultEnvironment: "remote"
environments:
  - name: remote
providers:
  - name: kubernetes
    environments: [remote]
    context: ****
    namespace: admin
    defaultHostname:  ****
    # buildMode: cluster-docker       # Remote build mode
    deploymentRegistry:
      hostname: ****
      namespace: garden-system
    clusterDocker:
      enableBuildKit: false      # Tried true also
```
### /admin/garden.yml
```
kind: Module
name: admin
type: container
hotReload:
  sync:
    - target: /usr/src/app
  postSyncCommand: [touch, /usr/src/app/hotreloadfile ]
services:
  - name: admin
    ports:
      - name: http
        containerPort: 8000
        servicePort: 80
    ingresses:
      - path: /
        port: http
        hostname: "****"
    environments:
      - varfile: './env-files/development.env'
    hotReloadArgs: [npm, run, start:dev]
build:
  timeout: 3600
```

### /admin/Dockerfile
```
FROM node:14.15

EXPOSE 8080

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json /usr/src/app/

RUN npm install
RUN npm install -g knex 

COPY . /usr/src/app

RUN npm run gulp build

CMD ["node", "app.js"]
```
