### ISSUE TITLE
Module Templates makes Hot Reload go into infinite loop

### ISSUE THREAD

**Issue by estoesto** [garden-io/garden#2315]
### Current Behavior

When using Module Templates for the `kubernetes` type and Hot Reload together, any file change will result in Hot Reload looping forever. I suspect Hot Reload makes `module.generateFiles()` rewrite the generated .yml file which then triggers Hot Reload again. I verified this by checking the Linux timestamp on the generated file, which keeps changing.

Using `.gitignore` or changing `hotReload.sync.source` to exclude the generated file did not help.

### Expected behavior

Hot Reload is triggered once on a file change.

### Reproducible example
My `garden.yml` looks like this
```
kind: Module
type: templated
template: k8s-container
name: my-app
inputs:
  containerPort: 8010
  servicePort: 80
```
And my `template/garden.yml` looks like this
```
kind: ModuleTemplate
name: k8s-container
inputsSchemaPath: schema.json
modules:
  - type: container
    name: ${parent.name}-image
    description: ${parent.name} image
    hotReload:
      sync:
      - target: /usr/app/
  - type: kubernetes
    name: ${parent.name}-manifests
    serviceResource:
      kind: Deployment 
      name: ${parent.name}-web-deployment
      containerModule: ${parent.name}-image
      containerName: ${parent.name}-web
    build:
      dependencies: ["${parent.name}-image"]
    files: [manifests/.manifests.yml]
    generateFiles:
      - sourcePath: web-garden-manifests.yml
        targetPath: manifests/.manifests.yml
```

### Your environment

* **OS:**  macOS 10.15.7
* **How I'm running Kubernetes:** Docker Desktop

`garden version` 0.12.19
