### ISSUE TITLE
BuildKit tries to reach un-deployed garden-docker-registry

### ISSUE THREAD

**Issue by Dariusch** [garden-io/garden#2339]
## Bug

I am running `cluster-buildkit` on GKE on `cos_containerd` against Google Container Registry and I am encountering errors reaching a service which is not available.

### Current Behavior

There is a BuildKit deployment created in each namespace.

The BuildKit proxy container tries to reach the `garden-docker-registry.garden-system.svc.cluster.local` (every 10s) but there is no such service deployed.
```shell
2021/04/07 17:59:25 socat[902] E getaddrinfo("garden-docker-registry.garden-system.svc.cluster.local", "NULL", {1,0,1,6}, {}): Name does not resolve
```

The BuildKit `util` container is also trying to connect to some service  (every 1s) (most likely the same as above):
```
2021/04/07 17:59:26 [9724] connect from UNDETERMINED (10.51.0.1)
```

For some reason I saw some garden deployments in the garden-system namespace with an earlier version of the garden-cli. As of right now there is only the namespace and no deployments running inside of it.  

Running the following commands is also not re-deploying the services:
```shell
garden --env=remote plugins kubernetes uninstall-garden-services
garden --env=remote plugins kubernetes cluster-init
```

imho there is either something wrong with my garden cluster setup (missing services) or BuildKit should not try to connect to while given an external registry.

### Expected behavior

The `garden plugins kubernetes cluster-init` is redeploying the garden k8s deployments.
The BuildKit containers connect to the service and stop logging errors.

### Suggested solution(s)

The `garden plugins kubernetes cluster-init` is redeploying the garden services or trying to fix/ignore the connection issues in the BuildKit deployment.

### Sample Configuration

```yaml
kind: Project
name: some-service
defaultEnvironment: remote
environments:
  - name: remote
providers:
  - name: kubernetes
    environments: ["remote"]
    context: gke_company-cluster_europe-west1-d_cluster
    namespace:
      name: ${local.username}
    buildMode: cluster-buildkit
    deploymentRegistry:
      hostname: "eu.gcr.io"
      namespace: "company-cluster/${local.username}"
    imagePullSecrets:
      - name: gcr-config
        namespace: default
```

### Your environment

* **OS:** macOS Big Sur
* **How I'm running Kubernetes:** GKE `cluster-buildkit` on `cos_containerd`

`garden version`
0.12.20
