### ISSUE TITLE
[FEATURE]: Support for Kubernetes Standard Registry Discovery

### ISSUE THREAD

**Issue by piotrminkina** [garden-io/garden#2393]
## Feature Request

Firstly, thank you for the wonderful product that is Garden. It simplifies a lot in the daily work of developing cloud solutions.

### Background / Motivation

Integration with the local Docker registry provided by [Kind](https://kind.sigs.k8s.io/docs/user/local-registry/), [microk8s](https://microk8s.io/docs/registry-built-in) and [k3d](https://k3d.io/usage/guides/registries/#using-a-local-registry).

### What should the user be able to do?

I think the user does not need to do anything else.

### Why do they want to do this? What problem does it solve?

The introduction of this feature should simplify working with the Docker registry, provided by mentioned Kind, microk8s and k3d. The Docker registry on the local Kubernetes cluster is visible at a different URL from the point of view of the host and Pod on this cluster. Same as the following example.

```yaml
# kubectl get configmaps -n kube-public -o yaml local-registry-hosting
---
apiVersion: v1
data:
  localRegistryHosting.v1: |
    host: localhost:37393
    hostFromContainerRuntime: k3d-k3s-local-registry:5000
    help: https://k3d.io/usage/guides/registries/#using-a-local-registry
# [...]
```

### Suggested Implementation(s)

In the same way as it is now implemented in [Tilt](https://docs.tilt.dev/choosing_clusters.html#discovering-the-registry). So if above ConfigMap exists on the cluster, then Garden should publish Docker images into `localhost:37393`, but applied YAML files by Garden should point to `k3d-k3s-local-registry:5000`.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
