### ISSUE TITLE
Template rendering is interrupted when $$ occurs in combination with { and }

### ISSUE THREAD

**Issue by piotrminkina** [garden-io/garden#2396]
### Current Behavior

`generateFiles` generates the following invalid `script.bash` as a result:

```bash
#!/bin/bash

dirPath=/workspace/script-templating/
fileName=script-templating.result
filePath=$${dirPath%/}/$${fileName}
contents="# Generated by: ${this.name}"

echo "$${contents}" >"$${filePath}"
```

### Expected behavior

`generateFiles` must generate the following `script.bash` as a result:

```bash
#!/bin/bash

dirPath=/workspace/script-templating/
fileName=script-templating.result
filePath=${dirPath%/}/${fileName}
contents="# Generated by: script-templating"

echo "${contents}" >"${filePath}"
```

### Reproducible example

1. Create directory `script-templating` for module.

2. Create file `garden.yml` with the following module definition:

```yaml
---
apiVersion: garden.io/v0
kind: Module
name: script-templating
type: exec
local: true
generateFiles:
  - sourcePath: script.bash.tpl
    targetPath: script.bash
build:
  command:
    - /bin/bash
    - script.bash
```

3. Create file `script.bash.tpl` with the following script template:

```
#!/bin/bash

dirPath=${this.path}/
fileName=${this.name}.result
filePath=$${dirPath%/}/$${fileName}
contents="# Generated by: ${this.name}"

echo "$${contents}" >"$${filePath}"
```

4. Enter the following command: `garden run module script-templating`
5. Check generated `script.bash`. Additionally file `script-templating.result` should be generated, but because of this error, there are files like `1234{filePath}`, where `1234` is a PID during script executing.

### Workaround

I must use `$${dirPath}` instead of `$${dirPath%/}`.

### Suggested solution(s)

The occurrence of `$$` should completely omit the occurrence of the characters `{` and `}`.

### Additional context

All the following examples causes this bug: `$${`, `$${}`, `$${word` and , `$${word%}`, but only `$${word}` works as expected.

### Your environment

* **OS:** alpine linux
* **How I'm running Kubernetes:** k3s created by k3d

`garden version`
0.12.21
