### ISSUE TITLE
Unable to build images in Kaniko after update to 0.12.22 (Kaniko + in cluster registry)

### ISSUE THREAD

**Issue by Chipcius** [garden-io/garden#2418]
## Bug
I can no longer build my images in Kaniko after updating to 0.12.22

### Current Behavior

![image](https://user-images.githubusercontent.com/1033039/120078680-26038f80-c0a0-11eb-84b9-6ac8ec9a262d.png)

### Expected behavior

It should build just fine

### Reproducible example

Is easily repeatable in my repository but according to @edvald  it is not easily reproducible on his side.

To make sure I jumped up and down a version a couple of times and completely removed garden from my cluster and re-installed for both versions.

Works fine on 0.12.21 and fails on 0.12.22

Garden files included in additional context

### Workaround

Downgrade back to 0.12.21

### Additional context

project.garden.yaml
```
kind: Project
name: system

environments:
  - name: dev
    defaultNamespace: 'u-${local.env.USER || local.username}'

providers:
  - name: kubernetes
    context: gd1
    #buildMode: cluster-buildkit
    buildMode: kaniko
    namespace:
      name: 'system-u-${local.env.USER || local.username}'
      labels:
        istio-injection: enabled
      annotations:
        field.cattle.io/projectId: "${local.env.GARDEN_RANCHER_PROJECT || '<redacted>'}"
    environments:
      - dev
    storage:
      registry:
        size: 200000
      sync:
        size: 200000


defaultEnvironment: 'dev'

```

module.garden.yaml
```
kind: Module
type: exec
name: yarn-build
build:
  command:
    - "./yarn install && ./yarn build"
include:
  - src/**/*.js
  - src/**/*.jsx
  - src/**/*.ts
  - src/**/*.tsx
  - src/**/*.css
  - src/**/*.scss
  - src/**/*.graphql
  - yarn
  - yarn.lock
  - package.json
  - apollo.config.js
  - babel.config.js
  - .eslintrc.json
  - inner_modules
  - jest.config.js
  - postcss.config.js
  - .prettierrc
  - tsconfig.json
  - webpack.config.js
  - webpack.dev.js
  - public/inc
---
kind: Module
type: container
name: system-fpm
dockerfile: Dockerfile
build:
  dependencies:
  - name: yarn-build
    copy:
      - source: public/bundles
        target: public/bundles
hotReload:
  sync:
  - source: src
    target: /var/www/src
  - source: vendor
    target: /var/www/vendor
services:
  - name: system-fpm
    ports:
      - name: fpm
        containerPort: 9000
        servicePort: 9000
---
kind: Module
type: container
name: system
dockerfile: Dockerfile.nginx
build:
  dependencies:
  - name: yarn-build
    copy:
      - source: public/bundles
        target: public/bundles
services:
  - name: system
    ports:
      - name: http
        containerPort: 80
        servicePort: 80
---
kind: Module
type: kubernetes
name: system-gateway
manifests:
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: system-gwy
    spec:
      selector:
        istio: ingressgateway # use istio default controller
      servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
        - ${local.env.USER || local.username}.<redacted>
  - apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: virtual-svc
    spec:
      hosts:
      - ${local.env.USER || local.username}.<redacted>
      gateways:
      - system-gwy
      http:
      - route:
        - destination:
            host: system
```

### Your environment

* **OS:** Ubuntu 20.04
* **How I'm running Kubernetes:** GKE
* **Garden version:** 0.12.22

**Comment by eysi09** [comment]
Hi @Chipcius and thanks for creating the issue. 

We're looking into this and trying to repro on our end, hence the "needs-more-info" label.

**Comment by eysi09** [comment]
Hi @carlosjgp 

A few things to unpack here.

> Garden is building the images locally on my laptop instead of spinning up Kaniko pods on the cluster.

Just to confirm, do you mean that you've fallen back to building locally because of the issue with Kaniko described above?

> I've also noticed that Garden is now deploying a new POD into my NS called garden-util-<RS hash>-<POD hash> ... This is meant to run on garden-system

This is actually to be expected. We're phasing out the `garden-system` namespace and instead opting to de-centralize things via individual namespaces. This particular pod is a utility pod that replaces the previous build sync pods. That is, the code gets synced from your computer into this pod, which shares a volume with Kaniko (which eventuall does the building).

So the above looks normal.

> every time I run garden deploy <module> it takes about 20m even without changes

This however does not look normal. Can you try running `garden deploy <service> --show-timestamps --log-level silly`. It will be a lot of output but hopefully helps us diagnose the underlying issue.

**Comment by carlosjgp** [comment]
@eysi09 here is a gist with the logs (obfuscated due to company rules)

```
$ garden version
0.12.23
```

Total time: 20m 3s
At least 1/8 Cores of my laptop running @ 100% on occasions two and up to 3 of them on some peaks

https://gist.github.com/carlosjgp/a479026a432590c806e088afecebf3aa

**Comment by edvald** [comment]
There's a strange number of `Calling configure handler ...` log lines here. I suspect the high CPU usage may have something to do with that, and not the actual builds (which still appear to be happening in Kaniko as expected). So basically I think we're looking at two entirely separate issues here.

@carlosjgp Just to confirm that, could you also share the "silly" logs for the latest Garden version that does work for you?

**Comment by gsvachulay01** [comment]
Same here, I have this going with:
```
Failed building magic. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to query registry for image status: time="2021-08-23T21:43:08Z" level=fatal msg="Error parsing image name \"docker://127.0.0.1:5000/xyz/magic:v-469c9407a8\": Error reading manifest v-469c9407a8 in 127.0.0.1:5000/xyz/magic: received unexpected HTTP
status: 500 Internal Server Error"
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
on MacOS 10.15.7 Catalina (intel)
using garden 0.12.25 (today's latest, but same with previous too)
on config
```
...
  - name: kubernetes
    context: localk3s
    environments:
    - mac-k3s
    buildMode: kaniko
    # buildMode: cluster-buildkit
    # kaniko:
    #   namespace: null
    deploymentRegistry: null
    # deploymentRegistry:
    #   hostname: garden-docker-registry.garden-system.svc.cluster.local
    #   port: 5000
    #   namespace: library
    setupIngressController: false
    imagePullSecrets:
    - name: registrycreds
      namespace: default
...
```
as you can see from the commented out sections I tried various different combinations and directly addressing the internal registry too. That doesn't work as it's not listening on HTTPS. For every other combination I get the above error. Same is true for docker-buildkit (regardless of rootless or not).

This is extremely disruptive and I can't downgrade to 0.12.21 as the package for MacOS for that release is corrupted and it doesn't execute.

I can positively say using different combinations of `deploymentRegistry: null` or `deploymentRegistry:` makes no difference either.

I'll try setting up a dummy registry for circumventing remote, but some advice or fix would be welcome.
