### ISSUE TITLE
autoApply does not pass the -auto-approve flag to terraform

### ISSUE THREAD

**Issue by MarkMurphy** [garden-io/garden#2517]
### Current Behavior

My terraform provider config looks like this:

```yaml
providers:
  - name: terraform
    environments:
      - development
      - staging
      - production
    initRoot: ${var.terraform}
    autoApply: ${local.env.CI || false}
    allowDestroy: true
    variables:
      gcp_project: ${var.gcp_project}
      gcp_region: ${var.gcp_region}
      hostname: ${var.hostname}
    version: 0.13.3
    workspace: ${var.workspace}
```

On deployment `garden plugins terraform apply-root` fails because terraform is expecting a confirmation:

```sh
Do you want to perform these actions in workspace "garden-upgrade"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
Apply cancelled.
Command "/home/runner/.garden/tools/terraform-0-13-3/c40fcb8aa9f2b8d1/terraform apply -var-file /runner/_work/pose-stack/pose-stack/terraform/services/dev/garden.tfvars.json" failed with code 1
```

### Expected behavior

I've confirmed that the `CI` environment variable is present and set to `true` so garden should be passing the `-auto-approve` flag to the terraform apply command.

### Reproducible example

See context above.

### Workaround

I can work around this by specifying this myself in the garden command: 

```sh
garden plugins terraform apply-root -- -auto-approve
```

### Suggested solution(s)

Seems like it _should_ be a pretty straight forward fix

### Your environment

`garden version` 0.12.24
