### ISSUE TITLE
[Question] How do services[].dependencies work?

### ISSUE THREAD

**Issue by bbaga** [garden-io/garden#2529]
I'm a little confused about the usage `services[].dependencies`. In my use case, I have an `nginx` service that depends on two different `php-fpm` services. So I defined service for `nginx` as follows:

```yaml
kind: Module
type: container
name: nginx
services:
  - name: http
    ports:
      - name: http-a
        containerPort: 8380
        servicePort: 8380
      - name: http-b
        containerPort: 8480
        servicePort: 8480
    ingresses:
      - path: /
        hostname: service-a.local.app.garden
        port: http-a
      - path: /
        hostname: service-b.local.app.garden
        port: http-b
    dependencies:
      - php-fpm-a
      - php-fpm-b
```

and the graph on the dashboard shows the hierarchy fine, but when I run `garden dev`, every now and then the `http` (nginx) service fails to start because either `php-fpm-a` or `php-fpm-b` host is not available yet.

The documentation does not explicitly say that the services will be brought up in order based on the hierarchy, only that `garden` will make sure that the dependency services are started. **So the question is, am I doing something wrong configuration wise, or the start up sequence doesn't respect the hierarchy?** Interestingly, `garden delete environment` seems to start peeling back the services from the "top", so it looks like it is aware of the dependencies between the services.

Garden version: 0.12.24
