### ISSUE TITLE
[FEATURE]: container service tolerations

### ISSUE THREAD

**Issue by MarkMurphy** [garden-io/garden#2532]
### Background / Motivation

We have several processes that require autoscaling onto specific nodes within our Kubernetes cluster and require the ability to specify `tolerations` for some of our container services.

### What should the user be able to do?

Note desired `tolerations` property.

```
apiVersion: garden.io/v0
kind: Module
type: container
services:
- name: video-processor
    command:
      - process
    tolerations:
      - key: dedicated
        operator: Equal
        value: high_cpu
        effect: NoSchedule
    cpu:
      min: 4000
      max: 4000
    memory:
      min: 2000
      max: 2000
    replicas: 1
```

### Why do they want to do this? What problem does it solve?

See background.

### Suggested Implementation(s)

See code sample above.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment]
I'm not sure we'd add this level of control to the `container` module type. Our general line of thinking is that the `kubernetes` module type is where you should look once you need this level of control. Have you looked into that option?

**Comment by MarkMurphy** [comment]
IMHO there's already support for annotations, ingress, health checks, replicas, volumes, resources, etc. so drawing a line in the sand for tolderations feels a bit arbitrary.

> Our general line of thinking is that the `kubernetes` module type is where you should look once you need this level of control. Have you looked into that option?

Yep. That's how we're implementing it now. It's a bit of a pain compared to just using garden, here's example of what we'd like to do vs what we do now:
 
## What we'd like to do:

```yaml
services:
# ...
- name: video-processor
    command:
      - process
    dependencies: *dependencies
    env: *env
    volumes:
      - *storage
    tolerations:
      - key: dedicated
        operator: Equal
        value: high_cpu
        effect: NoSchedule
    cpu:
      min: 4000
      max: 4000
    memory:
      min: 2000
      max: 2000
    replicas: 1
```
 
## What we are doing now:

```yaml
---
apiVersion: garden.io/v0
kind: Module
type: kubernetes
name: video-processor
dependencies:
  - faktory
  - run-database-migrations
manifests:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: video-processor
      labels:
        module: api
        service: video-processor
    spec:
      replicas: 1
      selector:
        matchLabels:
          service: video-processor
      template:
        metadata:
          labels:
            module: api
            service: video-processor
        spec:
          containers:
            - command:
                - process
              env:
                - name: ANALYSIS_SERVER_URL
                  value: "analysis-server"
                - name: APNS_APP_BUNDLE_ID
                  value: ${providers.terraform.outputs.apns_app_bundle_id}
                - name: APNS_ENCRYPTION_KEY
                  value: ${providers.terraform.outputs.apns_encryption_key}
                - name: APNS_ENCRYPTION_KEY_ID
                  value: ${providers.terraform.outputs.apns_encryption_key_id}
                - name: APNS_TEAM_ID
                  value: ${providers.terraform.outputs.apns_team_id}
                - name: APNS_DEV_APP_BUNDLE_ID
                  value: ${providers.terraform.outputs.apns_dev_app_bundle_id}
                - name: APNS_DEV_ENCRYPTION_KEY
                  value: ${providers.terraform.outputs.apns_dev_encryption_key}
                - name: APNS_DEV_ENCRYPTION_KEY_ID
                  value: ${providers.terraform.outputs.apns_dev_encryption_key_id}
                - name: APNS_DEV_TEAM_ID
                  value: ${providers.terraform.outputs.apns_dev_team_id}
                - name: APP_STORE_CONNECT_PRIVATE_KEY
                  value: ${providers.terraform.outputs.appstoreconnect_private_key}
                - name: APP_STORE_CONNECT_ISSUER_ID
                  value: ${providers.terraform.outputs.appstoreconnect_issuer_id}
                - name: APP_STORE_CONNECT_KEY_ID
                  value: ${providers.terraform.outputs.appstoreconnect_key_id}
                - name: AUTH_API_AUDIENCE
                  value: ${providers.terraform.outputs.auth_audience}
                - name: AUTH_CLIENT_ID
                  value: ${providers.terraform.outputs.auth_client_id}
                - name: AUTH_CLIENT_SECRET
                  value: ${providers.terraform.outputs.auth_client_secret}
                - name: AUTH_TENANT
                  value: ${providers.terraform.outputs.auth_tenant}
                - name: AUTH_TOKEN_CUSTOM_NAMESPACE
                  value: ${providers.terraform.outputs.auth_custom_namespace}
                - name: BETA_APP_ID
                  value: ${providers.terraform.outputs.appstoreconnect_beta_app_id}
                - name: BROKER_HOST
                  value: ${providers.terraform.outputs.broker_host}
                - name: BROKER_VHOST
                  value: ${providers.terraform.outputs.broker_vhost}
                - name: BROKER_USERNAME
                  value: ${providers.terraform.outputs.broker_username}
                - name: BROKER_PASSWORD
                  value: ${providers.terraform.outputs.broker_password}
                - name: BUGSNAG_API_KEY
                  value: ${providers.terraform.outputs.bugsnag_api_server_key}
                - name: DAILY_API_KEY
                  value: ${providers.terraform.outputs.daily_api_key}
                - name: DAILY_DOMAIN_ID
                  value: ${providers.terraform.outputs.daily_domain_id}
                - name: GRAFANA_PASSWORD
                  value: ${providers.terraform.outputs.grafana_database_password}
                - name: GRAFANA_USERNAME
                  value: ${providers.terraform.outputs.grafana_database_username}
                - name: DB_HOST
                  value: ${providers.terraform.outputs.db_host}
                - name: DB_DATABASE
                  value: ${providers.terraform.outputs.db_name}
                - name: DB_PORT
                  value: 5432
                - name: DB_NAME
                  value: ${providers.terraform.outputs.db_name}
                - name: DB_USERNAME
                  value: ${providers.terraform.outputs.db_username}
                - name: DB_PASSWORD
                  value: ${providers.terraform.outputs.db_password}
                - name: FAKTORY_URL
                  value: ${providers.terraform.outputs.faktory_url}
                - name: HOST
                  value: ${providers.kubernetes.outputs.default-hostname}
                - name: INFERENCE_URL
                  value: ${providers.terraform.outputs.inference_url}
                - name: NODE_ENV
                  value: ${environment.name}
                - name: PORT
                  value: 3000
                - name: SMTP_HOST
                  value: ${providers.terraform.outputs.smtp_host}
                - name: SMTP_PORT
                  value: ${providers.terraform.outputs.smtp_port}
                - name: SMTP_USERNAME
                  value: ${providers.terraform.outputs.smtp_username}
                - name: SMTP_PASSWORD
                  value: ${providers.terraform.outputs.smtp_password}
                - name: STORAGE_BUCKET_NAME
                  value: ${providers.terraform.outputs.bucket_name}
              image: ${modules.api.outputs.deployment-image-id}
              name: video-processor
              resources:
                limits:
                  cpu: "2"
                  memory: 2000Mi
                requests:
                  cpu: "2"
                  memory: 2000Mi
              volumeMounts:
                - mountPath: /storage
                  name: storage
          tolerations:
            - key: dedicated
              operator: Equal
              value: high_cpu
              effect: NoSchedule
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: storage
```

This isn't a huge deal but it's not insignificant in comparison. The biggest thing here is that because we have so many environment variables and the syntax for specifying them in a kubernetes manifest is different from that of garden, we can't reuse the yaml anchor we used for another service defined in garden's env syntax. This results in duplicate code, is more error prone and adds a significant number of additional lines of code to our configuration. 
 
It seems like a lot of work just to add some tolerations. At the moment, we have five services we'll need to do this with.
