### ISSUE TITLE
Module variables don't seem to follow the behaviour described in the documentation

### ISSUE THREAD

**Issue by bbaga** [garden-io/garden#2541]
### Current Behavior

According to the documentation we can [override project variables on module level](https://docs.garden.io/using-garden/variables-and-templating#module-variables):

> Notice that you can override variables defined at the project-level, and even reference project-scoped variables when defining the module variables.

This override doesn't happen when I try to follow the examples. In fact, none of the variables defined in the module seem to be available inside the same module or other modules.

### Expected behavior

Variables should take the values from the module's configuration. 

### Reproducible example

```yaml
kind: Project
name: using-variables
environments:
  - name: default
providers:
  - name: local-kubernetes
variables:
  hostname: local
  database-password: password
  envVars:
    LOG_LEVEL: debug
    SOME_OTHER_VAR: something

---

# Copied example from: https://docs.garden.io/using-garden/variables-and-templating#module-variables
# my-service/garden.yml
kind: Module
name: my-service
type: container
variables:
  # This overrides the project-level hostname variable
  hostname: my-service.${var.hostname}
  # You can specify maps or lists as variables
  envVars:
    LOG_LEVEL: debug
    DATABASE_PASSWORD: ${var.database-password}
services:
  - name: my-service
    ports:
      - name: http
        containerPort: 80
        servicePort: 80
    ingresses:
      - path: /hello-backend
        port: http
        # This resolves to the hostname variable set above, not the project-level hostname variable
        hostname: ${var.hostname}
    # Referencing the above envVar module variable
    env: ${var.envVars}
```

The configuration above produces the following pod (shortened for brevity:

```
Containers:
  my-service:
    ...
    Environment:
      GARDEN_VERSION:                      v-c54b13bad3
      GARDEN_MODULE_VERSION:               v-208dd05d29
      GARDEN_VARIABLES_HOSTNAME:           local
      GARDEN_VARIABLES_DATABASE_PASSWORD:  password
      GARDEN_DEPENDENCIES:                 [{"moduleName":"my-service","name":"my-service","type":"build","version":"v-208dd05d29"}]
      LOG_LEVEL:                           debug
      SOME_OTHER_VAR:                      something
      POD_HOST_IP:                          (v1:status.hostIP)
      POD_IP:                               (v1:status.podIP)
      POD_NAME:                            my-service-6ccfc54549-vkttl (v1:metadata.name)
      POD_NAMESPACE:                       using-variables-default (v1:metadata.namespace)
      POD_NODE_NAME:                        (v1:spec.nodeName)
      POD_SERVICE_ACCOUNT:                  (v1:spec.serviceAccountName)
      POD_UID:                              (v1:metadata.uid)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lrvw2 (ro)
```

The `DATABASE_PASSWORD` variable appears only as `GARDEN_VARIABLES_DATABASE_PASSWORD` which I suspect comes from the `project`'s config.

On the same note, when I try reference any of these module variable from an other module ([example in docs](https://docs.garden.io/using-garden/variables-and-templating#referencing-module-variables)) like so:
```yaml
env:
  MY_SERVICE_HOSTNAME: ${modules.my-service.var.hostname}
```

I get the following error:
`my-service-dup: Invalid template string (${modules.my-service.var.hostname}): Could not find key hostname under modules.my-service.var.`

### Workaround

I don't have a workaround.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** docker-desktop

`garden version`: 0.12.24

PS: sorry for opening issues every day!
