### ISSUE TITLE
In watch mode, garden watches files and directories that are excluded in ignorefiles

### ISSUE THREAD

**Issue by FBurner** [garden-io/garden#2547]
### Current Behavior

garden deploy tries to watch node modules

```
UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/user/orojects/root-config/node_modules/yargs/build/lib/yerror.d.ts'
```

### Expected behavior

Not to watch node_modules since its excluded in gardenignore

```
.idea
/shared-dependencies/core/.yarn/
/shared-dependencies/core/.yarnrc.yml
node_modules/
.gitignore
.prettierignore
doc
```

### Reproducible example

```
garden deploy -w
```

### Your environment

* **OS:** Ubuntu
* **How I'm running Kubernetes:** Digitalocean 

`garden version` 0.12.24

**Comment by FBurner** [comment]
i now excluded multiple folders and checked every gardenignore

keeps still popping up 

Process memory threshold reached. This most likely means there are too many files in the project, and that you need to exclude large dependency directories. Please see https://docs.garden.io/using-garden/configuration-overview#including-excluding-files-and-directories for information on how to do that.

If this keeps occurring after configuring exclusions, please file an issue at https://github.com/garden-io/garden/issues.

**Comment by FBurner** [comment]
it seems if the folder is not a garden module the gardenignore file rules are not applied and the folder is watched even if there is a node-module folder inside

**Comment by FBurner** [comment]
```
kind: Module

type: container

name: campaign-frontend

hotReload:
  sync:
    - target: /app

services:
  - name: campaign-frontend
    ports:
      - name: http
        containerPort: 80
        servicePort: 80
    ingresses:
      - path: /
        hostname: domain.com
        port: http

dockerfile: Dockerfile
```
