### ISSUE TITLE
Helm values from a chart applied to dependent charts

### ISSUE THREAD

**Issue by pstetsuk-exadel** [garden-io/garden#2589]
### Current Behavior

I've create [simple project](https://github.com/pstetsuk-exadel/garden-helm-test) to reproduce this bug.  
There are 3 modules:
-  base-chart - base template
- chart1
- chart2 - depend on char1

In base-chart defined values.yaml
```
addPorts: {}
```

In chart1 garden.yml looks like
```
values:
  addPorts:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
```

In chart2 value for `addPorts` is not defined but defined dependency to chart1
```
dependencies:
  - chart1
```

### Expected behavior

Values defined for chart1 should not apply to chart2

### Reproducible example

After run `garden deploy` check `.garden\build\chart1\garden-values.yml` and `.garden\build\chart2\garden-values.yml`  
Both these files looks almost the same and contain
```
addPorts:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
```

### Workaround

If deploy modules one by one, `garden deploy chart1` and then `garden deploy chart2` all works as expected

### Your environment

* **OS:** Windows
* **How I'm running Kubernetes:** Docker Desktop

`garden version` `0.12.26`
