### ISSUE TITLE
Variables don't work for `modules.include` in project configuration.

### ISSUE THREAD

**Issue by mattpolzin** [garden-io/garden#2617]
## Bug

Variables cannot be used in the **project** configuration's `modules.include`.

As a simplified example, the following seems reasonable (though the more useful extrapolation of the example involves different variable values per-environment):
```yml
modules:
  include: ${var.project-include}
variables:
  project-include:
    - shared/*
```

### Current Behavior

`Error validating project: key .modules.include must be an array`

### Expected behavior

The `include` property is set to the array referenced by the template argument.

### Additional context

The guess posited in Slack was that the `modules.include` is being resolved prior to variable replacement occurring, though that does not seem necessary.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** Docker for Mac

`garden version` 0.12.27
