### ISSUE TITLE
[FEATURE]: allow setting annotations on garden managed pods

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#2628]
## Feature Request

Allow setting annotations on garden managed pods like build pods (kaniko or cluster-buildkit) and pods used for running tasks in helm, kubernetes and container modules.

### Background / Motivation

When using cluster-autoscaler, all pods without the annotation `cluster-autoscaler.kubernetes.io/safe-to-evict: false` can be evicted in a scale-down and scheduled on a new node. 
For Garden build pods like kaniko or cluster buildkit, as well as for tasks run through container, kubernetes or helm modules it is necessary to set this annotation, as eviction and re-deploying of these pods results in longer waits or even an undefined state (e.g. task is evicted mid-run).

### What should the user be able to do?

Specify annotations for build containers in the provider configuration and for tasks in the task definition in a module.

### Why do they want to do this? What problem does it solve?

Tasks and build pods are not getting evicted by scale-down operations from cluster-autoscaler, as well as other possible use-cases for annotations on pods.

### Suggested Implementation(s)

Specify annotations for build containers in the respective provider configuration e.g.:

```
providers:
  - name: kubernetes
    # Use the kaniko build mode
    buildMode: kaniko
    kaniko:
      namespace: null
      annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: false
```

And for tasks:

```
tasks:
  - name: echo-task
    command: [/bin/sh, -c]
    args: ["echo hello"]
    annotations: 
        cluster-autoscaler.kubernetes.io/safe-to-evict: false
```

### How important is this feature for you/your team?

🥀 Crucial, Garden is unusable for us without it

🌵 Not having this feature makes using Garden painful

🌹 It’s a nice to have, but nice things are nice 🙂
