### ISSUE TITLE
Strengthen YAML validation and error reporting

### ISSUE THREAD

**Issue by ohookins** [garden-io/garden#2653]
### Current Behavior

Right now the YAML parsing in the Garden CLI is very fragile, and unfortunately the error messages leave a lot to be desired.

For example, using the standard boilerplate project configuration you can start with this:
```yaml
providers:
  - # The name of the provider plugin to use.
    name: local-kubernetes
```

I was attempting to clean up the vast amounts of comments in this file and accidentally deleted the comment in the middle of that block, also removing the array notation that was needed for the following line, giving me this:

```yaml
providers:
    name: local-kubernetes
```

Running `garden validate` (or really, any garden command) yields this output:

```shell
$ garden validate
Validate ✔️


undefined is not a function
```

### Expected behavior

Some error that indicates that the configuration is malformed, and an approximate location of where the problem is.

### Reproducible example

An example project.garden.yml:

```yaml
kind: Project
name: example
environments:
  - name: default
providers:
    name: local-kubernetes
```

### Workaround

No workaround.

### Suggested solution(s)

Better error output for malformed configuration files.

### Additional context

N/A

### Your environment

* **OS:** MacOS 11.6
* **How I'm running Kubernetes:** Docker Desktop

`garden version`
0.12.30
