### ISSUE TITLE
[FEATURE]: Support resolution as objects of YAML template files

### ISSUE THREAD

**Issue by shivanshs9** [garden-io/garden#2659]
### Background / Motivation

I was writing a template kubernetes deployment manifest in the following format:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  annotations:
    garden.io/generated: "false"
    garden.io/version: ${modules.build-web.version}
  labels:
    app.kubernetes.io/managed-by: garden
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: ${modules.build-web.outputs.deployment-image-id}
          env:
            - name: APP_ENV
              value: ${environment.name}
          ports:
            - containerPort: 5555
          resources: ${var.webResources}
```
where `resources` can be customized based on the env. So it's a map object, not a string variable.

However, garden resolves the `webResources` as plain string, even though it's written as an object and thus it resolves it as `[object Object]` in the generated manifest.

### What should the user be able to do?

User should be able to resolve objects and arrays in templated manifests the same way one can do it in garden-specific config yaml.

### Why do they want to do this? What problem does it solve?

This will allow proper segregation of code and to not mix the kubernetes manifest along with the garden module config.

### Suggested Implementation(s)

Going through the code, I understand that these non-garden files are read as plaintext and hence resolved like plain strings ([how `generateFiles` option works](https://github.com/garden-io/garden/blob/e84066909e73118e8adc58324945282e2e0ea385/core/src/resolve-module.ts#L445)). I propose we can try reading the files with `.yaml/.yml` extension as objects and then resolve them with `resolveTemplateStrings` ([like used with garden configs](https://github.com/garden-io/garden/blob/e84066909e73118e8adc58324945282e2e0ea385/core/src/resolve-module.ts#L302)).
If the file can't be read as object, then garden can smartly fallback to the existing approach of reading file as string.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
