### ISSUE TITLE
[FEATURE]: Allow specifying the service account for container modules

### ISSUE THREAD

**Issue by jgeigerOnline** [garden-io/garden#2661]
### Background / Motivation

Using the high-level `container` type is quite handy when it comes to the auto-generated images based on `Dockerfile`s and other convenience mechanisms compared to the bare-bones `kubernetes` type that requires more manual work.

Having said that, I currently don't see how to specify the service account that will be used to run the (in my case) Kubernetes Pod based on the `container`, leading to a situation in my case where every Pod ends up being ran by the `default` service account that does not have the same privileges as other service accounts that I might require.

### What should the user be able to do?

Specify the service account for each service in my `garden.yml`, probably grouped in a "Kubernetes specific" property section separated from the other abstract properties of services that are not dependent on a specific technology. 

### Why do they want to do this? What problem does it solve?

See above, currently the `default` SA is used all the time.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful (it forces us to allow the default service account to be able to create Kubernetes jobs)

**Comment by eysi09** [comment]
Hi @jgeigerOnline 

Thanks for opening this issue. 

This has come up a couple of times in the past. The idea with the `container` module type is that it's an abstraction that is not strictly coupled to Kubernetes. So we try hard to not let Kubernetes concepts bleed into it. 

Instead, the recommendation is simply to use the `kubernetes` module type for those instances were you need K8s specific config.

You could create a `kubernetes` module type based on the config that Garden generates by reading the `Deployment`, `Service`, and `Ingress` resources from the cluster for the module in question (i.e. `kubectl get deployment <name-of-pod> -o yaml` and the same for the other resources). 

We also have plans for adding a `k8s-container` module that is as easy to use as the normal `container` module but has all the "escape hatches". But that's not on the immediate roadmap.

**Comment by jgeigerOnline** [comment]
Thanks for your response, I thought about using a `kubernetes` module as well but wouldn't that mean you would lose the ability to let Garden generate an image based on a local Dockerfile "on the fly"? The "asymmetry" between our other `container` modules and the one `kubernetes` module would indeed be a second nuisance albeit not a deal breaker - having a "Kubernetes aware" container module that supports a few specifics but still provides a nice abstraction sounds good though, especially as I found other Kubernetes features not yet available in a `container` module, like the delay for the readiness check whose absence currently means that `container` modules are checked for their readiness instantly, even though I already know that my application takes 45s to start and a check during the startup is redundant.

**Comment by eysi09** [comment]
Hi again

The way it works when you have some source code with a Dockerfile is that you reference it from the `kubernetes` module type. So saying you replace the `container` module with a `kubernetes` module is a little misleading, you actually need to use both. 

I think a little before and after probably explains this best:

Before:

```yaml
# in my-module/garden.ylm
kind: Module
type: container
name: my-module
services:
  # ...
```
  
 After:
 
 ```yaml
 kind: Module
 type: container
 name: my-module-image
 
 ---
 
 kind: Module
 type: container
 name: my-module
 manifests:
  - apiVersion: apps/v1
    kind: Deployment
    spec:
      template:
        spec:
          containers:
            - name: my-container
              image: ${modules.my-module-image.outputs.deployment-image-id} # <--- Here you reference the image version from the underlying container module that holds the source code. 
              imagePullPolicy: IfNotPresent
             # ...
 ```
 
This pattern allows you to have dynamic image versions in your Kubernetes module. 
 
And here's a guide for configuring dev mode for `kubernetes` and `helm` modules: https://docs.garden.io/guides/code-synchronization-dev-mode#configuring-dev-mode-for-kubernetes-and-helm-modules

We realise this is a bit clunky, hence the mention of a `k8s-container` module type. That's been on the roadmap for quite a while now. 

We'd be happy to help you configure this if you have any further questions.
