### ISSUE TITLE
Conditional statement not working with null for jib-container

### ISSUE THREAD

**Issue by carolinapc** [garden-io/garden#2685]
## Bug
Trying to use ```dependencies: ["${var.buildSharedLibs ? 'shared-libs' : null}"]``` in a jib-container module for **build.dependencies** property inside of a template but is throwing this error: **key .build.dependencies[0][name] must be a string**

### Current Behavior

Garden is expecting a string and does not handle null or undefined.

```
kind: ModuleTemplate
name: my-template
modules:
  - type: jib-container
    name: ${parent.name}-image
    description: Backend service
    include: [./*]
    exclude: [app/target/*]
    image: ${parent.name}
    extraFlags: [-Djib.useOnlyProjectCache=false, -Djib.to.tags=14.0.0-GCP-SNAPSHOT, -DskipTests=true, -Djib.from.image=gcr.io/distroless/java:8-debug, package]
    build: 
      jdkVersion: 8
      projectType: maven
      dependencies: ["${var.myCustomVar ? 'my-dependency-module' : null}"]
```

### Expected behavior

Garden should handle the null or undefined and not append the value to the dependency list.

### Suggested solution(s)

Do for jib-container module what was done in this ticket as well: https://github.com/garden-io/garden/pull/2264

### Your environment

* **OS:** linux distro
* **How I'm running Kubernetes:** GKE

`garden version: 0.12.31-edge-a5649c83`
