### ISSUE TITLE
[FEATURE]: module varfiles

### ISSUE THREAD

**Issue by tedchang77** [garden-io/garden#2687]
### Background / Motivation

we are using module templates to generate our jib modules and each generated module has a different set of build dependencies.  we would like to be able to use a varfile that is scoped to each module so we can reference it in the dependency property. this is a subset of: https://github.com/garden-io/garden/issues/2506 which describes a more fulsome variable hierarchy.

### What should the user be able to do?
create a module varfile and have it available as variables in the module. 

```
kind: ModuleTemplate
name: common-rest-module-template
modules:
  - type: jib-container
      name: ${parent.name}-image
      description: Backend service
      include: [./*]
      exclude: [app/target/*]
      image: ${parent.name}
      varfile: dependencies.yaml
      build: 
        jdkVersion: 8
        projectType: maven
        dependencies: 
          ${yamlEncode(var.dependencies)}
```
```
# dependencies.yaml
dependencies:
  - dependency1
  - dependency2
```

### Why do they want to do this? What problem does it solve?

we need a way to pass variables to a module from outside the garden application.  passing through files is the easiest way to do that.

### Suggested Implementation(s)

this module varfile should have higher precedence that module variables.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
