### ISSUE TITLE
[FEATURE]: Enable the `var` template key in template strings for `variables`

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#2730]
## Feature Request

Currently, the `var`/`variables` template key is not available when resolving template keys in `variables`. So, for example, something like this is currently not possible:
```yaml
# project config
...
variables:
  baseDomain: example.com # We want to reuse this prefix
  apiHostname: "api.${var.baseDomain}"
  webhookHostname: "webhooks.${var.baseDomain}"
```
Supporting this would require us to resolve `var` references inside `variables` blocks in dependency order.

### Background / Motivation

Supporting this would enable users to further reduce repetition in their configs.

### Suggested Implementation(s)

When resolving a variables block (e.g. for the project, or for an environment or module), construct a simple dependency graph of variable references (indexed by the variable key).

Then, resolve the variables in dependency order and incrementally populate the key/value pairs available under the `var` key and use them to resolve template strings further up the reference graph.

There should also be circular dependency detection with informative error messages.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
