### ISSUE TITLE
Ambiguous errors with bad .kube config

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#2741]
### Current Behavior

If there's a cluster with no name or an empty name in kube config a possibly confusing error is returned on some garden commands.

`clusters[0].name is missing`

This made me search the docs for `cluster` parameter that I though I needed to add to my garden project config and it took me a while to realize my kube config was faulty.

### Expected behavior

Ignore the clusters with invalid config?

### Reproducible example

`project.garden.yml`
```yml
kind: Project
name: demo-project-start
environments:
  - name: default
providers:
  - name: local-kubernetes
```
`.kube/config` file
```yml
apiVersion: v1
clusters:
- cluster:
    server: ""
  name: ""
...
```

running `garden deploy` returns this error:

```
Failed resolving provider local-kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
clusters[0].name is missing
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- local-kubernetes
```

### Workaround

Remove invalid cluster config from kube configs

### Suggested solution(s)

Specify in the error that the missing name is in kubernetes configs not garden project file

### Your environment

* **OS:**  macOS
* **How I'm running Kubernetes:**  Docker Desktop

`garden version`: 0.12.33
