### ISSUE TITLE
Workflows / Tasks 📋

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#276]
## Objective and motivation

Most backend systems need some degree of imperative bootstrapping before they're considered functional.
In the abstract this can be many types of things, perhaps the most common being database migrations and data
fixtures, but one can imagine other tasks like generating keys, pulling information from external systems etc.

## Design considerations

Rather than attempt to implement fine-grained support for those specific types of tasks, we should focus on
workflows in the abstract, as part of the development workflow and runtime dependency graph, and also consider
how the more fine-grained tasks could be further facilitated by dedicated plugins.

In terms of flows, users need to be able to define tasks to be executed in certain sequence, and often in relation
to service deployment.

In many cases the user only cares about the execution order, but in some cases they may also need outputs from one
task to be passed on to other tasks, and even services (as files, environment variables etc.). For this we can look
to how some CI systems are configured (e.g. CircleCI), and workflow engines like [Argo](https://argoproj.io).

## Design proposal

I propose the addition of _tasks_ as a primitive in our plugin framework and API. _(This notably differs from the
notion of task in the terms of our TaskGraph, but that's internal implementation detail and we may simply rename that
component.)_

A task is configured similarly to services, and plugins are able to define and run tasks if

1) The given module type's schema allows for configuration of tasks.
2) The _parseModule()_ handler for the module type correctly populates the output `ModuleConfig` via a new
   `taskConfigs` key (analogous to `testConfigs` and `serviceConfigs`).
3) They provide a `runTask()` action handler for the module type.

Note that 3) will often be decoupled from 1) and 2), as in the case of the `container` plugin, and the `kubernetes`
plugin.

The `runTask()` handler will be very similar to the `runModule()` handler, but I feel it's wise to separate them
in case the plugin needs to behave differently between them. Plugins can of course re-use most of the code internally,
as appropriate.

I imagine configuring `container` tasks would look something like this:

```yaml
module:
  name: db
  type: container
  services:
    - name: db
      dependencies:
        - db-bootstrap
  ...
  tasks:
    - name: db-prepare
      command: [npm, run, prepare]
    - name: db-migrations
      command: [npm, run, notify]
      dependencies:
        - db
  ...
```

Here the execution flow would be
1) Run `db-prepare` and wait for result.
2) Deploy `db` and wait until healthy.
3) Run `db-migrations` and wait for result.

First thing to note here is that *tasks share a namespace with services*. This is perhaps debatable, but otherwise
we'd be forced to make simple dependency configuration much more verbose. Also, it will often make more sense for
a service to depend on the _migrations_ task for a service, rather than the service being up. In the case above,
some other service needing the db would likely want to list `db-migrations` as a dependency.

Another small note, is that tasks and services will likely share a lot of configuration flags in most cases,
since the runtime configuration will be similar. But that's mostly implementation detail on the plugin-side.

Internally the above can be implemented fairly easily by adding another type of `TaskGraph` task (but remember
that the new task needs to be in the same dependency namespace as the `DeployTask`, so it's possible some
considerations need to be applied there, as well as when validating configs in `Garden`).

We should also add a `garden run task` helper, analogous to the other run commands.

### Inputs/outputs

The above omits any notions of task inputs/outputs. I do think we should hold off on implementing such a system,
but for the sake of completeness, here's a thought on how that might look:

```yaml
module:
  name: db
  type: container
  services:
    - name: db
      dependencies:
        - db-bootstrap
  ...
  tasks:
    - name: db-prepare
      command: [npm, run, prepare]
      outputs:
        - name: fixtures
          type: files
          source: /data/*   # POSIX-style path
    - name: db-migrations
      command: [npm, run, notify]
      inputs:
        - name: fixtures
          from: db-prepare
          target: /data/
      dependencies:
        - db-prepare
        - db
  ...
```

That's a pretty rough idea, and we can iterate on that part, maybe dig a bit deeper into other implementations, like CI systems and Argo. My sense is that most users will be happy with a
workflow graph to start, and can work around not being able to pass data between tasks. Migrations likely won't need this, for example. We may also want to come up with some general notions of passing info between tasks and services (and service to service, service to task etc.) when we dive deeper into this.

### Other thoughts

With this in place, we're starting to see real potential benefits of adding a visual layer to show how all modules, services, tasks and even repos are connected, and how they depend on each other. A separate project for sure, but something to think about.

## Plan

I suggest we give this high priority, because it is not very difficult to implement, is a popular request, and thus has high ROI.

We should also include at least one solid example project with some form of database migration, and a guide.

**Comment by thsig** [comment]
Looks good!

Here are a few initial thoughts:

> I propose the addition of tasks as a primitive in our plugin framework and API. (This notably differs from the notion of task in the terms of our TaskGraph, but that's internal implementation detail and we may simply rename that component.)

"Task" is a good user-facing term. Tried to think of another internal term to replace "task" (e.g. as in `BuildTask` and the like), but haven't come up with an attractive replacement so far.

Another approach would be to internally refer to Tasks with a term like `InitTask` (replace with your prefix of choice).

```yaml
module:
  name: db
  type: container
  services:
    - name: mydb
      dependencies:
        - db-bootstrap
  ...
  tasks:
    - name: db-prepare
      command: [npm, run, prepare]
    - name: db-migrations
      command: [npm, run, notify]
      dependencies:
        - db
  ...
```

Should the dependency for the `db-migrations` task be `mydb` instead of `db`? I.e. referring to a service, not a module? Same would apply to the second YAML snippet.

> Also, it will often make more sense for a service to depend on the migrations task for a service, rather than the service being up.

+1. The opposite case makes sense as well, i.e. tasks depending on services. For example, tasks that fetch information from a running service.

I think it makes sense for tasks to share a namespace with services. If we were to later consider introducing more types of dependency to this namespace, that might call for breaking this namespace up into services, tasks etc.

But while there are only two entity types in the namespace (services and tasks), a flat/simple namespace (as you suggest) is more elegant, and simpler for the user.

> We may also want to come up with some general notions of passing info between tasks and services (and service to service, service to task etc.) when we dive deeper into this.

I imagine it might also make sense to include a Task output type (maybe named `json` or the like) that's similar to the way nodes in the `TaskGraph` currently pass results to their dependants, in addition to the `files` option. But as you say, that belongs to a later iteration.
