### ISSUE TITLE
[FEATURE]: some way to override default namespace

### ISSUE THREAD

**Issue by jalper** [garden-io/garden#2762]
### Background / Motivation

Currently in our garden setup, developers' namespaces are defined in the project config using their local username. Sometimes a dev wants to spin up a second environment in a different namespace, or maybe they want to override a clunky local username with something simpler, and to do that they would need to append --env <namespace>.dev to every garden command.

### What should the user be able to do? + Suggested Implementation(s)
Some sort of .env file for garden, or even just some garden environment variables that can be used to override this and potentially other things, would be great.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by eysi09** [comment]
Hi @jalper 

We don't expose the namespace as an environment variable at the moment (you can see what we expose here: https://github.com/garden-io/garden/blob/master/core/src/constants.ts#L52).

But would this workaround do the trick:

```
kind: Project
name: demo-project
environments:
  - name: dev
    defaultNamespace: "${local.env.NAMESPACE || var.defaultNamespace}"
providers:
  - name: kubernetes
    # ...
variables:
  defaultNamespace: my-project-${local.username}
```

That being said, we've meant to add support for user level settings for a quite a while now but we've never properly prioritised it. Would be very useful though.
