### ISSUE TITLE
garden-util deployment not cleaned up when uninstalling cluster services

### ISSUE THREAD

**Issue by ohookins** [garden-io/garden#2773]
### Current Behavior

Running `garden plugins kubernetes uninstall-garden-services` I'm expecting that all Garden services are cleaned up and I'm left with a relatively clean cluster. Unfortunately the `garden-util` deployment and pod are left behind.

Potentially this output is related:

```
ℹ Deleting services...
   ℹ nginx-kind                → Deleting...
   ℹ docker-registry           → Deleting...
   ℹ docker-daemon             → Deleting...
   ℹ util                      → Deleting...
   ℹ registry-proxy            → Deleting...
   ℹ ingress-controller        → Deleting...
   ✔ nginx-kind                → Not found
   ✔ util                      → Not found
```

### Expected behavior

The `garden-util` deployment is not still present.

### Reproducible example

```
kind: Project
name: bc-garden
domain: https://xxxx.app.garden
id: XXXX
defaultEnvironment: dev
environments:
  - name: dev
providers:
  - name: kubernetes
    environments: [dev]
    context: arn:aws:eks:us-east-1:xxxx:cluster/garden
    buildMode: kaniko
    kaniko:
      namespace: null
    deploymentRegistry:
      hostname: xxxx.dkr.ecr.us-east-1.amazonaws.com
      namespace: bc/garden
    imagePullSecrets:
      - name: ecr-config
        namespace: default
    setupIngressController: nginx
```

### Workaround

I've been deleting the deployment manually.

### Suggested solution(s)

Possibly the wrong name is being looked for when cleaning up - if the `util` name in the above output is to be trusted.

### Additional context

N/A

### Your environment

* **OS:** macOS 11.6.2
* **How I'm running Kubernetes:** EKS 1.21

```
$ garden version
0.12.34
```
