### ISSUE TITLE
ENOTEMPTY: directory not empty

### ISSUE THREAD

**Issue by tbl-harmoney** [garden-io/garden#2816]
### Current Behavior

Occasionaly, Garden commands fail to deploy or delete a specific service:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/65944949/155367854-ffc7ce80-a8c2-4f75-95f9-a0083a48703b.png">

The service is declared as follows:
```yaml
kind: Module
type: kubernetes
name: db
dependencies: '${ environment.name == "local" ? yamlDecode("[db-local]") : yamlDecode("[]") }'
manifests:
  - kind: Service
    apiVersion: v1
    metadata:
      name: db
      labels:
        app: db
    spec:
      type: ExternalName
      externalName: '${ environment.name == "local" ? "db-local.local.svc.cluster.local" : "percona-xtradb-pxc-db-haproxy.percona-xtradb.svc.cluster.local" }'
```
### Expected behavior

Service is deployed/deleted correctly.

### Your environment

* **OS:** Linux, Docker, ubuntu-20.04 image 
* **How I'm running Kubernetes:** GKE  

`garden version` 0.12.34
