### ISSUE TITLE
"hashes.join is not a function" when using a variable in an `include` field 

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2853]
### Current Behavior

I have the following config:

```yaml
kind: Module
type: exec
name: variables
variables:
  includes: ["foo", "bar"]
# ...

---

kind: Module
type: container
name: image
include: ${modules.variables.var.includes} 
# ...
---

kind: Module
type: kubernetes
name: service
build:
  dependencies: [image]
# ...  
```  

When I run `garden build image` I get the following error:

```
Failed resolving one or more modules:

service: hashes.join is not a function
```

So resolving the `service` module fails when attempting to build the `image` module. 

Looks like this is the offending piece of code: https://github.com/garden-io/garden/blob/master/core/src/vcs/vcs.ts#L322

When logging the output I see that the value we're attempting to join is the following string:

```
"${modules.variables.var.includes}"
```

...as opposed to an array.

So clearly the value hasn't been resolved yet and is causing issues when resolving a down stream dependency. 

### Reproducible example

See above.

### Workaround

Do not use variables in `include` and instead hard code (or use project level variables, haven't tried).
