### ISSUE TITLE
Template expansion weird behavior

### ISSUE THREAD

**Issue by antoinelyset** [garden-io/garden#2862]
### Current Behavior

Template not expanding in a test.

### Expected behavior

Template should expand in a test.

### Reproducible example

Given:

```yaml
---
kind: Module
type: exec
name: hello-world
include: []
tasks:
  - name: hello-world
    command: ['echo', 'HelloWorld']
---
kind: Module
type: container
name: e2e-test
image: node:14.18.1-alpine3.13
tests:
  - name: run-e2e
    env:
      HELLO_WORLD: ${runtime.tasks.hello-world.outputs.log}
    dependencies:
      - hello-world
    command: [/bin/sh, -c]
    args: [env]
```
If I execute : `garden run test e2e-test run-e2e -i`
I see : `HELLO_WORLD=${runtime.tasks.hello-world.outputs.log}`
I should see : `HELLO_WORLD=HelloWorld`

It actually works with a task.

Given : 

```yaml
---
kind: Module
type: exec
name: hello-world
include: []
tasks:
  - name: hello-world
    command: ['echo', 'HelloWorld']
---
kind: Module
type: container
name: e2e-test
image: node:14.18.1-alpine3.13
tasks:
  - name: run-e2e
    env:
      HELLO_WORLD: ${runtime.tasks.hello-world.outputs.log}
    dependencies:
      - hello-world
    command: [/bin/sh, -c]
    args: [env]
```
If I run `garden run task run-e2e`
I see : `HELLO_WORLD=HelloWorld`

### Workaround

Not that I know of.

### Suggested solution(s)

I didn't investigate the code yet.

### Additional context

None.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** GKE 

Garden version: `0.12.36`
