### ISSUE TITLE
Garden workflows fail silently

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#2883]
### Current Behavior

Running Garden workflows with errors in them like: 

* a wrong yaml indentation
* an invalid trigger spec in which an environment is specified that does not exist
* an invalid trigger spec with a trigger event that does not exist

causes Garden to fail without any error messages. Running this workflow with log-level 5 does also not output any hints into what is potentially mis-configured.

![Screenshot 2022-04-04 at 11 00 44](https://user-images.githubusercontent.com/78752267/161510595-9f8b57c8-7482-4893-a06f-31f10484c7ef.png)

The error log mentioned is not created.

### Expected behavior

Some output or additional help into what is causing Garden to fail. If the cause is a mis-configured environment that should be in the output. In case there is a problem with the yaml it would be good to hint at that.

### Reproducible example

Run the following workflow with wrong yaml indentation:

```
kind: Workflow
name: test
description: Testing out Workflows
steps:
  - script: echo "Hello"
      description: Hello World
      name: hello-world
triggers:
  - events: [pull-request]
    environment: dev # <--- Use one of your own environments here
```

Or the following with a non-existing trigger event:

```
kind: Workflow
name: test
description: Testing out Workflows
steps:
  - description: Hello World
    name: hello-world
    script: echo "hello world"
triggers:
  - events: [ miaow ]
    environment: dev # <--- Use one of your own environments here
```

```
garden run workflow test
```

### Suggested solution(s)

Add some output of why a workflow might be failing.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
