### ISSUE TITLE
[FEATURE]: $merge operator should work in Kubernetes manifests

### ISSUE THREAD

**Issue by jamesmeneghello** [garden-io/garden#2965]
### Background / Motivation

`$merge` works in config files, but not in external manifests as part of Kubernetes modules.

While you can add a set of common labels using, e.g.:

```yaml
metadata:
    labels: ${var.commonLabels}
```

...it would be nice to be able to do:

```yaml
metadata:
    labels:
        some-label: some-value
        $merge: ${var.commonLabels}
```

### What should the user be able to do?

Use `$merge` in manifests in Kubernetes modules.

### Why do they want to do this? What problem does it solve?

Allows for overriding of maps in manifests.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
