### ISSUE TITLE
bug: module templates cannot contain other templated modules

### ISSUE THREAD

**Issue by yyc** [garden-io/garden#2992]
### Current Behavior

With the following `garden.yaml` file that contains a templated module, referencing a module template that contains another template:
```yaml
kind: Module
type: templated
template: midtemplate
name: toplevel
---
kind: ModuleTemplate
name: midtemplate
modules:
  - type: templated
    kind: Module
    name: ${parent.name}-mid
    template: basetemplate
---
kind: ModuleTemplate
name: basetemplate
modules:
  - type: container
    name: ${parent.name}-base
    image: ubuntu/focal
    services:
    - name: ${parent.name}-base-service
      command: 
        - nc
        - -l
        - '4000'
      ports:
        - servicePort: 80
          containerPort: 4000
          name: svc
```

Garden does not resolve the second templated module:
```
$ garden get modules
Get Modules

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌍  Running in namespace default.default
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
✔ graph                     → Resolving 2 modules... → Done

┌──────────────┬──────────────┬───────────┬──────┐
│ Name         │ Version      │ Type      │ Path │
├──────────────┼──────────────┼───────────┼──────┤
│ toplevel     │ v-f922154c26 │ templated │ ./   │
├──────────────┼──────────────┼───────────┼──────┤
│ toplevel-mid │ v-bfd158029f │ templated │ ./   │
└──────────────┴──────────────┴───────────┴──────┘
```

### Expected behavior
From the [module template docs](https://docs.garden.io/reference/module-template-config#modules):

> A list of modules this template will output. The schema for each is the same as when you create modules normally in configuration files, with the addition of a path field, which allows you to specify a sub-directory to set as the module root.

I'd expect that the second (and additional) layers of templating will be resolved recursively, and `garden get modules` would yield 3 modules: 2 templated modules and 1 container module.

### Reproducible example

Use the `garden.yaml` above and run `garden dev` (no containers come up) or `garden get modules` (should match the above output)

### Workaround

Our current approach would probably to flatten the templates into a single layer to get around this issue, but this creates a bloated file and also reduces our ability to compose multiple modules in different ways.

### Suggested solution(s)

Looking at [`scanAndAddConfigs`](https://github.com/garden-io/garden/blob/d94c83b83b854caae7d7a2b90f2e5f7c17704f0d/core/src/garden.ts#L940), it looks like garden only does a [single pass](https://github.com/garden-io/garden/blob/d94c83b83b854caae7d7a2b90f2e5f7c17704f0d/core/src/garden.ts#L978) of module template resolution, so nested templates wouldn't get resolved at all.

Is this an intentional design, to eliminate the possibility of circular dependencies? If not, I can look into creating a PR that fixes this code so that it makes additional passes on the newly-resolved templates. I could also add a limit to the number of iterations (in case there is an infinite loop due to a circular dependency). 

Please let me know if this is something that I should proceed with, whether there are any issues with my approach, or if it's something that the garden team would not actually want to support (in which case the documentation should probably clarify this)

### Your environment

* **OS:**  Ubuntu 20.04 on AWS EC2
* **How I'm running Kubernetes:** Minikube

`garden version 0.12.41`
