### ISSUE TITLE
can't grab element from array after using split() in string templating

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#3001]
This doesn't work with err: `Invalid template string (${split("something.else", ".")[0]}): Unable to parse as valid template string.`
```yml
kind: Module
name: test
description: test env string templating
type: exec
variables:
  element: ${split("something.else", ".")[0]}

tasks:
  - name: test
    env:
      TEST: ${var.element}
    command: ["echo $TEST"]
```
This does work as expected (prints "else" to the console)
```yml
kind: Module
name: test
description: test env string templating
type: exec
variables:
  arr: ${split("something.else", ".")}

tasks:
  - name: test
    env:
      TEST: ${var.arr[1]}
    command: ["echo $TEST"]
```
