### ISSUE TITLE
copySecrets is not copying secrets

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3048]
### Current Behavior

In the kubernetes provider configuration, I've added the following snippet:
```yaml
  - name: kubernetes
    copySecrets:
      - name: test
        namespace: default
```

The `test` secret in default namespace exists.

When deploying with the kubernetes provider, the secret is not copied over to the deployment namespace.

### Expected behavior

The `test` secret should be copied to the deployment namespace.

### Workaround

As a workaround I've written an `exec` service which fetched the relevant secrets via kubectl, strips metadata and reapplies them to the deployment namespace.

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.12.42
