### ISSUE TITLE
GKE Ingress controller incompatible ingress created with `garden deploy`

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3072]
## Bug

Garden creates ingresses for module type `container` incompatible with GKE clusters using the default GKE ingress controller which results in an error when trying to reach the created load balancer's IP: `response 404 (backend NotFound), service rules for the path non-existent`.

### Current Behavior

Given module type `container` with the following declaration:
```yaml
kind: Module
type: container
name: vscode-remote-try-python
dockerfile: Dockerfile
services:
  - name: frontend
    ports: 
      - name: http
        containerPort: 5000
        servicePort: 80
    ingresses:
      - port: http
```
and a project file:
```yaml
kind: Project
name: vscode-remote-try-python
environments:
  - name: remote
providers:
  - name: kubernetes
    context: gke_devrel-348008_europe-north1_gke-autopilot-north1-demo-1
    defaultHostname: vscode-remote-try-python.devrel.demo.garden
    deploymentRegistry:
      hostname: "docker.io"
      namespace: "worldofgeese"
```

Garden will create the following ingress declaration:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    garden.io/generated: "true"
    garden.io/manifest-hash: a238bf58e700e09f5ef8559c737f0aeb3114434d9ec74199378f9fe810ec72dc
    garden.io/version: v-0b9668f3fd
    ingress.kubernetes.io/backends: '{"k8s-be-32038--57c5a8cb84a64a0c":"HEALTHY","k8s1-57c5a8cb-vscode-remote-try-python-defa-frontend-8-61461ea1":"HEALTHY"}'
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/forwarding-rule: k8s2-fr-bh145e40-vscode-remote-try-python-def-frontend-toort30l
    ingress.kubernetes.io/target-proxy: k8s2-tp-bh145e40-vscode-remote-try-python-def-frontend-toort30l
    ingress.kubernetes.io/url-map: k8s2-um-bh145e40-vscode-remote-try-python-def-frontend-toort30l
  labels:
    module: vscode-remote-try-python
    service: frontend
  name: frontend-0
  namespace: vscode-remote-try-python-default
spec:
  rules:
  - host: vscode-remote-try-python.devrel.demo.garden
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
```

Google's own example documentation for creating container-native ingresses uses a different key to declare a backend service and service path:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neg-demo-ing
spec:
  defaultBackend:
    service:
      name: neg-demo-svc # Name of the Service targeted by the Ingress
      port:
        number: 80 # Should match the port used by the Service
```
### Expected behavior
`garden deploy` should create an ingress resource compatible with the default GKE ingress controller.

### Workaround
If one replaces the Garden's `rules` key with `defaultBackend`, a user should be able to access the service directly by IP:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    garden.io/generated: "true"
    garden.io/manifest-hash: a238bf58e700e09f5ef8559c737f0aeb3114434d9ec74199378f9fe810ec72dc
    garden.io/version: v-0b9668f3fd
    ingress.kubernetes.io/backends: '{"k8s-be-32038--57c5a8cb84a64a0c":"HEALTHY","k8s1-57c5a8cb-vscode-remote-try-python-defa-frontend-8-61461ea1":"HEALTHY"}'
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/forwarding-rule: k8s2-fr-bh145e40-vscode-remote-try-python-def-frontend-toort30l
    ingress.kubernetes.io/target-proxy: k8s2-tp-bh145e40-vscode-remote-try-python-def-frontend-toort30l
    ingress.kubernetes.io/url-map: k8s2-um-bh145e40-vscode-remote-try-python-def-frontend-toort30l
  labels:
    module: vscode-remote-try-python
    service: frontend
  name: frontend-0
  namespace: vscode-remote-try-python-default
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  # rules:
  # - host: vscode-remote-try-python.devrel.demo.garden
  #   http:
  #     paths:
  #     - backend:
  #         service:
  #           name: frontend
  #           port:
  #             number: 80
  #       path: /
  #       pathType: Prefix
```

### Your environment

* **OS:** Windows 11 running Ubuntu via Windows Subsystem for Linux 2
* **How I'm running Kubernetes:** GKE Autopilot v1.22.10-gke.600

`garden version` 0.12.43
