### ISSUE TITLE
[FEATURE]: Add SecurityContext to Container Module Type

### ISSUE THREAD

**Issue by marklester** [garden-io/garden#3135]
### What should the user be able to do?

I would like to set a securityContext so I can override behavior of a given image

### Why do they want to do this? What problem does it solve?

Sometimes images used for containers have default behavior that can't be changed in the image. Having a way to change that behavior in a way supported by k8s would be very helpful

### Suggested Implementation(s)

```yaml
services:
- name: mysql
  securityContext:
    runAsUser: 0
  ...
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
