### ISSUE TITLE
Error raised if module level varfile is missing.

### ISSUE THREAD

**Issue by disbr007** [garden-io/garden#3150]
### Current Behavior
According to[ the docs](https://docs.garden.io/using-garden/variables-and-templating?q=environment), if a `varfile` is set but cannot be found, "no error is raised". However, when I attempt to deploy with a missing path, an error is raised and the deploy fails.

My use case is a .gitignored environmental variable file that is not present in the production environment (where the variable are read into local.env from GH secrets).

### Expected behavior
If `varfile` is missing, no error is raised, deploy succeeds.

### Reproducible example
Module level `garden.yml`:
```yaml
# The type of this module.
type: container

# The name of this module.
name: proxy-arcgis

# POSIX-style name of Dockerfile, relative to module root.
dockerfile: Dockerfile

varfile: missing
services:
...
```
```bash
$ garden deploy
Failed resolving one or more modules:

proxy-arcgis: Could not find varfile at path 'missing'
```

### Workaround
None found.

### Suggested solution(s)
No error is raised if `varfile` is missing.

Thanks in advance, let me know what else I can provide or if I am missing something here.

* **OS:** PopOS
* **How I'm running Kubernetes:** minikube

`garden version`
0.12.33

![image](https://user-images.githubusercontent.com/60416467/186915563-d3888452-76eb-4309-9c92-24157ef066b0.png)
