### ISSUE TITLE
vars not passed via `command` in workflows

### ISSUE THREAD

**Issue by jrnxf** [garden-io/garden#3286]
### Current Behavior

task:

```
- name: argtest
  command: [/bin/sh, -c]
  args: ["echo ${var.args || '-h'}"]
  ...
```

workflow:

```
kind: Workflow
name: workflow-a
description: workflow-a
steps:
  - description: WORKS
    script: garden run task argtest --var args="foobar"]
  - description: DOES NOT WORK
    command: [run, task, argtest, --var, args="foobar"]

```

### Expected behavior

I would think these would be exactly the same thing. Even stranger, this works!

`garden custom-workflow-b --var args="whyyyyy"`

```
kind: Command
name: custom-workflow-b
description:
  short: custom-workflow-b
gardenCommand:
  - run
  - task
  - argtest
  - --var
  - args="${var.args || ''}"
```

### Reproducible example
refer to above 

### Workaround

I guess I could call a custom workflow within a normal workflow? Idk, feels icky

### Additional context

Originally asked here: https://community.garden.io/t/why-does-one-of-these-work-while-the-other-doesnt/323

### Your environment

* **OS:** 
MacOS Monterey 12.6 (Mac M1 Pro 2021)
* **How I'm running Kubernetes:**  
locally via docker desktop

`garden version`
0.12.44
