### ISSUE TITLE
can't use dedicated envVars for singular garden command within workflow

### ISSUE THREAD

**Issue by jrnxf** [garden-io/garden#3287]
### Current Behavior

As far as I can tell, there doesn't seem to be a way to pass a single environment variable to one specific workflow command. In other words, I don't want the variable for the entire workflow, just one command. Which means I can't use `command` and have to use `script`

      - description: Generate environment file using `garden generate-env-file ${environment.name}`
        script: POCUS_GARDEN_ENVIRONMENT=setup garden generate-env-file "${environment.name}"### Expected behavior

      - description: Generate environment file using `garden generate-env-file ${environment.name}`
        envVars: 
          - POCUS_GARDEN_ENVIRONMENT: setup
        command: [generate-env-file, "${environment.name}"]^^ maybe something like this?### Workaround

I think I just have to use `script` for now or break it out into it's own workflow which seems messy

### Your environment

* **OS:** MacOS Monterey 12.6 (2021 M1 Pro) 
* **How I'm running Kubernetes:** Docker Desktop  

`garden version` 0.12.44

**Comment by vvagaytsev** [comment]
Thanks for reporting this @thatvegandev! We'll take a look.

Actually, this looks more like a feature request, not a bug. The `envVars` are already supported, but only with the `script`s, not with `command`s. The `envVars` description says:
> A map of environment variables to use when running script steps. Ignored for `command` steps.
> Note: Environment variables provided here take precedence over any environment variables configured at the workflow level.

So, something like this should work fine:
```
- description: Generate environment file using `garden generate-env-file ${environment.name}`
  envVars: 
      - POCUS_GARDEN_ENVIRONMENT: setup
  script: garden generate-env-file "${environment.name}"
```

I'm wondering why `command` ignores the `envVars`. @thsig do you know why we did it in such a way?
Maybe we should propagate `envVars` to `command` too.
