### ISSUE TITLE
[FEATURE]: Conditional build dependencies

### ISSUE THREAD

**Issue by jondeandres** [garden-io/garden#3295]
Is there a way to have conditional build dependencies?

We have a scenario where we'd like to do something like this in a `helm` module:

```
build:
  dependencies:
    - name: image
values:
  image
    id: ${vars.IMAGE_ID || modules.image.deployment-image-id}
```

But if `vars.IMAGE_ID` is set we don't want to wait for the container module to be built.

Thanks.

But

**Comment by vvagaytsev** [comment]
Thanks for reporting this @jondeandres! That's a nice and useful feature request. We'll take a look soon.

**Comment by thsig** [comment]
Actually, this can be done quite neatly using templating. Something like this should work:
```yaml
build:
  dependencies:
    # Using the shorthand build dependency format here for convenience (i.e. just a string, the name of the dependency).
    - "${var.IMAGE_ID ? null : 'image'}"
values:
  image
    id: ${vars.IMAGE_ID || modules.image.deployment-image-id}
```
So I'll go ahead and close this one. We should document this pattern more clearly, though!
