### ISSUE TITLE
Helm module generateFiles: does not substitute in templated values

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3369]
### Current Behavior
The templated values are treated as plain strings, eg: `"${runtime.services.infrastructure-aws.outputs.db_password}"`

### Expected behavior
The value should be substituted in

### Reproducible example
garden.yaml

```
kind: Module
description: PostgreSQL
type: helm
name: pg
chartPath: ./postgresql
dependencies: 
  - infrastructure-aws
valueFiles:
  - postgresql/values.default.yml
generateFiles:
  - sourcePath: values.default.yml
    targetPath: postgresql/values.default.yml
```

values.default.yml

```
auth:
  database: ${var.database.name}
  username: ${var.database.username}
  password: "${runtime.services.infrastructure-aws.outputs.db_password}"
```

### Workaround
Move them to values: in garden.yaml

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
