### ISSUE TITLE
Helm module does not have good multiline if block support

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3370]
### Current Behavior
The only way to use ${if var.foo} is via generateFiles

### Expected behavior
Multiline if blocks should work in the values: section of garden.yaml

### Reproducible example
garden.yaml

```
kind: Module
description: PostgreSQL
type: helm
name: pg
chartPath: ./postgresql
values:
  primary:
    ${if var.autoscale_env}
    nodeSelector: 
      type: karpenter
      provisioner: default
    ${endif}
    resources:
      requests:
        memory: 256Mi
        cpu: 50m
```

This fails with a yaml error

### Workaround
Use generateFiles: with a separate values file.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
