### ISSUE TITLE
Kubernetes module does not treat 0 replica deployments correctly

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3377]
## Bug

I have a duplicate garden module of our server container to run tasks only with a different set of resource limits (higher memory request/limits).

The workaround I am using is a 0 replica deployment with the tasks attached to that module. (until garden supports different resource requests/limits for tasks on kubernetes)

### Current Behavior

With a 0 replica deployment there are two different behaviours:

spec.strategy.type = RollingUpdate  will deploy the first time but garden will timeout waiting for the 0 pods to report as ready.  Subsequent deployments will never begin as garden will wait for the previous 'attempt' to finish before starting a new one.

spec.strategy.type = Recreate  will replace the existing deployment but still timeout waiting for the 0 pods to report as ready, in CI this results in the deployment reporting as failed.

Per: https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/status/workload.ts#L41

```
kubectl rollout status deployment/one-server-task -n glx-test-test
deployment "one-server-task" successfully rolled out
```

Kubernetes itself considers the deployment to have succeeded.

### Expected behavior

Garden will recognise that the deployment has 0 replicas and not wait for them to be ready

### Reproducible example

deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-server-task
  labels: 
    *snip*
spec:
  replicas: 0
  selector:
    matchLabels: 
      *snip*
  template:
    metadata:
      labels: 
        *snip*
    spec:
      containers:
        - name: one-server
*snip*
```
garden.yaml
```
kind: Module
type: kubernetes
name: one-server-task

include:
  - "*"
files: 
  - deployment.yaml

serviceResource:
  kind: Deployment
  name: one-server-task

tasks:
  - name: one-migrate
    command: ['yarn']
    args: ['db:migrate']
    env:
      DD_SERVICE: "one.migration"

```

### Suggested solution(s)

Modify waitForResources() to not timeout with 0 replica deployments or avoid calling that function at all

https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/status/status.ts#L177

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
