### ISSUE TITLE
Ingress controller fails to deploy on KinD cluster

### ISSUE THREAD

**Issue by sbulman** [garden-io/garden#3436]
## Bug
I have created a multi-node KinD cluster using the following configuration

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      listenAddress: "127.0.0.1"
      protocol: TCP
  - role: worker
  - role: worker
  - role: worker
```

When I run garden deploy with `setupIngressController: nginx` the `ingress-nginx-controller` deployment fails with the following error

```
Deployment/ingress-nginx-controller: 0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 node(s) didn't match Pod's node 
affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```

I am using a ModuleTemplate for kubernetes. This is my templated ingress resource definition

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${inputs.name}-ingress
spec:
  ingressClassName: nginx
  rules:
   - host: ${inputs.ingressHost}
     http:
      paths:
       - path: ${inputs.ingressPath}
         pathType: Prefix
         backend:
          service:
           name: ${inputs.name}
           port:
            number: ${inputs.proxyHttpPort}
```

Any help would be much appreciated.

### Environment
macOS Catalina Version 10.15.7
kind v0.17.0 go1.19.2 darwin/amd64
garden version: 0.12.47

### Workaround
Its also worth mentioning that if I follow [these instructions](https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx) i.e.,

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```

and set `setupIngressController: null` in the `local-kubernetes` provider then things work for me.
