### ISSUE TITLE
[FEATURE]: Allow glob matching in the `files` directive of the Kubernetes module

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3465]
### Background / Motivation
Let's say I have the following project structure:

```
.
├── api
│   ├── garden.yml
│   ├── manifests
│   │   ├── Deployment.yaml
│   │   ├── Ingress.yaml
│   │   └── Service.yaml
│   └── src
└── project.garden.yml
```

If the API module has type `kubernetes` I want to be able to reference the manifests via glob matching as opposed to having to list all of them.

That is, this:

```yaml
kind: module
type: kubernetes
name: api
files: [./manifests/*]
```

as opposed to this:

```yaml
kind: module
type: kubernetes
name: api
files: [./manifests/Deployment.yaml, ./manifests/Ingress.yaml, ./manifests/Service.yaml]
```

### How important is this feature for you/your team?

:rose: It’s a nice to have, but nice things are nice :slightly_smiling_face:
