### ISSUE TITLE
Helm charts (almost) always re-deploy even when nothing has changed

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3473]
## Bug
I make use of a hefty Helm chart (CockroachDB's) inside a `helm` Garden module. Even when no values have been changed, on `garden deploy` it's very likely Garden will version and release a new chart to the cluster, which can take up to minutes. One of our community members also [experiences this bug](https://discord.com/channels/817392104711651328/1049847539039473747).

### Current Behavior
Here are two separate releases deployed to my cluster of the same chart. You can see one update can take up to 164 seconds so it's quite costly.

Nothing has changed in the chart or the values provided to the chart.

![2022-12-28!UNITO-UNDERSCORE!15h34!UNITO-UNDERSCORE!40](https://user-images.githubusercontent.com/59834693/210082813-14ba582e-9a9b-4760-825f-fe1b7add14f2.gif)

![2022-12-29!UNITO-UNDERSCORE!11h02!UNITO-UNDERSCORE!27](https://user-images.githubusercontent.com/59834693/210082815-1ff78be9-d3e1-468c-92fe-4b7a29395941.gif)

### Expected behavior
Charts should only cut a new release version when an input value has changed.

### Reproducible example
Use [my full-fat example](https://github.com/worldofgeese/flask-cockroachdb-devcontainer/tree/gardenify) with your own authenticated deployment registry defined.

### Workaround
None.

### Your environment

* **OS:** Windows 11 running WSL
* **How I'm running Kubernetes:** GKE Autopilot

`garden version`
0.12.48

**Comment by ashwiren** [comment]
My experience has been that this only seems to happen if there are garden variables as values in the helm chart values.

If you have a static values in the helm chart then there's no redeployment.

examples:
No redeployment
```
kind: Module
description: In-cluster Redis for glx-connect
type: helm
name: redis
chartPath: ./redis
values:
  architecture: 'standalone'
  auth:
    enabled: false
  master:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
```
Redeploys.
```
kind: Module
description: In-cluster PostgreSQL for Keycloak
disabled: ${var.keycloak.database.rds} # if rds is enabled, see infrastructure-aws
type: helm
name: keycloak-pg
chartPath: ./postgresql
dependencies: 
  - infrastructure-aws
values:
  architecture: 'standalone'
  auth:
    database: ${var.keycloak.database.name}
    username: ${var.keycloak.database.username}
    password: "${runtime.services.infrastructure-aws.outputs.keycloak_db_password}"
```
