### ISSUE TITLE
If a kubeconfig Garden depends on is generated by Terraform within the same environment, `garden delete environment` will hang forever

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3491]
### Current Behavior

Given the project-level config:
```yaml
  - name: kubernetes
    context: ${providers.terraform.outputs.cluster_name}
    kubeconfig: ${var.terraformInitRoot}/${providers.terraform.outputs.kubeconfig_path}
    namespace: ${environment.namespace}

  - name: terraform
    autoApply: "${environment.name == 'dev' ? true : false}"
    initRoot: "${var.terraformInitRoot}"
    allowDestroy: true
    variables:
      project_id: devrel-348008
      region: europe-north1
 ```

`garden delete environment` will hang forever at step `Cleaning up environments...`.

![2023-01-04_15h01_23](https://user-images.githubusercontent.com/59834693/210571479-b972c747-80d2-44ed-b34c-b162a111c3c9.gif)

### Expected behavior

All environments and resources contained within are cleanly deleted.

### Reproducible example

Have a look at my [Dev Container](https://github.com/worldofgeese/flask-cockroachdb-devcontainer/tree/gardenify) which can be run on any developer's machine provided they are running VS Code and have the [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension installed.

### Workaround

Killing the garden process.

### Your environment

* **OS:** Windows 11 running WSL 2
* **How I'm running Kubernetes:** GKE Autopilot 1.25

`garden version`
0.12.48
