### ISSUE TITLE
[FEATURE]: Helm module type must support Helm tests

### ISSUE THREAD

**Issue by bitpavel** [garden-io/garden#3504]
### Background / Motivation
Helm provides a standard approach for running tests: https://helm.sh/docs/topics/chart_tests/
But Helm module type doesn't have native support for this. Moreover, there's no way to run local scripts. 

A single workaround I found is adding `exec` module with `local` mode enabled. But in this case I must provide a different module name from the name used by the `helm` module. It isn't transparent for consumers of such a module. 
Also, I have to care about k8s namespace, helm release name by myself (taken from a ModuleTemplate, that's why we have here some weird constructions) :
```
  - type: exec
    name: ${replace("${parent.name}", "-tpl", "")}-helm
    description: Run Helm tests for ${replace("${parent.name}", "-tpl", "")}
    local: true
    include: # useless section, it's added here because it's required by exec module type
      - argo/config.yaml
    tests:
      - name: helm
        command:
          - /usr/local/bin/helm
          - test
          - <helm_release>
          - '-n'
          - garden-<namespace>
          - '--kube-context'
          - <context>
```

### What should the user be able to do?
Given: garden has <helm_module_name> module of a `helm` type, and the helm chart has resources with `test` hook. 
When: I run `garden test <helm_module_name>`.
Then: garden run `helm test` for the helm release managed by the module.

### Why do they want to do this? What problem does it solve?
Helm test is a standard way to define tests at helm charts. This handler may be used by garden and outside of garden, for example by CD pipeline. 

### Suggested Implementation(s)
I see at two main ways:
- provide a basic boolean parameter for `helm` module type, that allows to enable or disable helm test for the given module
- introduce `type` field for `tests` item that supports such modes:
  - `remote`: the current behaviour, has to be used by default for backward compatibility
  - `local`: allows running local commands (like it's done for `exec` module type). Overall, it's a universal mode that allows running any kind of task. Having such mode would allow me to find a graceful workaround without using `exec` module as I described above. 
  - `helm`: enables running helm tests

### How important is this feature for you/your team?
🌵 Not having this feature makes using Garden painful (because it's a standard feature of Helm charts and its absence is a significant limitation for the whole helm module)
