### ISSUE TITLE
[FEATURE]: Configure terraform backend options in terraform-plugin provider configuration

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3570]
## Feature Request

Ability to configure the terraform backend options in the terraform plugin's provider configuration block.

This is especially helpful if the terraform backend requires secrets, e.g.:

```
providers:
  - name: terraform
    backend-config:
      some_token: "${secrets.MY_SECRET}"
```

### Background / Motivation

Currently the terraform provider is hard to use in case a partial or dynamic backend config is needed. User Examples:
- using a different path for the terraform backend state file, depending on the Garden environment
- using garden secrets to access the terraform backend state file (e.g. block storage tokens)

### What should the user be able to do?

Configure parts of the terraform backend config in the terraform plugin provider config, e.g.

```
providers:
  - name: terraform
    backend-config:
      some_token: "${secrets.MY_SECRET}"
```

as described in https://developer.hashicorp.com/terraform/language/settings/backends/configuration#partial-configuration

### Why do they want to do this? What problem does it solve?

Makes it easier to use Garden with terraform in case a dynamic backend configuration is needed, e.g. see the following use cases:

- using a different path for the terraform backend state file, depending on the Garden environment
- using garden secrets to access the terraform backend state file (e.g. block storage tokens)

### Suggested Implementation(s)

Garden would need to pass the `-backend-config` parameter for this to work, as described here: https://developer.hashicorp.com/terraform/language/settings/backends/configuration#partial-configuration

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by stefreak** [comment]
Workaround until this feature is implemented:

At the moment, the only way to pass Garden secrets to the terraform backend configuration is using the Garden exec provider. Here’s an example for that:
providers:

```yaml
  - name: exec
    initScript: |
      sed "s/SOME_SECRET/${secrets.SOME_SECRET}/g" terraform/backend.tf.tpl > terraform/backend.tf
```

This assumes that you have a `terraform/backend.tf.tpl` with contents similar to this:

```hcl
terraform {
  backend "backend-provider" {
    config-option = "value"
    some_secret = "SOME_SECRET"
  }
}
```

When doing this, you should also create a `.gitignore` file in the terraform directory to prevent accidental commit of the secret to the source repository, which contains this line:

```console
backend.tf.tpl
```
