### ISSUE TITLE
BUG: Inconsistent behaviour variable precendence / merge behaviour

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#3592]
## Bug

According to https://docs.garden.io/using-garden/variables-and-templating#module-variables we have a clear variable precedence, but we also have some merge behaviour that we explain by linking to an RFC (Can we also have some examples?)

I find the behaviour strange when comparing it with the documentation. Also, we are merging variables in the varfile with project-level, but we are not merging variables in the module-level with project-level.

### Reproducible example

`project.garden.yml`
```yaml
kind: Project
name: incident-repro
variables:
  one:
    config:
      foo: foo
      bar: bar
environments:
  - name: plain
  - name: varfile
    varfile: varfile
  - name: varfile-yml
    varfile: varfile.yml
  - name: varfile-yml-obj
    varfile: varfile-obj.yml
  - name: varfile-yml-empty
    varfile: varfile-empty.yml
```

`varfile`
```yaml
one:
  config:
    foo: "bar2"
```

`varfile.yml`
```yaml
one:
  config:
    foo: "bar2"
```

`varfile-empty.yml`
```yaml
one:
  config:
```

`varfile-obj.yml`
```yaml
one:
  config: {}
```

`module.garden.yml`
```yaml
kind: Module
type: exec
name: vars
build:
  command: [echo, "${var.one.config.foo}", "${var.one.config.bar}"]
#variables:
#  one:
#    config:
#      bar: baz
`

### Current Behavior

```shell
% garden build -f -l3
ℹ vars                      → [echo]: foo bar
✔ vars                      → [echo]: foo bar → Done (took 0 sec)

% garden build -f --env varfile
Failed resolving one or more modules:

vars: Invalid template string (${var.one.config.foo}): Attempted to look up key "config" on a string.

% garden build -f --env varfile-yml -l3
ℹ vars                      → [echo]: bar2 bar
✔ vars                      → [echo]: bar2 bar → Done (took 0 sec)

% garden build -f --env varfile-yml-obj -l3|grep echo
ℹ vars                      → [echo]: foo bar
✔ vars                      → [echo]: foo bar → Done (took 0 sec)

% garden build -f --env varfile-yml-empty -l3
Failed resolving one or more modules:

vars: Invalid template string (${var.one.config.foo}): Attempted to look up key "foo" on a object.
```

when uncommenting the variables in `module.garden.yml`
```shell
% garden build -f -l3
ℹ graph                     → Resolving 1 modules...
Failed resolving one or more modules:

vars: Invalid template string (${var.one.config.foo}): Could not find key foo under var.one.config. Available keys: bar.
```

### Expected behavior

Clear and consistent variable precendence behaviour that can be explained in a few sentences

Especially if we allow merging objects in varfiles with project-level vars, I think we should also allow merge of varfiles with module-level vars.

### Your environment

`garden version` `0.12.48-edge-2d8bf03e5`
