### ISSUE TITLE
garden creates recursive directory structure on each run (.garden)

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#366]
When the module and project are on the same level it creates recursive copy inside `.garden`

Minimal config 

```
project:
  name: recursion
  environments:
    - name: local
      providers:
        - name: local-kubernetes


module:
  description: recursion bug
  name: recursion
  type: container
  hotReload:
    sync:
      - target: /app
  services:
    - name: minimal
      ports:
        - name: http
          containerPort: 80
      ingresses:
        - path: /
          port: http
```

To reproduce run the following 
   
      garden dev 
      # wait for it to finish
      ctrl +c # stop the running command
      garden dev 
      # .... n times it gets deeper 

```
.garden
        ├── build
        │   └── recursion
        │       ├── .garden
        │       │   ├── build
        │       │   │   └── recursion
        │       │   │       ├── .garden
        │       │   │       │   ├── build
        │       │   │       │   │   └── recursion
        │       │   │       │   ├── local-config.yml
        │       │   │       │   └── logs
        │       │   │       │       ├── development.log
        │       │   │       │       └── error.log
```

See example project here for reproduce-able setup https://gist.github.com/drubin/d9af0fefd46bc577ca047cb44d313283/edit
