### ISSUE TITLE
Lower case env variables are not supported

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#369]
`Error validating module website: key "a_a_a" is not allowed at path .services[0][env][a_a_a]`

```
module:
  description: Minimal Gatsby example
  name: website
  type: container
  hotReload:
    sync:
      - target: /app/src/
        source: src
  services:
    - name: website
      command: [ls, /app/src]
      hotReloadCommand: [npm, run, develop]
      env:
        GATSBY_WEBPACK_PUBLICPATH: /
        a_a_a: bbb
        #GATSBY_WEBPACK_PUBLICPATH: http://gats.local.app.garden/
      ports:
        - name: http
          containerPort: 8000
      ingresses:
        - path: /
          port: http
```

Changing the blow key to `A_A_A: bbb` works
