### ISSUE TITLE
[FEATURE]: extend templated module context

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#3763]
## Feature Request

We should extend the available templates in the templated module context. Currently, users can only use `command`, `datetime`, 
`git`, `local`, `project`, `secrets`, `var` and `variable` and it would be useful to extend this list with most, if not all the keys generally available for Modules. See module docs [here](https://docs.garden.io/reference/template-strings/modules).

### Background / Motivation
A user tried to configure a templated module as below:

```yaml
kind: Module
type: templated
template: my-module-template
name: my-module
disabled: ${environment.name != 'dev'}
```
Garden fails with the following error:
```
Invalid template string (${environment.name != 'dev'}): Could not find key environment. Available keys: command, datetime, 
git, local, project, secrets, var and variables.
```

Additionally, we should state in the docs that the context for templated modules is limited compared to "normal" modules, in order to avoid confusion. In particular, [this section](https://docs.garden.io/using-garden/module-templates#defining-modules) is misleading.

### What should the user be able to do?

Our users should be able to use the keys specified in the [docs](https://docs.garden.io/reference/template-strings/modules).

### Why do they want to do this? What problem does it solve?

Expanding the list of available keys will allow our users to create more complex templates.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by tedchang77** [comment]
this is also affecting us.  our use case is the same as the example given where we need to conditionally disable the module based on the environment.

**Comment by shumailxyz** [comment]
With the release of Bonsai, this has already been addressed and additional templating context like `disabled: ${environment.name != 'dev'}` works.

**Comment by ishantagarwal-x213235** [comment]
I got this issue again in Bonsai version. here is the reference that will help you to reproduce this issue

https://github.com/ishantagarwal-x213235/garden-sample-project/blob/main/spring-boot/spring-boot.garden.yml#L5

**Comment by vvagaytsev** [comment]
This might be related to #4830

**Comment by Orzelius** [comment]
Additional template keys are available for use in both render definitions for inputs and templates themselves for actions.

I'm closing this as complete.

@ishantagarwal-x213235 Templated modules (in 0.13 renamed to `RenderTemplate`) don't have a`disabled` field. If you want to conditionally disable actions/modules that are coming from templates you should pass disabled as an input and later use in your templates like this:

## New syntax

```yaml
kind: RenderTemplate
template: template
name: name
inputs:
  disabled: ${environment.name != 'dev'}
---
kind: ConfigTemplate
name: k8s-container
inputsSchemaPath: schema.json

configs:
  - kind: Build
    type: container
    name: ${parent.name}  # Now possible as it doesn't conflict with the RenderTemplate type
    disabled: ${inputs.disabled}
```

## Old syntax

```yaml
kind: Module
type: templated
template: template
name: name
inputs:
  disabled: ${environment.name != 'dev'} 
---
kind: ModuleTemplate
name: template

modules:
  - type: type
    name: ${parent.name}-something
    disabled: ${inputs.disabled}
```

**Comment by ishantagarwal-x213235** [comment]
@Orzelius It is working when you have small project while it's not working when you have big project.
Our project is having a 170 modules and it stopped working when i made changes. Garden is not able to scan those modules having these definition.

**Comment by Orzelius** [comment]
@ishantagarwal-x213235 Is the error the same? Are you on 0.13? It's hard to figure this out without extra details.

cc @vvagaytsev, somebody has to take this over from me.

**Comment by ishantagarwal-x213235** [comment]
@Orzelius I am talking about using the new Templated modules (in 0.13 renamed to RenderTemplate). When applying the below changes in big project(having 170 modules), we got the below error

```
Could not find one or more Deploy actions: x-service
```

Use the template like this

```
kind: RenderTemplate
template: template
name: x-service

---
kind: ConfigTemplate
name: spring-service-module-template
inputsSchemaPath: schema.json

configs:
  - type: pulumi
    name: ${parent.name}-service
```

Please note that it is working when you have few modules in project but stopped working in case of big project.
