### ISSUE TITLE
Templating in kubernetes manifest does not fail if variable does not exists

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3867]
### Current Behavior

When templating a non-existent garden variable into a kubernetes manifest file, the whole templating process does not fail.

```
# File: module.garden.yml
kind: Module
type: kubernetes
name: foo
files:
  - manifest.yml

# File: manifest.yml
apiVersion: v1
kind: Service
metadata:
  name: ${var.bar}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: ${this.name}
```

In the example, `var.bar` is not defined.
When deploying the module via `garden deploy`, the process suceeds.
The following kubernetes resource is applied to the cluster:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    baz: ${var.bar}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: foo
```

### Expected behavior

The templating should fail, since `var.bar` is not set.
This behavior makes kubernetes modules quite error-prone.
In fact it had happened multiple times that a kubernetes environment variable has not been properly replaced, leading to a production incident.

### Suggested solution(s)

It could probably be necessary to introduce an escape mechanism in order to keep the literal value.

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.12.52
