### ISSUE TITLE
Implicit dependency not detected in kubernetes manifest files

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3871]
### Current Behavior

When using a variable from another module `foo` inside an kubernetes manifest file of a kubernetes module `bar`, `bar` does not seem to implicitly depend on `foo`. When `foo` already depends on `bar`, this results in an undetected circular dependency.

```
# File: module.garden.yml
kind: Module
type: kubernetes
name: bar
files:
  - manifest.yml

# File: manifest.yml
apiVersion: v1
kind: Service
metadata:
  name: ${modules.foo.var.baz}
spec:
  ...
```

Undetected circular dependencies cause flaky, hard to detect bugs in template rendering.

### Expected behavior

`bar` should implicitly depend on `foo`, leading to the detection of the circular dependency.
### Workaround

Don't reference other modules in kubernetes manifest files. Instead use them indirectly:

```
# File: module.garden.yml
kind: Module
type: kubernetes
name: bar
variables:
  baz: ${modules.foo.var.baz}
files:
  - manifest.yml

# File: manifest.yml
apiVersion: v1
kind: Service
metadata:
  name: ${var.baz}
spec:
  ...
```

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.12.52

**Comment by vvagaytsev** [comment]
@thsig @edvald should a variable reference create a dependency between modules?

**Comment by edvald** [comment]
That's actually not an implicit behavior for modules. However, the new action config format in 0.13 does introduce that, since I feel that's indeed the expected behavior.

So I don't expect we'll address that for modules, and for now you need to list the referenced module explicitly as a dependency.

**Comment by hnicke** [comment]
Somehow I was sure implicit dependencies are automatically created. I must have mixed this up then.
In case you know pulumi: I kind of expected it to work like dependencies for pulumi Outputs.

However some sort of circular dependency checking seems to exists.
Let's look at the following two modules which reference each other's variables:
```yml
# file: example.garden.yml
kind: Module
type: kubernetes
name: foo
variables:
  my-var: x
  foreign-var: ${modules.bar.var.my-var}

---

kind: Module
type: kubernetes
name: bar
variables:
  my-var: x
  foreign-var: ${modules.foo.var.my-var}
```

Let's validate the stack:
```
$ garden validate
...
  graph                     → Resolving 46 modules...
Detected circular dependencies between module configurations:

foo <- bar <- foo
```

As expected, the circular dependency is properly detected.

Let's move `foo`'s variable `foreign-var` into a manifest file:
```
# file: example.garden.yml
kind: Module
type: kubernetes
name: foo
variables:
  my-var: x
files:
  - manifest.yml

---

kind: Module
type: kubernetes
name: bar
variables:
  my-var: x
  foreign-var: ${modules.foo.var.my-var}


# file: manifest.yml
foreign-var: ${modules.bar.var.my-var}
```

Let's validate the stack once more:
```
$ garden validate
...
  graph                     → Resolving 46 modules... → Done

OK
```

I expect the validation to fail, just like in the first example.
This issue might be related to #3867.
