### ISSUE TITLE
Templating custom arguments in custom commands fails when using if/else statement

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#3897]
### Current Behavior

Consider the custom commands `start-dev-if` and `start-dev-ternary`.

```
kind: Command
name: start-dev-if
description:
  short: deploy api and frontend
args:
  - name: with
    description: Additional services to deploy
    type: string
gardenCommand:
  - deploy
  - ${if args.with}${args.with},${endif}api,frontend
  - $concat: ${args.$rest} # Allow any arguments/options on top of the fixed ones above
---

kind: Command
name: start-dev-ternary
description:
  short: deploy api and frontend
args:
  - name: with
    description: Additional services to deploy
    type: string
gardenCommand:
  - deploy
  - ${args.with ? concat(args.with, ","):""}api,frontend
  - $concat: ${args.$rest} # Allow any arguments/options on top of the fixed ones above
```

Both define the same custom command and use an additional custom argument `with`. While `start-dev-ternary` works, `start-dev-if` fails when run when not providing a value for `with`.

```
[2023-03-07T09:54:25.870Z] Error: Invalid template string (${if args.with}${args.with},${endi…): Could not find key with under args. Available keys: $all, $rest, -- and with.
    at resolveTemplateString (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/template-string/template-string.ts:200:11)
    at $resolveTemplateStrings (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/template-string/template-string.ts:215:15)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:191:20
    at $resolveTemplateStrings (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/template-string/template-string.ts:252:43)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:191:20
    at CustomCommandWrapper.action (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/commands/custom.ts:165:39)
    at GardenCli.runCommand (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/cli/cli.ts:535:34)
    at GardenCli.run (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/cli/cli.ts:694:26)
    at Object.runCli (/snapshot/project/tmp/pkg/cli/src/cli.ts:41:14)

Error Details:

err:
  detail:
    text: '${if args.with}'
  type: template-string
 ```

### Expected behavior

Ternary expression and if/else should behave in the same way here. The if statement should work.

### Reproducible example

See custom commands above.

### Workaround

Use ternary.

### Your environment

* **OS:** MacOS Monterey 12.6
* **How I'm running Kubernetes:** AWS EKS

`garden version` 0.12.52
