### ISSUE TITLE
Deploying Helm charts that use strict value validation breaks with Garden

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#3962]
### Current Behavior

It is not possible to install helm charts with Garden that use strict values validation via a values.schema.json that include the `additionalProperties: false` stanza. For an overview of json schema validation for helm values see [here](https://helm.sh/docs/topics/charts/#schema-files).
Garden adds custom values to a chart deployed with Garden to add some metadata to the helm release. This is an example of a values file that Garden produces:

```
service:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
.garden:
  moduleName: istio-gateway
  projectName: istio-example
  version: v-5f013b4127
```

When `additionalProperties: false` is set in the values.schema.json of a chart the deploy will fail with following error:

```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
gateway:
- (root): Additional property .garden is not allowed
```
### Expected behavior

Garden deploys the helm chart.

### Reproducible example

Deploy the istio gateway Helm Chart with Garden e.g.:

```
kind: Deploy
name: istio-gateway
description: Install istio gateway helm chart
type: helm
spec:
  chart:
    name: gateway
    version: 1.17.1
    repo: https://istio-release.storage.googleapis.com/charts
```

### Workaround

If you maintain the chart, consider setting `additionalProperties: true` in the validation schema. If it is a public chart the only way to install it is to download it and store it locally and set `additionalProperties: true`.
There is an open issue in Helm like https://github.com/helm/helm/issues/10398 to override  the validation client-side.

### Suggested solution(s)

Store the Garden related metadata in a configmap or secret in the same namespace similar to test results instead of Helm values.

### Additional context

If you run into this error please give the issue a thumbsup, currently we only saw this with the istio chart.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by worldofgeese** [comment]
A community member was bitten by this bug just now when attempting to deploy `jupyterhub/jupyterhub`. I have validated this bug myself using the following action provided by the community member:

```yaml
kind: Deploy
type: helm
name: platformhub-helm
spec:
  releaseName: jupyterhub
  namespace: jupyterhub
  chart:
    repo: https://jupyterhub.github.io/helm-chart/
    name: jupyterhub
    version: "1.2.0"
```

The Discord forum post is available [here](https://discord.com/channels/817392104711651328/1131951332643840000/1131951332643840000).
