### ISSUE TITLE
Allow service port definition to differ from container port

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#400]
## Problem 

A very common usecase is the container to listen on a none privliged port i.e 8080 but have the service connect to `http://user/` this is achived by port mapping in both kubernetes and docker-compose. 

Our default option of defaulting to the container port is a great default but pretty limiting when you are working with pre-built containers/modules and pre-built code that makes assumptions.

### Introduce `servicePort`
Possible solution

```
ports: 
        #
        # Required.
        - # The name of the port (used when referencing the port elsewhere in the service
          # configuration).
          #
          # Required.
          name:
​
          # The port number on the container defaults to the service endpoint's port
          #
          # Required.
          containerPort:

          # The port number on the service defaults to `containerPort`
          #
          # optional 
          servicePort:
​
```

### Mapping values 

Use a similar syntax to docker and docker-compose where you map a port. 

ie `docker run -p 8080:9090` 

```
ports: 
        #
        # Required.
        - # The name of the port (used when referencing the port elsewhere in the service
          # configuration).
          #
          # Required.
          name:
​
          # The port number on the container defaults to the service endpoint's port
          #
          # Required.
          containerPort:  "80:9090"

          # The port number on the service defaults to `containerPort`
          #
          # optional 
          servicePort:
​
```

My personal preference is for option of introducing a `servicePort`
