### ISSUE TITLE
0.13: [Bug]: Error converting exec module to Build action

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4055]
### Current Behavior

When converting an 0.12 exec module to Bonsai, the following error occurs when running `garden build`:

```shell
ℹ build.get-kubeconfig [debug] → Syncing 0 files from go to .garden/build/get-kubeconfig (and removing any extraneous files)
ℹ build.get-kubeconfig [verbose] → Done syncing sources (took 0 sec)
ℹ build.get-kubeconfig [debug] → Running command: kubectl config view --minify --output jsonpath="{.clusters[*].cluster.server}" | tee .defaultApiserverEndpoint
✖ build.get-kubeconfig      → Build failed (in 0.1 sec)
✖ build.get-kubeconfig      →
Failed processing Build type=exec name=get-kubeconfig. Here is the output:
────────────────────────────────────────────────────────────────────────────────
Command "kubectl config view --minify --output jsonpath="{.clusters[*].cluster.server}" | tee .defaultApiserverEndpoint" failed with code ENOENT:
──────────────────────────────────────────────────────────────────────────────── (in 0.1 sec)
ℹ [debug] Done flushing all events and log entries.
✖ 1 deploy action(s) failed!
```

### Reproducible example

```yaml
kind: Build
type: exec
name: get-kubeconfig
description: Determine kubernetes endpoint url
spec:
  command:  # warning, garden.io behaves very oddly (concats command's items and runs that with sh -c)
    - kubectl config view --minify --output jsonpath="{.clusters[*].cluster.server}" | tee .defaultApiserverEndpoint
include: []
```

This issue is submitted on behalf of Axoflow's  @pepov. @worldofgeese has reproduced this error.

### Your environment
* **How I'm running Kubernetes:** minikube

`garden version` 0.13.0
