### ISSUE TITLE
[FEATURE]: Get array/object of all modules when using ${modules} key in template strings

### ISSUE THREAD

**Issue by dawidstezycki** [garden-io/garden#4063]
### Background / Motivation

I was working on HorizontalPodAutoscale and wanted to create one for each of our services but I wanted to use $forEach functionality to create them dynamically. Unfortunately, I couldn't find a way to iterate over all modules out-of-the-box, so I had to manually list them which is obviously something that would need to be maintained over time if we wanted to add more modules.
```
kind: Module
type: kubernetes
name: horizontal-autoscalers
manifests:
  $forEach: ${modules} ## I would like this to be equivalent to ${[modules.module1, modules.module2]}
  $filter: ${item.value.var contains "horizontalAutoscalerConfig"}
  $return:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${item.value.name}
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ${item.value.name}
      minReplicas: ${item.value.var.horizontalAutoscalerConfig.minReplicas}
      maxReplicas: ${item.value.var.horizontalAutoscalerConfig.maxReplicas}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: ${item.value.var.horizontalAutoscalerConfig.targetCpuUtilizationPercentage}
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 120
```
### What should the user be able to do?

I would like to be able to access all the modules as an iterable array or object since the format that lets you access them separately `${modules.module1}` is already suggesting that `${modules}` will just output all of them.

### Why do they want to do this? What problem does it solve?

It allows to avoid repetition when defining resources that are inherently designed to be associated with modules in one-to-one relationship.

### Suggested Implementation(s)

Like described above:
```
  $forEach: ${modules} ## I would like this to be equivalent to ${[modules.module1, modules.module2]}
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
