### ISSUE TITLE
Garden dev stopped working

### ISSUE THREAD

**Issue by fabianboerner** [garden-io/garden#4152]
### Current Behavior

Garden dev says "no enabled modules found in project"

### Expected behavior

Development is deployed in dev mode to kubernetes cluster

### Reproducible example

Project root: garden.project.yml
Subfolder: /module/submodule1/garden.yml

### Your environment

* **OS:** Ubuntu 14.04
* **How I'm running Kubernetes:** Digitalocean

`garden version`: 0.12.55

Log:

````
Dev 

[debug] Initializing Garden Cloud API client.
[debug] No auth token found, proceeding without access to Cloud Dashboard. Command results for this command run will not be available in Cloud Dashboard.
ℹ garden                    → Running in namespace xxx in environment dev
ℹ garden                    → Garden dashboard running at http://localhost:9777?key=xxx
[debug] Scanning project root at /home/xxx/xxx/xxx
→ Includes: **/*garden.y*ml
→ Excludes: xxx/**/*,xxx/**/*,v/**/*,utils/**/*,a/**/*,b/**/*,xxx/**/*,xxx/**/*,.garden/**/*,.git,.gitmodules,.garden/**/*,debug-info*/**
[debug] Found 0 files in project root /home/xxx/xxx/xxx
ℹ providers                 → Getting status...
ℹ providers [debug]         → Kubernetes: Getting API resource info for group networking.k8s.io/v1
ℹ garden system [debug]     → Initializing...
ℹ providers [debug]         → Kubernetes: Getting API resource info for group v1
ℹ providers [debug]         → Getting currently deployed resource statuses...
ℹ providers [debug]         → Comparing expected and deployed resources...
ℹ providers [debug]         → All resources match.
ℹ providers                 → Getting status...
✔ providers                 → Getting status... → Cached
ℹ providers                 → Run with --force-refresh to force a refresh of provider statuses.
ℹ garden system [debug]     → Scanning project root at /home/xxx/.garden/bin/static/kubernetes/system
→ Includes: **/*garden.y*ml
→ Excludes: ../../../../../xxx/xxx/.garden/kubernetes.garden/**/*,.git,.gitmodules,.garden/**/*,debug-info*/**
ℹ garden system [debug]     → Found 11 files in project root /home/xxx/.garden/bin/static/kubernetes/system
ℹ graph                     → Resolving 11 modules...
✔ graph                     → Resolving 11 modules... → Done
ℹ providers [debug]         → Upserting Secret garden-system/regcred
ℹ providers [debug]         → Replaced Secret garden-system/regcred
ℹ providers [debug]         → Kubernetes: Getting API resource info for group apps/v1
ℹ providers [debug]         → Getting currently deployed resource statuses...
ℹ providers [debug]         → Comparing expected and deployed resources...
ℹ providers [debug]         → All resources match.
✔ garden system [debug]     → Initializing...
✔ providers                 → Getting status... → Done
ℹ graph                     → Resolving 0 modules...
✔ graph                     → Resolving 0 modules... → Done

No enabled modules found in project.
Aborting...
[debug] Done flushing all events and log entries.
[debug] Done flushing all events and log entries.
````
Command executed:
 garden --force-refresh --hot=* --log-level=4 --env dev dev

Module definitions are there!

Project YAML
````
providers:
  - name: kubernetes
    namespace: ${var.namespace}
    environments: [dev, staging]
    buildMode: cluster-buildkit
    resources:
      builder:
        limits:
          memory: 8192
          cpu: 4000
    context: xxx
    defaultHostname: ${var.defaultHostname}
    setupIngressController: nginx
    deploymentRegistry:
      hostname: breitseite.azurecr.io
      namespace: "${local.env.BASE_SUBDOMAIN}?${local.env.BASE_SUBDOMAIN ? '-' : ''}${local.env.BASE_DOMAIN}"
    imagePullSecrets:
      - name: regcred
        namespace: default
    tlsCertificates:
      - name: ${var.certificateSecretRefName}
        secretRef:
          name: ${var.certificateSecretRefName}
````
