### ISSUE TITLE
Boolean variables not comparing correctly in string templates

### ISSUE THREAD

**Issue by marklester** [garden-io/garden#4174]
### Current Behavior

Given:

```
kind: Module
description: run hello world
type: exec
name: var-bug
variables:
  booltest: true
tasks:
  - name: varbug-echo
    command: ["echo", "${var.booltest ? 'true':'false'}"]
```

```
garden run task varbug-echo --var booltest=false
Task output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
true
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Expected behavior

I would expect this to return false

### Workaround

The workaround I am currently using is to treat all variables as strings

### Your environment

* **OS:** VERSION="18.04.6 LTS (Bionic Beaver)"
* **How I'm running Kubernetes:** kind version 0.17.0

`garden version`
0.12.53
