### ISSUE TITLE
Add a get tasks command

### ISSUE THREAD

**Issue by thsig** [garden-io/garden#420]
We should add a `description` field to task definitions, and a `get tasks` command that outputs a project-wide list of all tasks (and their descriptions).

The output could look something like this:
```yaml
some-module:
  migrate-db:
    description: Migrate the DB to the latest version. Idempotent.
    command: ...
  download-dev-db:
    description: Download the latest internal dataset to populate your local dev database.
    command: ...
some-other-module:
  ...
```
