### ISSUE TITLE
0.13: [Bug]: build times cumulative

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4212]
### Current Behavior

Build times are cumulative. If build of `test2` depends on `test1`, build time of `test2` will be the build time of `test1 + test2`.

0.13 output:
```
steffen@Steffens-MBP repro % gdev build test2
Build 🔨

ℹ garden               → Running in Garden environment default.default
ℹ providers            → Getting status...
✔ providers            → Cached (in 0.3 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (in 0 sec)
✔ build.test1          → Done (in 2 sec)
✔ build.test2          → Done (in 4.1 sec)

Done! ✔️
```

### Expected behavior

I expect that Garden starts counting build time when all dependencies have completed and the build starts. Otherwise it is hard to tell where to optimize if one wants to improve the overall build time.

0.12 output:
```
steffen@Steffens-MBP repro % garden build test2
Build 🔨

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌍  Running in namespace default in environment default
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.
✔ graph                     → Resolving 2 modules... → Done
✔ test1                     → Building version v-31a5e07448... → Done (took 2.1 sec)
✔ test2                     → Building version v-5ee10df664... → Done (took 2.1 sec)

Done! ✔️
```

### Reproducible example

```
kind: Project
name: repro
environments:
 - name: default
providers:
 - name: exec

---

kind: Module
type: exec
name: test1
include: []
build:
 command: [sleep, "2"]

---
kind: Module
type: exec
name: test2
include: []
build:
 dependencies: [test1]
 command: [sleep, "2"]
```

### Workaround

Unknown

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
