### ISSUE TITLE
[FEATURE]: Garden should have a option for choosing tag on `garden deploy`

### ISSUE THREAD

**Issue by BillRamsey-minted** [garden-io/garden#4386]
## Feature Request

Garden should have an option for choosing a tag on `garden deploy`

### Background / Motivation

Garden has a --tag for publish.  Which, although I have (other) issues with, seems like a great feature.  The problem I have is that `garden deploy` does not have a --tag for deploying. 

### What should the user be able to do?

In our CI/CD, we want to create an artifact for deploying to test.  Therefore, we do something like this:

`garden publish --tag 'release-candidate-20230522'`

Later, when deploying to prod, I want to deploy this specific image to prod after it has been tested in QA.

### Why do they want to do this? What problem does it solve?

I have some sneaky code to try to replicate it with a var:

```
dockerfile: "${var contains 'image_tag' ? null : './services/go-service/${var.dockerfile}'}"
image: "${var contains 'image_tag' ? '${var.docker-registry}/${project.name}/${this.name}:${var.image_tag}?' : null}"
```

so for example, if you want to deploy a specific image, you would include:
`garden deploy --var image_tag=release-1234`

however, even this doesn't work, as garden explicitly tries to find a dockerfile to use, even if you've set dockerfile to null.

So the only solution is to find all Dockerfiles in the repo, and delete them (which then tweaks the build id)

### Suggested Implementation(s)

I think the best solution is to have a `--tag` argument.  Changing behavior to not find a dockerfile even when image is specified could break some users workflows.  But having a `--tag` argument would allow one to over-ride the default behavior and even make `garden publish` more useful

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

We have a work-around, but its painful, and finding and deleting the dockerfile certainly feels like a hacky work-around.

**Comment by stefreak** [comment]
Thank you for reporting this @BillRamsey-minted. I like this idea and we have a similar workflow internally. It would be nice if this workflow was more natively supported in garden 👍

**Comment by shumailxyz** [comment]
Thank you for reporting this @BillRamsey-minted. 

This should be already supported in Bonsai as Build and Deploys are separate actions that can be configured independently. 

For example, here's example config for `build` and `deploy` actions for a frontend service.

```yaml
kind: Build
name: frontend
description: frontend image
type: container

---
kind: Deploy
name: frontend-service
description: frontend service container
type: container
dependencies:
  - deploy.backend

build: "${var.image_tag ? null : 'frontend'}?" # rely on build action and use latest build if no image_tag is specified

spec:
  image: "${command.params contains 'var' && (command.params.var[0] contains 'image_tag') ? 'frontend:${var.image_tag}' : null}"
  ports:
    - name: http
      containerPort: 3000
  ingresses:
    - path: /
      port: http

---
```

With above config, it should be possible to run `garden build` to build the image, `garden publish` to publish the image with specific tag. Afterwards, you could deploy the specific tag using  `var` to pass `image_tag`. e.g. 

`garden deploy frontend-service --var image_tag=<tag>`.

To simplify these operations even further, you can leverage [custom commands](https://docs.garden.io/advanced/custom-commands) by encapsulating the build and deploy functionalities as custom garden commands.

It's important to note that the `deploy` command is designed to be versatile and not limited to containers or Kubernetes. It can be used for various workflows such as executing scripts, using Terraform, Pulumi, and more. Considering this flexibility, introducing a `tag` option at the command level may not align with the command's semantics, as it would only be relevant for specific use cases. Additionally, deploy command is also supposed to work without specifying deployment names and that leads to more questions about what the tag should apply to and so on.

I would suggest trying this out with Bonsai and action configs, and let us know if that resolves the issue.
