### ISSUE TITLE
Ports in Service definition don't behave as expected

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#441]
### Current Behavior

Using an example project and appending a "debug port" as either a `hostPort` or `nodePort` doesn't work as expected.

We create a single service of type `clusterIP` a service can't be both a `nodePort` and `clusterIP`

### Expected behavior

I expect us to be able to create nodePorts or hostPorts

### Reproducible example

```yaml
 ports:
    - name: http
        containerPort: 5001
    - name: debug
        containerPort: 9229
        hostPort: 9229
    # Public exposed endpoints via the lb
    ingresses:
    - path: /
        port: http
```

k8s definition 
```
k get services end-user
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
end-user   ClusterIP   10.102.131.10   <none>        5001/TCP,9229/TCP   17m
```

### Suggested solution(s)

Maybe we need to create 2 different services for each type?  Or at least create a 2nd one for nodePorts or hostports

`end-user:5001 and 9229` both ports exposed on clusterIP
`end-user-nodeport:9229` only port as nodePort exposed.

### Your environment

`garden -v
0.8.1
`

`kubectl version` na

`docker version` na
