### ISSUE TITLE
0.13: [Bug]: Pulumi module with dependencies does not validate

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4468]
### Current Behavior

Using 0.13.0
```
steffen@MacBook-Pro repro2 % garden validate
Validate ✔️

[...]

foo: Error validating Module 'foo': key "dependencies" is not allowed at path [dependencies], key "build" is not allowed at path [build]. Available keys: allowDestroy, autoApply, createStack, root, pulumiVariables, pulumiVarfiles, orgName, cacheStatus, stackReferences, deployFromPreview, stack)
```

### Expected behavior

Using 0.12.56

```
steffen@MacBook-Pro repro2 % garden validate
Validate ✔️

[...]

OK ✔️
```

### Reproducible example

```
kind: Project
apiVersion: garden.io/v0
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes
 - name: pulumi

---

kind: Module
type: pulumi
name: foo
stack: "${environment.name}"

createStack: true
cacheStatus: false
allowDestroy: true
autoApply: true
deployFromPreview: false
dependencies:
  - baz

pulumiVarfiles:
  - "../global.yaml"
  - "config/common.yaml"
  - "config/${environment.name}.yaml"
build:
  dependencies:
    - bar

include: []

---
kind: Module
type: exec
name: bar
include: []

---
kind: Module
type: exec
name: baz
tasks:
  - name: baz
    command: [echo]
include: []
```

### Workaround

Workaround unknown so far, other than using Garden 0.12

### Suggested solution(s)

TBD

### Additional context

–

### Your environment

* **OS:** macOs
* **How I'm running Kubernetes:** Docker Desktop

`garden version` 0.13.0
