### ISSUE TITLE
0.13: [Bug]: deploy.kubernetes: Confusing error message when file is not a valid path

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4499]
## Garden Bonsai (0.13) Bug

When file list includes a URL, instead of a path, the error message is extremely confusing

### Current Behavior

```
Error processing config for Deploy action test:
Error validating configure handler output from provider local-kubernetes for Deploy type kubernetes: key .config does not match any of the allowed types. Available keys: config, supportedModes)
```

### Expected behavior

I would expect an error message that actually points me to the right direction and tells me what's wrong:
```
Error processing config for Deploy action test:
Error validating Deploy type=kubernetes name=test: file "https://..." could not be found
```

### Reproducible example

```
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes

---

kind: Deploy
type: kubernetes
name: test
spec:
  files:
    - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/grafana-dashboardSources.yaml
```

### Workaround

–

### Suggested solution(s)

–

### Additional context

–

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** docker desktop

`garden version` 0.13.0
