### ISSUE TITLE
0.13: [Bug]: Terraform module with dependencies does not validate

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4508]
This is essentially a copy of https://github.com/garden-io/garden/issues/4468 but for Terraform instead of Pulumi.

Reproducible with `garden/plugins/terraform/test/test-project-module/` and running `garden validate` on `0.13`.

```yaml
kind: Project
name: terraform-provider
environments:
  - name: local
providers:
  - name: terraform
    variables:
      my-variable: base
variables:
  workspace: default
---
kind: Module
type: terraform
name: tf
include: ["*"]
autoApply: true
root: ./tf
workspace: ${var.workspace}
variables:
  my-variable: foo
---
kind: Module
type: exec
name: test
include: ["*"]
tasks:
  - name: test-task
    dependencies: [tf]
    command: ["echo", "${runtime.services.tf.outputs.my-output}"]

```

```
gdev validate
Validate ✔️

"apiVersion" is missing in the Project config. Assuming "garden.io/v0" for backwards compatibility with 0.12. The "apiVersion"-field is mandatory when using the new action Kind-configs. A detailed migration guide is available at https://docs.garden.io/tutorials/migrating-to-bonsai
ℹ garden               → Running in Garden environment local.default
ℹ providers            → Getting status...
✔ providers            → Cached (took 0.3 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0 sec)
✖ deploy.tf            → Failed processing resolve Deploy type=terraform name=tf (from module tf) (took 0.01 sec). Here is the output:

────────────────────────────────────────────────────────────────────────────────
Error validating spec for Deploy type=terraform name=tf (from module tf): key "build" is not allowed at path [build], key "dependencies" is not allowed at path [dependencies]. Available keys: allowDestroy, autoApply, root, variables, version, workspace)
────────────────────────────────────────────────────────────────────────────────
Failed to resolve Deploy type=terraform name=tf (from module tf): Error: resolve Deploy type=terraform name=tf (from module tf) failed: Error: Error validating spec for Deploy type=terraform name=tf (from module tf): key "build" is not allowed at path [build], key "dependencies" is not allowed at path [dependencies]. Available keys: allowDestroy, autoApply, root, variables, version, workspace)
```
