### ISSUE TITLE
0.13: [Bug]: Module conversion validation error when using `build` in module service spec

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4573]
### Current Behavior

```
% garden validate
[..]
✖ deploy.solr          → Failed processing resolve Deploy type=container name=solr (from module solr) (took 0.04 sec). Here is the output:

[..]

Failed to resolve Deploy type=container name=solr (from module solr): Error: resolve Deploy type=container name=solr (from module solr) failed: Error: Error validating spec for Deploy type=container name=solr (from module solr): key "build" is not allowed at path [build]. Available keys: command, args, env, cpu, memory, volumes, privileged, addCapabilities, dropCapabilities, tty, deploymentStrategy, annotations, daemon, sync, localMode, image, ingresses, healthCheck, hotReload, timeout, limits, ports, replicas)
```

### Expected behavior

0.12 behaviour:
```
% garden validate
[..]
OK ✔️
```

### Reproducible example
```
kind: Project
apiVersion: garden.io/v0
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes
---

kind: Module
description: solr
type: container
name: solr
exclude: [.garden, .dockerignore, .gardenignore, fixture.garden.yml, commands.garden.yml]
dockerfile: Dockerfile
services:
  - name: solr
    build:
      targetImage: solr
    env:
      SOLR_HOST: localhost
      SOLR_PORT: 8983
    ports:
      - name: http
        containerPort: 8983
        servicePort: 8983
```
### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** docker desktop

`garden version`
