### ISSUE TITLE
0.13: [Bug]: Cyclic dependency when using different build target based on deploy mode

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4603]
## Garden Bonsai (0.13) Bug

When using "sync" deploy mode it is necessary for compiled languages to use a different build target, because you need the tools to compile the code which you don't need without sync mode.

### Current Behavior
```
Cyclic dependency, node was:"Deploy.limiter"
```

### Expected behavior

I'd like an easy way of doing this without an error as it's a quite common use case.

### Reproducible example

```
kind: Build
type: container
name: myservice
spec:
  dockerfile: Dockerfile
  targetStage: "${actions.deploy.myservice.mode == 'sync' && 'dev' || 'prod'}"

---

kind: Deploy
type: container
name: myservice
build: myservice
spec:
  sync:
    command: [air]
    paths:
      - target: /app
        source: .
        mode: one-way-replica
        exclude: []
  ports:
    - name: http
      containerPort: 8080
      servicePort: 80
  ingresses:
    - path: /
      port: http
      hostname: myservice.${var.base-hostname}
```

### Workaround

Something like 

```
${command.params contains 'sync' || isEmpty(command.params.sync)}
```
can be used as a workaround.

### Suggested solution(s)

Not sure how to solve this in a good way. Maybe the deploys with sync mode enabled should be just a list and globally available from any actions.

### Your environment

* **OS:** macOs
* **How I'm running Kubernetes:**  

`garden version` 0.13.2

**Comment by edvald** [comment]
We might be able to allow referencing the action modes without making a dependency on the resolution, but the better solution will be parameterized actions, which has a design draft already.

In the meantime, I'd suggest making two separate builds with the different stages, instead of referencing the dependency in a single build.

**Comment by stefreak** [comment]
@edvald interesting idea to make two different builds! I'll try that. Thank you.

**Comment by stefreak** [comment]
Here is a working workaround using your suggestion:

```
# Production container to be used without sync mode.
kind: Build
type: container
name: limiter-prod
include:
  - src
  - Dockerfile
exclude:
  - src/tmp/*
spec:
  dockerfile: "Dockerfile"

---

# The sync container only provides the tools necessary for building the library
# when using it during inner loop development together with Garden's sync mode.
kind: Build
type: container
name: limiter-sync
include:
  - Dockerfile
spec:
  dockerfile: "Dockerfile.syncmode"

---

kind: Deploy
type: container
name: limiter
build:
  $if: ${command.params contains 'sync' && (command.params.sync contains 'limiter' || isEmpty(command.params.sync))}
  $then: limiter-sync
  $else: limiter-prod
[...]
```

I wasn't able to use `${this.mode}` unfortunately because of #4616
