### ISSUE TITLE
[FEATURE]: experimental local-openshift provider scaffolding

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#4608]
Part of the OpenShift epic https://github.com/garden-io/garden/issues/4243

We should add the initial scaffolding to Garden so that it can parse a project definition like this:

```yaml
apiVersion: garden.io/v1
kind: Project
name: demo-project
environments:
  - name: local
providers:
  - name: local-openshift
    environments: [local]
```

- Make sure to print warning messages about the experimental status
- Either disable documentation generation for this, or print large warning messages at the top
- The actual functionality of the provider is not required yet
