### ISSUE TITLE
Template string variables unresolved in some circumstances

### ISSUE THREAD

**Issue by TimBeyer** [garden-io/garden#4614]
## Bug

When setting up a kubernetes module, in some circumstances variables in template strings are not resolved unless the expression somehow mentions another context to resolve variables from before the string to be templated.

### Current Behavior

```
# This sets it to the string "${environment.namespace}"
TEST: "base64Encode(\"${environment.namespace}\")"
```

```
# This sets it to the string "${environment.namespace}"
TEST: "${true == true ? base64Encode(\"${environment.namespace}\") : false }"
```

```
# This resolves the template correctly
TEST: "${environment && base64Encode(\"${environment.namespace}\")}"
```

### Expected behavior

The variable should always be resolved and replaced

### Reproducible example

```
apiVersion: garden.io/v0
kind: Project
name: bug-repro
environments:
  - name: local
providers:
  - name: local-kubernetes
    environments: [local]
    namespace: ${project.name}-testing-${var.userId}
variables:
  userId: ${local.username}

---

kind: Module
description: Secret
type: kubernetes
name: secret
manifests:
  - apiVersion: v1
    kind: Secret
    data:
      # DOES NOT WORK
      TEST_A: "${base64Encode(\"test-${environment.namespace}-data\")}"
      TEST_B: "${true == true && base64Encode(\"test-${environment.namespace}-data\")}"
      # WORKS
      TEST_C: "${environment && base64Encode(\"test-${environment.namespace}-data\")}"
      TEST_D: "${var.userId && base64Encode(\"test-${environment.namespace}-data\")}"
    metadata:
      name: credentials
```

### Workaround

Using `"${environment && base64Encode(\"${environment.namespace}\")}"`

### Your environment

* **OS:** macOS 13.4
* **How I'm running Kubernetes:** docker

```
garden version
0.12.58
0.13.1
```
