### ISSUE TITLE
0.13: [Bug]: `this.mode` not available in `build` option of `Deploy` action

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4616]
## Garden Bonsai (0.13) Bug

When choosing the build action for a deploy action, the template context does not include `this` so I cannot differentiate between modes (e.g. sync mode)

I want to use a different build action when in sync mode because in sync mode I need dev dependencies in the Dockerfile, which I do not need for the production container.

### Current Behavior

When using `build: "${this.mode == 'sync' && 'foo' || 'bar' }"` 
```
Error processing config for Deploy action limiter:
Invalid template string (${this.mode == 'sync'}): Could not find key this. Available keys: command, datetime, environment, git, inputs, local, parent, project, secrets, template, var and variables.
```

### Expected behavior

I expect it to successfully choose the correct build action depending on the value of `this.mode`.

### Reproducible example

See this pull request to the quickstart-example: https://github.com/garden-io/quickstart-example/pull/9/files

```
# Production container to be used without sync mode.
kind: Build
type: container
name: limiter-prod
include:
  - src
  - Dockerfile
exclude:
  - src/tmp/*
spec:
  dockerfile: "Dockerfile"

---

# The sync container only provides the tools necessary for building the library
# when using it during inner loop development together with Garden's sync mode.
kind: Build
type: container
name: limiter-sync
include:
  - Dockerfile
spec:
  dockerfile: "Dockerfile.syncmode"

---

kind: Deploy
type: container
name: limiter
build:
  $if: "${this.mode == 'sync'}"
  $then: limiter-sync
  $else: limiter-prod
spec:
  sync:
    command: [air]
    paths:
      - target: /app
        source: ./src
        mode: one-way-replica
        exclude: ["tmp/*/**"]
  ports:
    - name: http
      containerPort: 8080
      servicePort: 80
  ingresses:
    - path: /
      port: http
      hostname: limiter-${var.base-hostname}
  env:
    PROXY_URL: http://api

```

### Workaround

As a workaround it is possible to use 
```
  $if: ${this.mode == 'sync' && (command.params.sync contains 'limiter' || isEmpty(command.params.sync))}
```
Where `limiter` is the name of the deploy action. It is not 100% reliable as you can also use wildcards in the sync params, and you can start / stop syncs using `garden sync`  commands.

### Suggested solution(s)

Make the `this` context available in `build`.

### Additional context
Once this is fixed, also update the code of the `limiter` service in https://github.com/garden-io/quickstart-example

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS

`garden version` 0.13.2
