### ISSUE TITLE
0.13: [Bug]: deploy action invalidated when files change that are not included in the build action

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4618]
## Garden Bonsai (0.13) Bug
When I make changes to files that are not included in the build action, I expect no changes when running garden deploy.

### Current Behavior

Currently, when touching files that are not included in the deploy's build action, the deploy action will be considered 'outdated' and redeployed, even though nothing has changed:

```
ℹ deploy.test          → outdated
ℹ build.test           → Already built
ℹ deploy.test          → Deploying version v-9b6a2216a5...
ℹ deploy.test          → Waiting for resources to be ready...
ℹ deploy.test          → Resources ready
✔ deploy.test          → Done (took 2.7 sec)
```

### Expected behavior

I expect no changes when I touch files that are not included in the build action:
```
ℹ deploy.test          → Already deployed
```

### Reproducible example

`garden.yml`
```
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes
---
kind: Build
type: container
name: test
include:
 - Dockerfile
---
kind: Deploy
type: container
name: test
build: test
```

`Dockerfile`
```
FROM nginx
```

1. `garden deploy` (deploy the service for the first time)
2. `touch someFile` (Change a file that is not `include`d in the build action)
3. `garden deploy` (Deploy should not redeploy, because no files included in the build action changed)

### Workaround

Add `include: []` to the deploy action. This will successfully work around, but I feel that this should be unnecessary because the build action should count here.

### Suggested solution(s)

I don't know where to start with the solution.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS

`garden version` 0.13.2
