### ISSUE TITLE
0.13: [Bug]: action-variables can't be used in action's excludes or includes

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4619]
## Garden Bonsai (0.13) Bug
I can't use action-variables in excludes or includes.

### Current Behavior

```
% garden validate
Error processing config for Deploy action test2:
Invalid template string (${var.anyVar}): Could not find key anyVar under var. Available keys: (none).
```

### Expected behavior

Successful validation

### Reproducible example

```
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes

---
kind: Deploy
type: exec
name: test2
build: test
exclude: "${var.anyVar}"
variables:
  anyVar:
    - "*/**"
```

### Workaround

1. Use project-level variables if possible
2. Do not use variables (e.g repeat code)

### Suggested solution(s)

Allow using action-based variables. We could allow that by lazily evaluating variables and only failing if they refer to a context that's not available yet in excludes/ includes

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS

`garden version` 0.13.2
