### ISSUE TITLE
Crash: Custom commands cause crash in `garden dev` shell: Missing cli argument in custom command wrapper.

### ISSUE THREAD

**Issue by shumailxyz** [garden-io/garden#4668]
### Current Behavior
Custom commands that use `gardenCommand` do not work in dev mode and throw an error:

```
Missing cli argument in custom command wrapper.
This is a bug. Please report it!
```

![Screenshot 2023-06-20 at 12 24 41](https://github.com/garden-io/garden/assets/5106058/77e157e6-3843-491c-95a4-1c512d7bf372)

### Expected behavior

Custom garden commands should work just fine in dev mode.

### Workaround

Use following `commands.garden.yml` and try to run `c` in dev mode.

```
kind: Command
name: echo
description:
  short: Just echo a string
exec:
  command:
    - sh
    - -c
    - echo "hello world"

---

kind: Command
name: c
description:
  short: Run validate cmd
gardenCommand:
  - validate
 
```

`garden version`: 0.13.2
