### ISSUE TITLE
${environment.name} is not interpolated appropriately on deploy action

### ISSUE THREAD

**Issue by KoduIsGreat** [garden-io/garden#4702]
## Bug
I have the following  Deploy action that sets up some kubernetes secrets that utilizes ${environment.name} to select the correct varfile to merge into the deployment but it does not work. Note previously this worked with Modules Here is an example of the Module that worked before
```yaml
kind: Module
name: secrets
type: kubernetes
manifests:
  $forEach: ${var.secrets}
  $return:
    apiVersion: v1
    kind: Secret
    metadata:
      name: ${item.key}
    type: Opaque
    stringData:
      $merge: ${item.value}
varfile: secrets.${environment.name}.yaml
```

### Current Behavior
```yaml
kind: Deploy
name: secrets
type: kubernetes
spec:
  manifests:
    $forEach: ${var.secrets}
    $return:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ${item.key}
      type: Opaque
      stringData:
        $merge: ${item.value}
varfiles: 
  - ./secrets.${environment.name}.yaml
  ```
  
I get the following error when I run garden deploy
```
Error processing config for Deploy action secrets:
Could not find varfile at path './secrets.${environment.name}.yaml'
```
If i hard code it to the environment e.g. "local" it works.

### Expected behavior
It should interpolate the environment name as part of the filepath

### Reproducible example

git clone https://github.com/KoduIsGreat/garden-bug
cd to garden-bug
garden deploy -l5

### Workaround

N/a

### Additional context
Discussed this in discord with worldofgeese

### Your environment

* **OS:** M1 Mac OS Monteray
* I'm using kind for kubernetes

garden version: 0.13.3
