### ISSUE TITLE
0.13: [Bug]: source.repository.url not able to interpolate variables

### ISSUE THREAD

**Issue by andrewjensen** [garden-io/garden#4754]
### Current Behavior

I am upgrading to Bonsai and was previously using vars to reference a secret gitlab token to deploy each service:

```yaml
# Old config...

kind: Module
description: Halberd
type: container
name: halberd
repositoryUrl: https://gitlab-ci-token:${variables.gitlab-token}@gitlab.example.com/path/to/halberd.git#master

# ...
```

But when I convert to the new manifest format for Builds, like this:

```yaml
# New config...

---
kind: Build
name: halberd
type: container
description: Halberd
source:
  repository:
    url: https://gitlab-ci-token:${variables.gitlab-token}@gitlab.example.com/path/to/halberd.git#master

# ...
```

...then I get this error output:

```
Error processing config for Build action halberd:
Invalid template string (https://gitlab-ci-token:${variable…):
```

matching screenshot:

![image](https://github.com/garden-io/garden/assets/3885955/a297d24f-b359-468d-97bd-e4d1cd805701)

(Unfortunately `cat .garden/error.log` shows an empty file, so the error details didn't seem to be saved.)

I know the variable exists because Garden is able to use it in both `buildArgs` and `env`. It seems to **only be the repository url** failing to pass in the available variables for interpolation.

### Expected behavior

When I use `${var.some-var-name}` inside of `source.repository.url`, it should find that in my defined keys and interpolate it rather than failing.

### Reproducible example

Start from the [remote-sources](https://github.com/garden-io/garden/blob/main/examples/remote-sources/worker/garden.yml) example repo.

Edit the Build action for `worker`:

```yaml
kind: Build
type: container
name: worker
source:
  repository:
    url: https://github.com/${variables.github-org}garden-io/garden-example-remote-module-jworker.git#main

variables:
  github-org: garden-io
```

Attempt to run  `garden deploy worker`.

The expected result is that it will successfully build and deploy. The actual result is that the graph resolution will fail even before the build begins, and you will see an error message like this:

```
Error processing config for Build action worker:
Invalid template string (https://github.com/${variables...):
```

### Workaround

No workaround: This is my organization's current way to safely authenticate to pull images from our Gitlab server, so we are blocked from upgrading.

### Suggested solution(s)

Make an edit somewhere in `core` that evaluates the value of `source.repository.url`, so the variables are passed to it correctly.

(Sorry, I'm not familiar enough with the source code to be more help on this section!)

### Additional context

Some other test cases I tried:

- `gitlab-token` in source.repository.url: fails
  - The test case of the issue
- `gitlab-token` in an env var: succeeds
  - Able to shell into my deployment and run `env | grep GITLAB_TOKEN` and see the value
- `this-var-does-not-exist` in an env var: fails with "invalid template string"
  - Indicates that when a var is missing, from some other spot in the config files, the error message looks the same
- `ingress-suffix` in an env var: succeeds
  - Other env var that I know works, as a sanity check

### Your environment

* **OS:**: MacOS Ventura 13.4 
* **How I'm running Kubernetes:**: EKS, Kubernetes 1.23 

```
garden version: 0.13.6
```

**Comment by shumailxyz** [comment]
@andrewjensen Thank you for reporting this issue. I am unable to reproduce it with the [remote-sources](https://github.com/garden-io/garden/blob/main/examples/remote-sources/worker/garden.yml) example by introducing the change in url that you mentioned in reproducible example steps.

I just tried it out and for me, the variable `github-org` is resolved correctly and `deploy worker` goes through successfully. 

Could you please try this again or provide more info so we can reproduce it?

---
I'm posting my logs below as well:

> garden version

```
➜  bug-repository-url git:(main) ✗ garden version
garden version: 0.13.6
```

> directory listing

```
➜  bug-repository-url git:(main) ✗ ls -la
total 32
drwxr-xr-x@  8 shumail  staff   256 Jul  6 11:51 .
drwxr-xr-x@ 16 shumail  staff   512 Jul  6 11:20 ..
-rw-r--r--@  1 shumail  staff  6148 Jul  6 11:51 .DS_Store
drwxr-xr-x@  9 shumail  staff   288 Jul  6 11:45 .git
-rw-r--r--@  1 shumail  staff     0 Jul  6 11:45 .gitignore
-rw-r--r--@  1 shumail  staff  2112 Jul  6 11:43 README.md
-rw-r--r--@  1 shumail  staff  1726 Jul  6 11:46 garden.yml
drwxr-xr-x   3 shumail  staff    96 Jun 22 13:37 worker

➜  bug-repository-url git:(main) ✗ ls -la worker
total 8
drwxr-xr-x  3 shumail  staff   96 Jun 22 13:37 .
drwxr-xr-x@ 8 shumail  staff  256 Jul  6 11:51 ..
-rw-r--r--@ 1 shumail  staff  470 Jun 22 13:37 garden.yml
```

> my `worker/garden.yml` 

(note that in original issue, there was a mistake in the URL as `https://github.com/${variables.github-org}garden-io/` included `garden-iot` after the variable `variables.github-org`.

```
➜  bug-repository-url git:(main) ✗ cat worker/garden.yml
kind: Build
type: container
name: worker
source:
  repository:
    url: https://github.com/${variables.github-org}/garden-example-remote-module-jworker.git#main

variables:
  github-org: garden-io

---
kind: Deploy
description: The worker that collects votes and stores results in a postgres table
type: container
name: worker
build: worker
dependencies:
  - deploy.redis
  - run.db-init
spec:
  env:
    PGDATABASE: ${var.postgres-database}
    PGUSER: ${var.postgres-username}
    PGPASSWORD: ${var.postgres-password}
```
> and finally ran `garden deploy worker` and that goes through.

Note that in the logs, it also shows the fully resolved URL for worker. `Fetching from https://github.com/garden-io/garden-example-remote-module-jworker.git#main`



```
➜  bug-repository-url git:(main) ✗ garden deploy worker
Deploy 🚀

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment local.default
ℹ db-services          → Fetching from https://github.com/garden-io/garden-example-remote-sources-db-services.git#66903d73fbca3daa6ed53d04a4b03ddd9dafea43
ℹ web-services         → Fetching from https://github.com/garden-io/garden-example-remote-sources-web-services.git#main
✔ web-services         → Done (took 1.2 sec)
✔ db-services          → Done (took 1.3 sec)
ℹ providers            → Getting status...
ℹ providers            → Getting status...
✔ providers            → Done (took 0.2 sec)
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.6 sec)
ℹ providers            → Preparing environment...
ℹ local-kubernetes     → Configuring...
ℹ providers            → Getting status...
✔ providers            → Cached (took 0.4 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ providers            → Getting status...
✔ providers            → Cached (took 0 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.6 sec)
ℹ deploy.default-backend → outdated
ℹ deploy.default-backend → Deploying version v-a9bc10af9e...
ℹ deploy.default-backend → Waiting for resources to be ready...
ℹ deploy.ingress-controller → outdated
ℹ deploy.default-backend → Resources ready
✔ deploy.default-backend → Done (took 2.7 sec)
ℹ deploy.ingress-controller → Deploying version v-f0a583adb3...
ℹ deploy.ingress-controller → Waiting for resources to be ready...
ℹ deploy.ingress-controller → Resources ready
✔ deploy.ingress-controller → Done (took 4.2 sec)
✔ local-kubernetes     → Ready
✔ providers            → Done (took 11.8 sec)
ℹ graph                → Resolving actions and modules...
ℹ build.worker         → Fetching from https://github.com/garden-io/garden-example-remote-module-jworker.git#main
✔ build.worker         → Done (took 1.2 sec)
✔ graph                → Done (took 1.9 sec)
ℹ deploy.worker        → missing
ℹ deploy.redis         → missing
ℹ deploy.redis         → Deploying version v-ce4fe584ea...
ℹ deploy.db            → missing
ℹ deploy.db            → Deploying version v-875dd08778...
ℹ build.worker         → Already built
ℹ deploy.db            → Waiting for resources to be ready...
ℹ deploy.redis         → Waiting for resources to be ready...
ℹ deploy.redis         → Resources ready
✔ deploy.redis         → Done (took 2.8 sec)
ℹ deploy.db            → Deployment/db: Started container db
ℹ deploy.db            → Resources ready
✔ deploy.db            → Done (took 5.4 sec)
ℹ run.db-init          → Running...
✔ run.db-init          → Done (took 19.7 sec)
ℹ deploy.worker        → Deploying version v-b2949e6f33...
ℹ deploy.worker        → Waiting for resources to be ready...
ℹ deploy.worker        → Resources ready
✔ deploy.worker        → Done (took 2.6 sec)

Done! ✔️
```
