### ISSUE TITLE
0.13: [Bug]: `garden deploy --force-build` has no effect without also specifying `--force`

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#4800]
### Current Behavior

1. Run `garden deploy`
```
ℹ deploy.nginx         → missing
ℹ build.example        → Building example:v-dcb0e827a8...
✔ build.example        → Done (took 10.8 sec)
ℹ deploy.nginx         → Deploying version v-368eff6e63...
ℹ deploy.nginx         → Waiting for resources to be ready...
ℹ deploy.nginx         → Resources ready
✔ deploy.nginx         → Done (took 2.7 sec)
```
2. Run `garden deploy --force-build`
```
ℹ deploy.nginx         → Already deployed
```

### Expected behavior

I expect that garden rebuilds the example container and re-deploys the nginx service.

### Reproducible example

```
# garden.yml
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
 - name: default
providers:
 - name: local-kubernetes

---
kind: Module
type: container
name: example
exclude:
  - node_modules/**
services:
  - name: nginx
```

```
# Dockerfile
FROM nginx
```

### Workaround

```garden deploy --force --force-build```

### Suggested solution(s)

Garden needs to detect where deploys need to be implicitly forced, as is the behaviour of latest garden acorn (0.12).

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** Docker desktop

`garden version` edge-bonsai
