### ISSUE TITLE
0.13: [Feature Request]: Reuse variables between environment and deploys

### ISSUE THREAD

**Issue by antoinelyset** [garden-io/garden#4817]
### Current Behavior

In the current version of Garden Bonsai, there seems to be no way to share variables between environment and deploys. If I want to reuse variables between deploys and I want to use variables from the environment, I can't.

### Expected behavior

I expected to be able to reuse variables between deploys (modules in general) and use variables from the environment. This was possible in previous versions using YAML *anchors because different deploys could be in the same `Module`.

### Reproducible example

```yaml
# in Project
environments:
  - name: personal
    variables:
      rootHostname: ${local.env.GARDEN_USERNAME || local.username}.dev
      commonConf:
        api:
          env:
            some-common-api-variables: true
---
kind: Deploy
type: container
name: api
build: api
spec:
  env:
    $merge: ${var.commonConf.api.env}
    a-variable-that-needs-rootHostname: ${var.rootHostname}
---
kind: Deploy
type: container
name: api-worker
build: api
spec:
  env:
    $merge: ${var.commonConf.api.env}
    a-variable-that-needs-rootHostname: ${var.rootHostname}
```

### Workaround

Right now I just copy pasted variables like `a-variable-that-needs-rootHostname` in the example.

### Suggested solution(s)

A possible solution could be to implement a new feature that allows for the reuse of variables between modules (with variables coming from the `environment`). Some kind of intermediary step/conf.

### Additional context

This issue has been causing some difficulties in managing and reusing variables in my projects. 

### Your environment

* **OS:** MacOS
* **How I'm running Kubernetes:** GKE

---

My bad if I've missed a pattern here :D

**Comment by antoinelyset** [comment]
My bad if I didn't use the right template, I clicked on url in the CLI `https://go.garden.io/report-bonsai`

**Comment by Orzelius** [comment]
hey @antoinelyset, I think you have two separate issues here:

1. reusage of variables between actions. This is a valid feature request as we don't offer a convenient way to do so.

2. Bug where environment variables are not available in actions. I failed to reproduce this.

```
apiVersion: garden.io/v1
kind: Project
defaultEnvironment: local
name: cool-test
environments:
  - name: local
    defaultNamespace: local-testing
    variables:
      somevar: foo
      my:
        nested:
          var: bar
---
kind: Run
type: exec
name: echo
spec:
  command: ["echo", "${var.somevar} ${var.my.nested.var}"]
```
`garden run echo -l3` prints "foo bar" just fine for me.

Please make sure you're on the env you're trying to use the variables from and check for typos.

**Comment by antoinelyset** [comment]
Ha, I think it's a misunderstanding, when I talk about "variables from the environment", I'm not talking about environment variables but variables coming from `project.environments.{name}.variables`. :D

**Comment by hnicke** [comment]
In our garden stack we solved this by introducing a `common` exec module which does not declare any service nor task - it only contains the 'common' shared variables.
```
kind: Module
type: exec
name: common
description: |
  Commonly shared variables are defined here in order to circumvent circular dependencies.
  Most of the time, defining the variables project-wide or environment-wide (via project.garden.yml) is sufficient.
  Sometimes this is not an option since when defining variables, other variables which were defined in the same scope can't be accessed.
  I.e., Only define variables here if you need to reuse an environment-wide variable.
variables:
  foo: bar-${var.variable-from-environment-scope}
```

In the other modules, these variables can be references like this: `${modules.common.var.foo}`.

This is a workaround which works quite well for us.

**Comment by antoinelyset** [comment]
Oh that's clever. Nice hack indeed! I will see if I can refactor some Modules with it. Thanks a lot for sharing!

**Comment by vvagaytsev** [comment]
@antoinelyset it looks like this is no longer a bug. Could you please elaborate on the idea of sharing variables between actions?

Currently, it's possible to refer to the variables of one action from another:

```yaml
kind: Project
apiVersion: garden.io/v1
name: repro
# in Project
environments:
  - name: default

---
kind: Deploy
type: exec
name: foo
variables:
  FOO: "foo"
spec:
  deployCommand: [ "sh", "-c", "echo", "foo" ]

---
kind: Deploy
type: exec
name: bar
spec:
  deployCommand: [ "echo", "bar", "${actions.deploy.foo.var.FOO}" ]
```

If you run `garden deploy bar -l3` you'll see the variable `${actions.deploy.foo.var.FOO}` resolved and printed. Is that something you'd like to reach?

If not, feel free to file a separate feature request. Let's close this as a resolved bug for now :) Thank you!
