### ISSUE TITLE
0.13: [Bug]: use Project variables in the include/exclude of an action

### ISSUE THREAD

**Issue by antoinelyset** [garden-io/garden#4830]
### Current Behavior

I'm not able to use Project variables in the `include` of a `Build`.

If I run this I get `Invalid template string (${var.include): Could not find key include under var. Available keys: (none).`

### Expected behavior

To be able to use the var

### Reproducible example

```yaml
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
 - name: default
   variables:
     include:
       - 'afile'
providers:
 - name: local-kubernetes

---
# it can be reproduced with Build/Run/Test as well
kind: Deploy
type: exec
name: test
include:
  - $concat: ${var.include}
spec:
  deployCommand: ["sh", "-c", "echo", "foo"]
```

I didn't try exactly this but this is the idea.

### Workaround

Duplication 

### Suggested solution(s)

Being able to use it :D 

### Your environment

garden version: 0.13.8
