### ISSUE TITLE
0.13: [Bug]: ModuleTemplate - Module is not able to find the build dependency

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#4833]
## Garden Bonsai (0.13) Bug - Ignore build.dependencies mentioned in pulumi module

Garden is not able to find the build dependency mentioned in ModuleTemplate. Below is the configuration

```
kind: ModuleTemplate
name: spring-service-module-template
inputsSchemaPath: rest.schema.json
modules:
  - type: pulumi
    name: ${parent.name}-service # ${var.test}-${parent.name} #${parent.name}-module
    description: common to all REST services
    root: ${inputs.deploymentFolder}/pulumi
    stack: "${environment.name}"

    variables:
      excludeDefault: ["${parent.name}"]
      pulumiProjectName: ${var.gardenProjectName}-${var.projectname}-${parent.name}

    createStack: true
    autoApply: true

    deployFromPreview: ${var.withPlan}

    pulumiVarfiles: 
       - "${local.projectPath}/deployment-common/pulumi/config/global.yaml"
       - "${inputs.deploymentFolder}/config/common.yaml"
       - "${inputs.deploymentFolder}/config/${environment.name}.yaml"

      
    generateFiles:
      - sourcePath: ../pulumi/Pulumi.yaml
        targetPath: ${inputs.deploymentFolder}/pulumi/Pulumi.yaml
      - sourcePath: ../pulumi/index.ts
        targetPath: ${inputs.deploymentFolder}/pulumi/default-index.ts
    build:
      dependencies: [x-publish-image]


  - type: jib-container
    name: x-publish-image
    description: Backend service

    varfile: "dependencies.yaml"

    include: 
      - ./**/src/**/*
      - pom.xml
      - ./**/pom.xml
    image: ${parent.name}
    extraFlags: 
    - -Djib.useOnlyProjectCache=false
    - "-Djib.from.image=${var.dockerRepo}/${inputs.jdkVersion == '11' ? var.baseImageJava11 : var.baseImageJava8}"
    - "-nsu"
    - "-Dtransitive=false"

    build: 
      jdkVersion: ${inputs.jdkVersion} 
      projectType: maven
      dependencies: ${var.dependencies}?
      mavenPhases: [ "clean", "package" ]
```

When I trigger the command ```garden deploy x-service```

**Expected Output**
garden first execute the x-publish-image and then it should execute the x-service.

**Actual Output**
garden only execute the x-service and ignore the build-dependency
