### ISSUE TITLE
Non-existing variable breaks the behaviour of `$merge` operator

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4880]
### Current Behavior
When `$merge` operator encounters an undefined variable as an argument it never gets resolved properly. It is rendered as JSON object instead.

Assume we have variables defined in the project-level config:
```yaml
variables:
  example-env:
    FIELD1: hi
    FIELD2: bye
```

If we use `$merge` operator like this
```
  env:
    $merge: ${var.example-env}
    HELLO: GOODBYE
```
then we get a valid output:
```yaml
          env:
            - name: FIELD1
              value: hi
            - name: FIELD2
              value: bye
            - name: HELLO
              value: GOODBYE
```

But if we change `$merge: ${var.example-env}` to ``$merge: ${var.empty || var.example-env}` then the output is invalid:
```yaml
          env:
            - name: $merge
              value:
                FIELD1: hi
                FIELD2: bye
            - name: HELLO
              value: GOODBYE
```
Here `$merge` is not considered a valid helper function and is interpreted as a JSON object key.

### Expected behavior

The missing variable can be interpreted as an empty one to produce a valid output:
```yaml
          env:
            - name: FIELD1
              value: hi
            - name: FIELD2
              value: bye
            - name: HELLO
              value: GOODBYE
```

Or an error can be thrown because of the reference to a missing variable. To be confirmed. Need to check the expected behavior in the docs.

### Reproducible example

<details>

1. Create the project from the files below:

<details>

`bug-demo.garden.yml`
```yaml
---
kind: Module
type: container
name: bug-module
description: Container Module
---
kind: Module
type: templated
template: manifests-local
name: manifests
inputs:
  env:
    $merge: ${var.empty || var.example-env}
    HELLO: GOODBYE
---
kind: ModuleTemplate
name: manifests-local
inputsSchemaPath: schema.json
modules:
  - type: kubernetes
    name: bug-service
    description: ${parent.name} manifests
    build:
      dependencies:
        - bug-module
    variables:
      env:
        # put non-secrets into the correct format.
        - $concat:
            $forEach: ${inputs.env || []}
            $return:
              name: ${item.key}
              value: ${item.value}
    files: [.manifests-template.yml]
    generateFiles:
      - sourcePath: manifests-template.yml
        targetPath: .manifests-template.yml
```

`project.garden.yml`
```yaml
kind: Project
name: example-project
variables:
  example-env:
    FIELD1: hi
    FIELD2: bye
environments:
  - name: default
    defaultNamespace: ${project.name}
providers:
  - name: local-kubernetes
    environments: [ default ]
    namespace: ${environment.namespace}
```

`manifests-template.yml`
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-demo
  labels: my-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${parent.name}
      service: ${parent.name}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: my-label
    spec:
      containers:
        - name: ${parent.name}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          env:
${indent(yamlEncode(var.env), 12)}
```

`schema.json`
```yaml
{
  "type": "object"
}
```

`Dockerfile`
```dockerfile
FROM nginxdemos/hello
```

</details>

2. Run `garden validate`
3. Check the `spec.template.containers.spec` section in the generated `.manifests-template.yml` file, it will have the following `env` values (which are correct):
```yaml
          env:
            - name: FIELD1
              value: hi
            - name: FIELD2
              value: bye
            - name: HELLO
              value: GOODBYE
```
5. Modify `bug-demo.garden.yml` file by rewriting the inputs section as follows (change `$merge: ${var.example-env}` to `$merge: ${var.empty || var.example-env}`, the variable `empty` is not defined in any scope): 
```
inputs:
  env:
    $merge: ${var.empty || var.example-env}
    HELLO: GOODBYE
````
6. Rerun `garden validate`
7. Check the re-generated `.manifests-template.yml` again, the `env` values will be:
```yaml
          env:
            - name: $merge
              value:
                FIELD1: hi
                FIELD2: bye
            - name: HELLO
              value: GOODBYE
```

</details>

### Workaround
Unknown

### Additional context
This might not be a module-template-specific issue. Need to check it with a simpler example if possible.

### Your environment
`garden version 0.13.9`

**Comment by vvagaytsev** [comment]
One more issue reported by user:

> The templated module also does not properly allow its own variables to be assigned to the inputs:

```yaml
---
kind: Module
type: templated
template: minted-manifests-local
name: manifests
variables:
  replicas: 1
inputs:
  replicas: ${var.replicas}
---
kind: ModuleTemplate
name: minted-manifests-local
inputsSchemaPath: schema.json
modules:
  - type: kubernetes
    name: bug-service
    description: ${parent.name} manifests
    template-replicas: ${inputs.replicas}
```
> It gives the error:
```console
bug-service: Invalid template string (${var.replicas}): Could not find key replicas under var. Available keys: example-env.
varfiles also seem to not work here.
```
