### ISSUE TITLE
0.13: [Bug]: ModuleTemplate failed to identify variable with default value pass in schema.json file

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#4882]
### Current Behavior

Garden fails with the error:

```console
Failed resolving one or more modules:

name: Invalid template string (-Djib.from.image=${var.dockerRepo}…): Could not find key jdkVersion under inputs. Available keys: (none).
```

### Expected behavior

No errors, validation should pass.

### Reproducible example

Run `garden validate` with the configuration below.

**Garden configuration.**
```yaml
kind: Project
apiVersion: garden.io/v1
name: repro
environments:
  - name: default
providers:
  - name: local-kubernetes
    environments: [ default ]
variables:
  dockerRepo: "hub.docker.io"
  baseImageJava8: eclipse-temurin:8u345-b01-jre-ubuntu23
  baseImageJava11: distroless-os-images:debian11-java11.0.18

---
kind: Module
type: templated
template: k8s-container
name: name

---
kind: ModuleTemplate
name: k8s-container
inputsSchemaPath: schema.json

modules:
  - kind: Module
    type: container
    name: ${parent.name}  # Now possible as it doesn't conflict with the RenderTemplate type
    extraFlags:
      - "-Djib.from.image=${var.dockerRepo}/${inputs.jdkVersion == '11' ? var.baseImageJava11 : var.baseImageJava8}"
```

**`schema.json`**
```yaml
{
    "type": "object",
    "properties": {
      "excludeModules": {
        "type": "array",
        "items": {
            "type": "string"
        }
      },
      "jdkVersion": {
        "type": "string",
        "default": "8"
      }
    }
}
```

**Dummy `Dockerfile`**
```dockerfile
FROM busybox:1.36.0
ENTRYPOINT ["tail", "-f", "/dev/null"]
```

### Workaround

Use action-based template:

```yaml
---
kind: ModuleTemplate
name: k8s-container
inputsSchemaPath: schema.json

configs:
  - kind: Build
    type: container
    name: ${parent.name}  # Now possible as it doesn't conflict with the RenderTemplate type
    spec:
      extraFlags:
        - "-Djib.from.image=${var.dockerRepo}/${inputs.jdkVersion == '11' ? var.baseImageJava11 : var.baseImageJava8}"
```

**Comment by vvagaytsev** [comment]
@ishantagarwal-x213235 I've also updated the `ModuleTemplate` config. The `extraFlags` of the `Deploy` action must be in located in the `spec`:

```yaml
---
kind: ModuleTemplate
name: k8s-container
inputsSchemaPath: schema.json

configs:
  - kind: Build
    type: container
    name: ${parent.name}  # Now possible as it doesn't conflict with the RenderTemplate type
    spec:
      extraFlags:
        - "-Djib.from.image=${var.dockerRepo}/${inputs.jdkVersion == '11' ? var.baseImageJava11 : var.baseImageJava8}"
```
