### ISSUE TITLE
0.13: [Bug]: Kubernetes manifest change not taken into account during deploy

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#4884]
### Current Behavior

When removing a field from the kubernetes spec, like a annotation, garden does not pick up the change when deploying that action. Instead, it yields `Already deployed`.

### Expected behavior

Garden should detect that the action changed and redeploy.
I expect the same behavior as when applying the manifest via `kubectl apply`.

### Reproducible example
Given: A kubernetes module with one ingress, having two annotations `foo` and `foobar`:
```
# example.garden.yml
kind: Module
type: kubernetes
name: example
files:
  - ingress.yml
```

```
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  annotations:
    foo: bar
    foobar: baz
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              service:
                name: example
                port:
                  number: 80
            path: /
            pathType: Prefix
```

Run `garden deploy example`.

Then, remove the `foobar` annotation from the ingress: 

```
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  annotations:
    foo: bar
    # foobar: baz <-- remove
spec:
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              service:
                name: example
                port:
                  number: 80
            path: /
            pathType: Prefix
```

Run `garden deploy example` once again.
Output: `ℹ deploy.example       → Already deployed`.
The module is not redeployed and thus the annotation does not get removed.

### Workaround

When running `garden deploy example --force`, the annotation is correctly removed.

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.13.9
