### ISSUE TITLE
[IMPROVEMENT]: add description to provider config or add type field. 

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4892]
### Background / Motivation

When configuring multiple `kubernetes` providers (e.g. for a multi-cloud setup), users are required to create multiple `kubernetes` providers and this, aside being slightly unintuitive, could also cause confusion when trying to edit the configuration.
See example below:

```yaml
 - name: kubernetes
  environments: [remote-gcp]
  kubeconfig: "cnujasd88js.yaml"
  context: default
  ingressClass: "nginx"
  buildMode: kaniko
  ...
  namespace: ${environment.namespace}
  defaultHostname: ${var.base-hostname}
  dependencies:
    - exec

- name: kubernetes
  environments: [remote-azure]
  kubeconfig: "123123hj23h2j3h.yaml"
  context: default
  ingressClass: "nginx"
  buildMode: kaniko
  ...
  namespace: ${environment.namespace}
  defaultHostname: ${var.base-hostname}
  dependencies:
    - exec


```

### What should the user be able to do?

Ideally I would like to be able to specify a description for my provider, like the example below:

```yaml
- name: kubernetes
  description: "My kubernetes provider for the Azure cluster"
  environments: [remote-azure]
  kubeconfig: "123123hj23h2j3h.yaml"
  ...
```
or alternatively, change the semantic of `name` and add a new `type` field:

```yaml
- name: azure-k8s-provider
  type: kubernetes
  environments: [remote-azure]
  kubeconfig: "123123hj23h2j3h.yaml"
  ...
```

### Why do they want to do this? What problem does it solve?

It makes it easier and more maintainable to configure multiple providers of the same type.

### Suggested Implementation(s)

Adding the description is a simple fix and could be done easily. Changing the semantic of `name` is a breaking change and we could consider it for `0.14.0`.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
