### ISSUE TITLE
0.13: [Bug]: Logs not streamed to Cloud if running workflow with "run" command

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#4916]
### Current Behavior

The correct way to run a workflow with Bonsai is via the `garden workflow <my-workflow>` command.

However, we still support the old way which is `garden run workflow <my-workflow>` which invokes the `run` command.

The problem is that the `run` command has `streamLogEntries` set to `false` (it's supposed to be `true` when running workflows).

This just an oversight / edge case but needs to be addressed because quite a lot of users will continue using `run` event if its deprecated and will risk losing logs. 

### Expected behavior

Garden should stream log entries when running workflows, irrespective of how the command is invoked. 

### Reproducible example

Note, this can only be reproduced internally. 

1. Change into some example project that's configured for Cloud.
2. Add the following workflow config:

```
kind: Workflow
name: missing-logs-test 
description: Foo
steps:
  - command: [deploy, --force]
    name: deploy
    description: Deploy the project
```

3. Log into a commercial version of Cloud (community tier doesn't support workflows). 
4. Run `garden run workflow missing-logs-test`
5. Observe how logs aren't streamed, either from the Cloud UI or by running Garden with `-l5`. 

### Workaround

None known.

### Your environment

Latest main, testing against my own Cloud instance.
