### ISSUE TITLE
Dependency on exec.deploy action is ignored

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#4918]
### Current Behavior

Reporting from @xdvpser on Discord:

Hi!
I am using docker image build action and it depends on exec deploy action that deploys registry credentials. When I run `garden deploy <my_docker_build_action>` it goes right away to building an image without even checking the status of exec deploy action. As a result image build fails as there are no creds deployed. In 0.12 it worked, but after upgrade to 0.13 dependency resolution seems broken. I've checked everything, but couldn't find anything to solve this issue.

My actions are defined as in the following example:
```yaml
kind: Deploy
type: exec
name: example-registry-creds
spec:
  deployCommand: [example, deploy, command]
  statusCommand: [example, status, command]
  cleanupCommand: [example, cleanup, command]

--- 

kind: Build
type: container
name: my-docker-image
dependencies:
  - deploy.example-registry-creds
include:
  - Dockerfile
```

Maybe these logs can be related:
```sh
Found 0 files in Deploy action example-registry-creds root /path/to/example-registry-creds  
```

I see also this in the end of the logs
```sh
resolve Deploy type=exec name=example-registry-creds is ready.
```

### Expected behavior

Garden respects the dependency as defined in the configuration file

### Reproducible example

Please take a look at this repo: [https://github.com/xdvpser/bonsai-bug-repro](https://github.com/xdvpser/bonsai-bug-repro).
### Your environment

I am using garden `v0.13.9` on Ubuntu `20.04`, k8s cluster version is `1.23.12`
