### ISSUE TITLE
0.13: [Bug]: Conditional disabled flag is not working with default value

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#4946]
I have a conditional flag "disabled" which needs to pass as an input but only with few services. Here is my config for two services x and y
**Use Case**
X should be disabled in dev environment and Y should work for all envs.

```
kind: RenderTemplate
template: spring-service-module-template
name: x
inputs:
   disabled: ${environment.name == 'dev'}
```

```
kind: RenderTemplate
template: spring-service-module-template
name: y

---
kind: ConfigTemplate
name: spring-service-module-template
inputsSchemaPath: schema.json

configs:
  - type: pulumi
    name: ${parent.name}-service
    disabled: {inputs.disabled}
```

```
schema.json
{
    "type": "object",
    "properties": {
      "excludeModules": {
        "type": "array",
        "items": {
            "type": "string"
        }
      },
      "jdkVersion": {
        "type": "string",
        "default": "8"
      },
      "disabled":{
	"type": "boolean",
	"default":false		
      }
    }
}
```

Following error is coming 
**x-service: Error validating inputs for x-service (services/x/garden.yaml): value at ./disabled must be boolean**

**Comment by TimBeyer** [comment]
I've tried to replicate it, and I think it's just a typo here in `disabled: {inputs.disabled}` which should be `disabled: ${inputs.disabled}`.

In my setup with 
```
kind: ConfigTemplate
name: spring-service-module-template
inputsSchemaPath: schema.json

configs:
  - kind: Run
    type: exec
    name: ${parent.name}-service
    disabled: ${inputs.disabled}
    spec:
      command:
        - sh
        - -c
        - |
          echo "Hello, world!" > .${parent.name}-service.txt

---

kind: RenderTemplate
template: spring-service-module-template
name: y
inputs:
  excludeModules: []

---

kind: RenderTemplate
template: spring-service-module-template
name: x
inputs:
   disabled: ${environment.name == 'dev'}

```

it was working as expected.
