### ISSUE TITLE
[FEATURE]: `kubernetes-*` types for Build actions

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#4954]
### Background / Motivation

I'm kind of using Garden as a replacement for manually scripting builds in either CI/CD scripts (i.e. Gitlab yaml) or in my Dockerfiles. I like being able to run the same thing locally and in CI as it makes the whole cycle much faster; and I like writing the script outside of the Dockerfile since its much easier to debug failing builds when its outside of the Dockerfile and I have to deal less with injecting tokens/keys etc. which is a PITA with docker (and different if you use docker build locally, and kaniko remotely).

My goal is that I want an action to download/clone another repo, run (in effect) make build, and then have the outputs be available to other build tasks in my garden graph.

I've run into a couple dead-ends so far though:

I tried just using "Build exec", which works if you don't sandbox anything which would be the more desirable way of working. Furthermore, this is not not ideal for running in CI and doesn't work in most cases. First, my CI runner is using the gardendev/garden-gcloud image which is good for running garden, but not so much for my own toolchain and may actually be incompatible (for instance this image is on alpine). I could make my own image but then it would be a weird hybrid and hard to maintain. Without that concern it would be better just to run exactly the same build container locally and in CI.
I also looked at using custom commands but this would also suffer from the same problem.

I also tried running the builds inside of a Pod in the cluster (whether that is local minikube or remote GKE). The problem here is that there is no Build type for running in an exec-like command in a pod (like kubernertes-pod for the Run action type). Using Run kubernetes-pod works, but the semantics around passing data between actions is only really set up for Build action types. I can output an artifact but AFAIK there is no good way to get this into the Build container workspace.

Currently, instead of running the build via Garden I just do the build via a multi-stage Dockerfile. My current action configuration looks like this. One step to fetch the source code, so I at least don't have to do this in the Dockerfile. This is reasonable since it depends on a very common dependency in the garden host container/OS. And a second action for running the container build:

```yaml
---
kind: Build
name: get-src
type: exec
description: Get the necessary source codes for running container builds

include: []
spec:
  command:
    - bash
    - "-c"
    - rm -rf myproj;
        git clone
          --depth 1
          --branch ${var.myproj_version}
          https://${var.gitlab_username}:${var.gitlab_token}@${var.gitlab_hostname}/my-org/myproj.git
          myproj &&
        rm -rf myproj/.git

---
kind: Build
name: app-container
type: container
description: App container

dependencies:
  - build.get-src

include:
  - app.Dockerfile

copyFrom:
  - build: get-src
    sourcePath: myproj
    targetPath: myproj

spec:
  dockerfile: app.Dockerfile

``` 

### What should the user be able to do?

I would like to be able to write a series of actions like this:

```yaml
---
kind: Build
name: build-src
type: kubernetes-pod
description: Do a source build to produce executable

include:
  - src
  - pod.yaml

spec:

  files:
    - pod.yaml
  resource:
    kind: Deployment
    name: build-src

  # outputs build to path src/dist
  command: [make]


---
kind: Build
name: my-container
type: container
description: my app container

dependencies:
  - build.build-src

include:
  - app.Dockerfile

copyFrom:
  - build: build-src
    # path to build results
    sourcePath: src/dist
    targetPath: src/dist

spec:
  dockerfile: app.Dockerfile

```

I think it also makes sense to have a `kubernetes-exec` type as well. Maybe helm variants as well, I just don't know enough about them and have not used them yet.

### Why do they want to do this? What problem does it solve?

In the small, my current solution is fairly status quo for doing container builds. The reason I don't like this is that it is very difficult and time consuming to debug builds inside a container build system like `docker build`, `kaniko`, etc. so I prefer to make Dockerfiles as simple as possible i.e. 1. choose OS/toolchain, 2. install necessary dependencies, 3. copy in executables.

I see this as a feature that advances the overall vision of what Garden.

### Suggested Implementation(s)

I'm not sure how to implement this, but it would be combining some already existing functionality to allow for some extra options for Build action types.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
