### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by pabbott-starbucks** [garden-io/garden#4980]
### Background / Motivation

Our team is using garden to build a large, distributed application.  Our app is comprised of many sub-applications across a number of repositories, so we're using `remote-sources` to link everything together.   

In the main repository, we're able to use garden workflows to accomplish continuous delivery via `garden deploy` and also leveraging the `triggers:` so that our environments are updated whenever someone pushes code to the main repository.  We're also able to pull in specific versions of `remote-sources` via a git version tag.  For example... 

```yaml
sources:
  - name: sub-app-1-with-garden-modules
    repositoryUrl: git@github.com:org-name/sub-app-1-with-garden-modules.git#v2.3.4
  - name: sub-app-2-with-garden-modules
    repositoryUrl: git@github.com:org-name/sub-app-2-with-garden-modules.git#v1.19.8
  # ... 
```

This means an app team working primarily in the `sub-app-1` repository needs to cut a new version, and then additionally go to the main repository and bump the version number any time they want to release.  

### What should the user be able to do?

As a developer who primarily works in a repository listed as a garden remote source
I want to be able to trigger garden workflows when i push changes to my repository
so that I can achieve continuous delivery limited to just the modules involved in my sub-application driven by change in my sub-application.

### Why do they want to do this? What problem does it solve?

This would mean that our app dev teams would be able to work independently of one another.  Right now, everyone needs to go to the main repository to issue a new release.  This can be problematic as changes might be in flight for one team, and another team might be ready to launch.  This requires quite a lot of overhead to determine which version of which apps are ready to ship.

### Suggested Implementation(s)

I see quite a few options to solve this problem.  Here are some ideas:

**Idea (1) - Better support for remote repositories**

Since our teams are largely working from repositories listed as `remote-sources` .. I think it would be great to find a way to link all of our repositories together via garden enterprise.  Perhaps a new garden manifest could be created to help designate that repositories as "linked" -- For example...

```yaml
kind: SubProject
id: guid-for-garden-enterprise-project-goes-here
domain: https://garden.company.com
```

With this link established, then developers could gain access to all other modules in the project.  Rather than needing to drive their daily workflows from the main repository.  Additionally, the sub-project designation could enable garden workflows in remote repositories.  Though, I'm not sure what conflicts might arise with the remote-sources list..  Perhaps SubProjects and RemoteSources are mutually exclusive?

**Idea (2) - Enhance workflows**

A perhaps simpler solution would be to add a optional `remote-source` name field to garden workflows.  If all garden workflows need to be in the `main` repository, then we could just specify a `remote-source` as a part of the `triggers:` --  For example...

```yaml
triggers:
  - environment: production
    branches: [main]
    namespace: app-name
    events: [push]
    # new!
    remote-source: sub-app-1-with-garden-modules
```

**Idea (3) - Enhance remote-sources**

Perhaps there is a way to decorate the remote-sources list to enable this functionality?  I'm not s

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

In order to accomplish continuous delivery for these linked repositories, we would really like to do this with garden; however, if its impossible, we'll likely need to look at augmenting with other tools in the industry to accomplish this.  Garden + ArgoCD ?
