### ISSUE TITLE
0.13: [Bug]: Helm Module devMode relative sourcePath resolves to non-POSIX full path and then fails validation

### ISSUE THREAD

**Issue by har-cpol** [garden-io/garden#4982]
### Current Behavior

After upgrade to Garden Bonsai (version 0.13.12), an existing config for Module of type helm with `devMode.sync` set is not valid anymore.
Running `garden validate` raises the error: `"key .sync.paths[0][sourcePath] must be a POSIX-style path"`

Running `garden validate -l=silly` shows that garden transforms this value to a full path that starts with `C:\Users\...` on Windows:

### Expected behavior

`garden validate` should not fail.

### Reproducible example

The attached zip file contains a minimal garden project that triggers the issue:

Module defines: `devMode.sync[0].source: "src"`

My project is in directory `C:\Users\User\proj\demo\`
Running `garden validate -l=silly` shows that the converted value becomes: 
`sync.paths[0].sourcePath: "C:\Users\User\proj\demo\src"`

```
context: spec for Deploy type=helm name=db-local (from module db-local)
schemaMetadata: {}
errorDescription: "key .sync.paths[0][sourcePath] must be a POSIX-style path. Available keys: namespace, portForwards, releaseName, timeout, values, valueFiles, atomic, chart, defaultTarget, sync, localMode)"
errorDetails:
  - message: key .sync.paths[0][sourcePath] must be a POSIX-style path
    path:
      - sync
      - paths
      - 0
      - sourcePath
    type: base
    context:
      label: sync.paths[0].sourcePath
      value: C:\Users\User\proj\demo\src
      key: sourcePath

```

which is then rejected as invalid because it is not a valid POSIX path.

### Workaround

I did not manage to find a workaround - had to disable devMode for this module.

### Additional context

The issue only occurs on Windows.
Behavior same for both `cmd.exe` as from `gitbash`.

### Your environment

* **OS:** Windows 11.
* **How I'm running Kubernetes:** k0s local or gke remote 

`garden version`
[project.garden.yml.zip](https://github.com/garden-io/garden/files/12431947/project.garden.yml.zip)
 : garden version: 0.13.12
