### ISSUE TITLE
[FEATURE]: Make image tag an available output

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4988]
## Feature Request

Provide a `container` Build action image tag (e.g. `v-ae4750b`)  as an output.

### Background / Motivation

Helm library charts like The Helmet often [expose an image tag field](https://github.com/companyinfo/helm-charts/tree/main/charts/helmet#image-parameters). We don't (as far as I can tell) expose this as an output. A workaround is to use Garden's helpers to split the tag:

```yaml
  values:
    image:
      registry: ${providers.kubernetes.config.deploymentRegistry.hostname}
      repository: ${providers.kubernetes.config.deploymentRegistry.namespace}/${actions.build.telegram-bot-service-image.outputs.localImageName}
      tag: ${replace(actions.build.telegram-bot-service-image.outputs.localImageId, "telegram-bot-service-image:", "")}
```

### What should the user be able to do?

```yaml
      tag: ${actions.build.telegram-bot-service-image.outputs.localImageTag}
```

### Why do they want to do this? What problem does it solve?

To improve usability around the `helm` action type and ease transition from `container` to `helm` actions.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
