### ISSUE TITLE
Crash: Cannot read properties of undefined (reading 'selector'

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5018]
### Error message

```
Failed resolving status for Deploy type=kubernetes name=silly-demo (took 0.02 sec). This is what happened:
TypeError: Cannot read properties of undefined (reading 'selector')
    at detectChangedSpecSelector (/Users/steffen/work/github/garden/core/build/src/plugins/kubernetes/status/status.js:391:50)
    at compareDeployedResources (/Users/steffen/work/github/garden/core/build/src/plugins/kubernetes/status/status.js:242:38)
    at async Object.getKubernetesDeployStatus (/Users/steffen/work/github/garden/core/build/src/plugins/kubernetes/kubernetes-type/handlers.js:150:59)
    at async Object.assign.handlerType.handlerType (/Users/steffen/work/github/garden/core/build/src/router/base.js:204:28)
    at async Router.callHandler (/Users/steffen/work/github/garden/core/build/src/router/base.js:175:24)
    at async getStatus (/Users/steffen/work/github/garden/core/build/src/router/deploy.js:89:24)
    at async DeployTask.getStatus (/Users/steffen/work/github/garden/core/build/src/tasks/deploy.js:57:36)
    at async descriptor.value (/Users/steffen/work/github/garden/core/build/src/tasks/base.js:269:29)
    at async /Users/steffen/work/github/garden/core/build/src/util/open-telemetry/decorators.js:47:30
    at async StatusTaskNode.execute (/Users/steffen/work/github/garden/core/build/src/graph/nodes.js:249:28)
    at async GraphSolver.processNode (/Users/steffen/work/github/garden/core/build/src/graph/solver.js:283:35)
```

### What did you do?

```
garden deploy
```

reproducable using this deploy action:
`garden.yml`:
```
kind: Deploy
type: kubernetes
name: silly-demo
spec:
  manifests:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: silly-demo
      labels:
        app.kubernetes.io/name: silly-demo
```

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** local-kubernetes
* **Garden version:** `0.13.13`

### Frequency

100% reproducable

### Workaround

Define a spec:
`garden.yml`:
```
kind: Deploy
type: kubernetes
name: silly-demo
spec:
  manifests:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: silly-demo
      labels:
        app.kubernetes.io/name: silly-demo
    spec: {}
```

### Additional context
The TypeScript types for `KubernetesManifest` seem to suggest that the `spec` is always defined, but input is not being validated sufficiently. Either we need to change the types to make the fields we do not validate optional, or we need to improve validation (but this will be tricky to do for all kinds of possible manifests)
