### ISSUE TITLE
0.13: [Bug]: devMode syncs in windows throwing errors

### ISSUE THREAD

**Issue by kroher** [garden-io/garden#5031]
### Current Behavior

using 0.13 on windows we get errors about the devMode relative sync paths that we have in our config files.

this works fine on 0.12 with the same project, as well as on macOs/linux on 0.12 and 0.13

Error validating spec for Deploy type=kubernetes name=backend(from module backend): key .sync.paths[0][sourcePath] must be a POSIX-style path, key .sync.paths[1][sourcePath] must be a POSIX-style path, key .sync.paths[2][sourcePath] must be a POSIX-style path. Available keys: files, kustomize, manifests, namespace, portForwards, timeout, waitForJobs, defaultTarget, sync, localMode)

example:
```
kind: Module
type: kubernetes
name: backend
description: >
  The main backend service
devMode:
  sync:
    - source: backend
      target: /var/code/backend
      exclude:
        [
          backend/dir1,
          backend/dir2,
        ]
      mode: one-way-replica
    - source: backend/dir1
      target: /var/code/backend/dir1
      mode: one-way-replica
    - target: /var/code/backend/dir2
      source: backend/dir2
      mode: two-way
```

### Expected behavior

that it should work with these configs since it does in 12, and on other os's

### Workaround

use garden 12 on windows

### Your environment

* **OS:** win 11
* **How I'm running Kubernetes:** gke

0.13.13
