### ISSUE TITLE
0.13: [Bug]: Publish does not adhere to specified `publishId`

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5094]
### Current Behavior

When running `garden publish skopeo` it does the following:
```
ℹ build.skopeo         → Tagging image with skopeo:v-8b7165e21a and gardendev/skopeo:v-8b7165e21a
ℹ build.skopeo         → Publishing image gardendev/skopeo:v-8b7165e21a...
```

(It ignores the tag specified in `publishId`)

### Expected behavior

```
ℹ build.skopeo         → Tagging image with skopeo:v-8b7165e21a and gardendev/skopeo:1.41.0-3
ℹ build.skopeo         → Publishing image gardendev/skopeo:1.41.0-3...
```

### Reproducible example

in the garden core `images/skopeo/` directory
```
kind: Module
type: container
name: skopeo
description: Used by the kubernetes provider for interacting with container registries within a cluster
image: gardendev/skopeo:1.41.0-3
dockerfile: Dockerfile
extraFlags: [ "--platform", "linux/amd64" ]
```

or an equivalent build action like

```
kind: Build
type: container
name: skopeo
description: Used by the kubernetes provider for interacting with container registries within a cluster
spec:
  publishId: gardendev/skopeo:1.41.0-3
  dockerfile: Dockerfile
  extraFlags: [ "--platform", "linux/amd64" ]
```

### Workaround

Specify the --tag option, then it correctly only publish the specified `--tag`:

```
 % garden publish skopeo --tag foobar
[...]
ℹ build.skopeo         → Tagging image with skopeo:v-8b7165e21a and gardendev/skopeo:foobar
ℹ build.skopeo         → Publishing image gardendev/skopeo:foobar...
```

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** This is just Docker, no kubernetes involved

`garden version` 0.13.13
