### ISSUE TITLE
varfiles still expected even when action is disabled

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5110]
### Current Behavior

If you have an action which is conditionally disabled Garden still tries to resolve the varfiles, which is annoying since you then need more templating or dummy varfiles to satisfy it. For example locally (env `local`) I want to load some secrets from a user provided varfile, but when running remotely (like in CI) I use a completely different secret mgmt. approach and I don't require this action at all (instead running a different action). So if I have the following action:

```yaml
kind: Deploy
name: local-test-data-secrets
type: kubernetes
disabled: ${environment.name != "local"}

varfiles:
  - test-data.local.yaml
```

Even when running with `--env=dev` Garden still errors out on checking for the varfile.

In the example snippet of the docs this is written:

> If a varfile is defined but not found, an error is thrown in order to prevent misconfigurations silently passing.

Which makes sense only if the action is not disabled.

For reference the specific error is:

```console
[...]

Error processing config for Deploy action local-test-data-secrets:
Could not find varfile at path 'test-data.local.yaml'
```

### Expected behavior

If an action is disabled then varfiles should not be checked for. The above example should work without an error.

### Reproducible example

The above should be enough to reproduce.

### Workaround

My workaround is to just have dummy `test-data.${environment.name}.yaml` files for each environment.

I tried somewhat more convenient approach; which gave a strange error that I couldn't really debug further:

```yaml
kind: Deploy
name: local-test-data-secrets
type: kubernetes
disabled: ${environment.name != "local"}

varfiles:
  $if: ${environment.name == "local"}
  $then:
    - test-data.local.yaml
  $else:
    - test-data.remote.yaml
```

```console
Error processing config for Deploy action local-test-data-secrets:
_a.filter is not a function
```

### Suggested solution(s)

Change the behavior of enforcing varfile existence to not act when actions are disabled.

### Your environment

* **OS: linux**
* **How I'm running Kubernetes: minikube, GKE**

`garden version`
garden version: 0.13.10
