### ISSUE TITLE
containerName inconsistency for multi-container pods

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5113]
### Current Behavior

Currently the only way to specify a container to be used for Run/Test actions is
to use the `kubectl.kubernetes.io/default-container` annotation for a Pod spec.

The documented behavior appears to be that if you don't set the annotation
and/or you want to specify the container within a garden action it appears that
the `containerName` option is what is to be used, both in the
`spec.defaultTarget.containerName` as the default of the Deploy action (for e.g.
`garden exec` and unspecified Run/Test actions) and/or overriden in the
consuming Run/Test action in the `spec.resource.containerName` field.

However, this does not appear to have this behavior.

### Expected behavior

Firstly, I only discovered the `kubectl.kubernetes.io/default-container`
annotation from the `garden exec --help` text. I think it would be helpful to
document this, even though it technically is a feature of the underlying
`kubectl` tool.

Secondly, I think there should be the following order of precedence:

1. If the `spec.resource.containerName` is given for an action (Run or Test)
   targetting a Deploy action Pod this should be used, otherwise
2. if the `spec.defaultTarget.containerName` is specified for a Deploy action
   this should be used, otherwise
3. the native `kubectl` mechanisms for deciding the default container to target, i.e. `kubectl.kubernetes.io/default-container` annotations, otherwise
4. use an arbitrary (but consistent and documented) resolution decision strategy
   hard-coded into Garden behavior.
   
For 4. it might be that you are just using `kubectl` defaults, which is fine but
because `kubectl` is abstracted over being able to read the Garden docs alone
for this should be sufficient.

### Reproducible example

I have the following files for reproducing where I've only redacted some
specifics on configuring my cluster for the kubernetes provider:

`project.garden.yaml`

```yaml
---
apiVersion: garden.io/v1
kind: Project
name: garden-debug-salotz
defaultEnvironment: dev
dotIgnoreFile: .gardenignore

environments:
  - name: dev

providers:
  - name: kubernetes

    # The Garden environments which use the remote cluster
    environments:
      - dev

    [redacted]
---

# Deploy acceptance test container with mounted data
kind: Deploy
name: default-target
type: kubernetes

spec:
  files:
    - multi-defaults.yaml
  defaultTarget:
    kind: Deployment
    name: multi-deploy-default
    # containerName: b

---
# Deploy acceptance test container with mounted data
kind: Deploy
name: nodefault-target
type: kubernetes

spec:
  files:
    - multi-nodefaults.yaml
  defaultTarget:
    kind: Deployment
    name: multi-deploy-nodefault
    containerName: b

---
kind: Test
name: defaults-check
type: kubernetes-exec
dependencies:
  - deploy.default-target

spec:
  resource:
    kind: Deployment
    name: multi-deploy-default
  command:
    - bash
    - -c
    - . /etc/os-release && if [[ $NAME != 'Ubuntu' ]]; then exit 1; fi

---
kind: Test
name: nodefaults-check
type: kubernetes-exec
dependencies:
  - deploy.nodefault-target

spec:
  resource:
    kind: Deployment
    name: multi-deploy-nodefault
    containerName: b

  command:
    - bash
    - -c
    - . /etc/os-release && if [[ $NAME != 'Ubuntu' ]]; then exit 1; fi

---
kind: Test
name: defaults-check-specify
type: kubernetes-exec
dependencies:
  - deploy.default-target

spec:
  resource:
    kind: Deployment
    name: multi-deploy-default
    containerName: a
  command:
    - bash
    - -c
    - . /etc/os-release && if [[ $NAME != 'Debian GNU/Linux' ]]; then exit 1; fi
```

`multi-nodefaults.yaml`
```yaml
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: multi-deploy-nodefault

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nodefaults-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodefaults-pod
    spec:

      containers:
        - name: a
          image: debian:bookworm
          command: [sleep, infinity]
        - name: b
          image: ubuntu
          command: [sleep, infinity]

```

`multi-defaults.yaml`
```yaml
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: multi-deploy-default

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: defaults-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: defaults-pod
      annotations:
        kubectl.kubernetes.io/default-container: b
    spec:

      containers:
        - name: a
          image: debian:bookworm
          command: [sleep, infinity]
        - name: b
          image: ubuntu
          command: [sleep, infinity]
```

This has expected (but hidden implicit) behavior:

```console
$ garden test defaults-check
Running Tests 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment dev.default
ℹ providers            → Getting status...
✔ providers            → Cached (took 0.5 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.1 sec)
ℹ deploy.default-target → Already deployed
ℹ test.defaults-check  → Running...
ℹ test.defaults-check  → Defaulted container b due to the annotation kubectl.kubernetes.io/default-container.
✔ test.defaults-check  → Success (took 1.9 sec)

Done! 
```

And correctly selects the default pod as overridden by the pod annotation.

From my tests both `containerName` fields are ignored:

```console
$ garden test nodefaults-check
Running Tests 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment dev.default
ℹ providers            → Getting status...
✔ providers            → Cached (took 0.5 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.1 sec)
ℹ deploy.nodefault-target → Already deployed
ℹ test.nodefaults-check → Running...
ℹ test.nodefaults-check → Defaulted container a out of: a, b.
✖ test.nodefaults-check → Failed running test (took 2.1 sec)
✖ test.nodefaults-check → Failed processing Test type=kubernetes-exec name=nodefaults-check (took 2.13 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed with exit code 1.
──────────────────────────────────────────────────────────────────────────────────────────────────────────
1 test action(s) failed!
```

And you cannot override the `kubectl.kubernetes.io/default-container` for a Deployment Pod:

```console
$ garden test defaults-check-specify
Running Tests 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment dev.default
ℹ providers            → Getting status...
✔ providers            → Cached (took 0.5 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.1 sec)
ℹ deploy.default-target → Already deployed
ℹ test.defaults-check-specify → Running...
ℹ test.defaults-check-specify → Defaulted container b due to the annotation kubectl.kubernetes.io/default-container.
✖ test.defaults-check-specify → Failed running test (took 2.2 sec)
✖ test.defaults-check-specify → Failed processing Test type=kubernetes-exec name=defaults-check-specify (took 2.19 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed with exit code 1.
──────────────────────────────────────────────────────────────────────────────────────────────────────────
1 test action(s) failed!

See .garden/error.log for detailed error message
```

### Workaround

Currently I'm fine with using the default annotation and I don't have any
complex requirements in choosing containers.

I'm currently just dealing with some sidecars in GKE being picked up rather than
my main container.

### Suggested solution(s)

I think the behavior above is intended and there is a bug in its implementation,
so I would say fix that. Otherwise if I am misinterpreting the use of the
`containerName` fields a feature that does as described above would be very
helpful.

### Your environment

* **OS: linux**
* **How I'm running Kubernetes: GKE**

`garden version`
`garden version: 0.13.14`
