### ISSUE TITLE
0.13: [Bug]: When using templates, file added by copyFrom are excluded from the build context

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#5201]
### Current Behavior

A user is trying to create a template + an exec action to dynamically use a dev Dockerfile (see below).

```yaml
kind: Build
name: docker-dev
type: exec
include:
  - ./Dockerfile.dev
---

kind: ConfigTemplate
name: node-build

configs:
  - kind: Build
    type: container
    name: ${parent.name}-dev
    description: Development build of the ${parent.name}
    exclude: ['node_modules']
    dependencies:
      - build.docker-dev
    copyFrom:
      - build: docker-dev
        sourcePath: ./Dockerfile.dev
        targetPath: ./Dockerfile.dev
    spec:
      dockerfile: ./Dockerfile.dev

```

When trying to build the following templated build action:

```yaml
kind: RenderTemplate

name: node-app-2

template: node-build

```

Garden will throw the following error:

```sh
...

✖ build.node-app-1-dev → Build failed (took 0.7 sec)
✖ build.node-app-1-dev → Failed processing Build type=container name=node-app-1-dev (took 0.73 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Dockerfile not found at ./Dockerfile.dev for build node-app-1-dev.
Please make sure the file exists, and is not excluded by include/exclude fields or .gardenignore files.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1 build action(s) failed!
...
```

NOTE: the `Dockerfile.dev` file is correctly found in the `.garden/build` directory for the action.

### Expected behavior

Garden should take into consideration all the files in the action folder in the build context and successfully build the container using the `Dockerfile.dev` file.

### Reproducible example

Please find the full repo below:

[repro.zip](https://github.com/garden-io/garden/files/12830901/repro.zip)

### Workaround

There is no workaround at the moment. Additionally, the flow the user is trying to implement is a workaround in itself, to overcome the removal of the old `generateFiles` property of Modules (0.12).

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`: `edge`
