### ISSUE TITLE
Crash: copyFrom[0][targetPath] is not allowed to be empty

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5218]
### Error message

```
Error processing config for Build action remote-source:
Configure handler for exec Build set a templated value on a config field which could not be resolved. This may be a bug in the plugin, please report this. Error: Error: Error validating exec Build remote-source 'remote-source':
copyFrom[0][targetPath] is not allowed to be empty
```

### What did you do?

Ran `garden build remote-source` with this config (Requires a directory called `kustomization` with a `.yaml` file inside, e.g. `kustomization.yaml`. The contents do not matter.

```
kind: Build
type: exec
name: remote-source
dependencies:
 - build.kustomization
copyFrom:
  - build: kustomization
    sourcePath: kustomization
source:
  repository:
    url: https://github.com/prometheus-operator/kube-prometheus.git#3fff8b56097778f1491edba968aee3cfbd5652ef
---
# Combine the dashboards we need with the kustomization we need
kind: Build
type: exec
name: kustomization
include:
 - kustomization/**/*.yaml
```

### Your environment

* **OS:** macos
* **How I'm running Kubernetes:** orbstack
* **Garden version:** 0.13.17

### Frequency

Reproducable

### Workaround

Define the `targetPath`

### Additional context

According to the docs, the `targetPath` is optional: https://docs.garden.io/reference/action-types/build/exec#copyfrom-.targetpath
