### ISSUE TITLE
0.13: [Bug]: deploy actions resolve template strings in manifests in a way that breaks for multi-line strings 

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5266]
### Current Behavior
Error cannot parse yaml with multiline string in variable templated to a manifest file

### Expected behavior

Should work.

### Reproducible example

manifest:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  hello: ${var.multiline-var}
```

deploy action:
```yaml
kind: Deploy
type: kubernetes
name: multiline-var-in-manifest-deploy
spec:
  files: [ "deployment.yml" ]
variables:
  multiline-var: |
    this is a
    multiline
    variable
  foo: bar
```

### Workaround

Works with inline manifest

### Suggested solution(s)

Resolve variables after parsing 

### Your environment

* **OS:** macos
* **How I'm running Kubernetes:** orbstack

`garden version` latest main
