### ISSUE TITLE
0.13: [Bug]: Module task with `podSelector` does not work with 0.13

### ISSUE THREAD

**Issue by shumailxyz** [garden-io/garden#5269]
### Current Behavior

If a `task` in a `module` specifies `podSelector`, it doesn't work in bonsai with the following error message:

```
Error validating spec for Run type=kubernetes-pod name=task-foo (from module test-tasks):
"podSelector" can't be specified with "kind"
object at spec.resource can only contain one of [kind, podSelector]
```

### Expected behavior

Task should work fine.

### Reproducible example

Run `garden run task-foo` with the following project and module:

project.garden.yml
```
apiVersion: garden.io/v1
kind: Project
name: repro-task-to-run
environments:
  - name: local
providers:
  - name: local-kubernetes
    environments: [local]

```

garden.yml
```
kind: Module
name: test-tasks
description: task bug in bonsai
type: kubernetes
allowPublish: false
include: []
timeout: 120
manifests:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: test-app
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: nginx
      restartPolicy: Never
tasks:
  - name: task-foo
    description: This will take a backup of assets + database
    timeout: 1200
    resource:
      podSelector:
        app: test-app
    dependencies:
      - test-tasks
    command:
      - '/bin/bash'
      - '-c'
      - 'echo hello'

```

### Workaround

Don't know of any.

### Additional context

Could be an issue with conversion of tasks to run.

### Your environment

* **OS:** mac
* **How I'm running Kubernetes:** minikube

`garden version`
0.13.17
