### ISSUE TITLE
0.13: [Bug]: Garden does not validate provider environments

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#5276]
### Current Behavior

Garden does not error when a provider is used in an environment that doesn't exist.

### Expected behavior

I'd expect it to fail with the message that the environment doesn't exist since otherwise it can hav cascading downstream issues that are hard to debug.

### Reproducible example

Add the following bad provider config to some example project and then run `garden validate`:

```yaml
providers:
  - name: kubernetes
    environments: [bad-environment]
 ```

### Your environment

`garden version` Latest main as of writing.
