### ISSUE TITLE
garden.yml files are not detected in folders containing dashes

### ISSUE THREAD

**Issue by NoiSek** [garden-io/garden#5346]
### Current Behavior

When scanning child directories of a project for `garden.yml` files, Garden does not scan the folder at all if the name contains a dash.

### Expected behavior

Garden should scan and load files from any directory as long as it is a valid file path.

### Reproducible example

`garden.yml` in `project/foo-dir`:
```
kind: Deploy
type: container
name: redis
description: Redis service for queueing votes before they are aggregated
spec:
  image: redis:alpine
  ports:
    - name: redis
      protocol: TCP
      containerPort: 6379
```

Running `get deploys` from the `garden dev`  CLI will show no resources. Renaming the directory to use underscores (`project/foo-dir` -> `project/foo_dir`) will immediately cause the deployment to be visible.

### Workaround

Alias existing directories to underscores.

### Suggested solution(s)

Examine whatever file watching daemon is being used that prevents directories from loading and ensure there is no stripping of dashes.

### Additional context

Dashes in repo names is a very common convention for git repo names, and submodules are a common usecase with Garden. If you're starting out and attempting to build your first project from existing repositories, this is a pain to troubleshoot given that it fails silently.

### Your environment

* **OS:** OS X - Ventura - 13.0.1
* **How I'm running Kubernetes:** k3d
* **`garden version`**: 0.13.18
