### ISSUE TITLE
`garden.yml` files are not detected in manually cloned git repositories

### ISSUE THREAD

**Issue by NoiSek** [garden-io/garden#5347]
### Current Behavior

When scanning child directories of a project for `garden.yml` files, Garden does not detect / scan `garden.yml` files if the child directory contains a valid `.git` directory and has not been added explicitly as a remote source.

### Expected behavior

Garden should either:
A) Account for manually cloned directories by checking if it is within the configuration, then scan and load files from the directory as normal
B) Explicitly disallow child repos without an annotation in the configuration, and surface that behavior with an error in the logs rather than failing silently.

#### 1. Clone an arbitrary repo. In this case, a minimal HTML template Hello World:
`git clone https://github.com/Azure-Samples/html-docs-hello-world.git`

#### 2. Create a `garden.yml` file at the root of the above cloned repo
```
kind: Deploy
type: container
name: redis
description: Redis service for queueing votes before they are aggregated
spec:
  image: redis:alpine
  ports:
    - name: redis
      protocol: TCP
      containerPort: 6379
```

### Workaround

Add child repos as explicit project sources.

### Suggested solution(s)

Add messaging around this scenario so that the root cause is clear, if it cannot be mitigated for practical reasons.

### Additional context

Testing with cloned repos initially is probably a common usecase with Garden. If you're starting out and attempting to build your first project from existing repositories, this is a pain to troubleshoot given that it fails silently.

### Your environment

* **OS:** OS X - Ventura - 13.0.1
* **How I'm running Kubernetes:** k3d
* **`garden version`**: 0.13.18
