### ISSUE TITLE
taskPending event emitted when it shouldn't

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#540]
### Current Behavior

When changing the `services/api/app.py` file in the `vote` example, a `taskPending` event for the `vote` unit test is fired. 

### Expected behavior

Event shouldn't fire.

### Reproducible example

1. Run `garden dev` in the `vote` example.
2. Open the dashboard and browse to the graph page.
3. Change `examples/vote/services/app.py` and save.
4. Notice that the `test.vote.unit` task starts processing. It's also possible to inspect the console logs in the browser or add a log statement here: https://github.com/garden-io/garden/blob/master/garden-service/src/task-graph.ts#L99. 

Furthermore, the `taskComplete` event never fires.

### Additional context

Here's the relevant config for the `vote` service:

```
  tests:
    - name: unit
      args: [npm, run, test:unit]
    - name: integ
      args: [npm, run, test:integ]
      dependencies:
        - api
```

Notice that the `integ` test should run but the `unit` test should not. 

### Your environment

`garden version`

Latest `master`. 

`kubectl version`

N/A

`docker version`

N/A
