### ISSUE TITLE
[FEATURE]: allow exec blocks to have different commands per os

### ISSUE THREAD

**Issue by kroher** [garden-io/garden#5425]
### Background / Motivation

In custom commands and actions it seems like it would be good to allow a way for us to provide a different script for different os/cli versions in the exec block.

A simple case for us would be we'd like to check for the existence of certain files and would run a sh script for linux/mac but a bat script for windows.

### Suggested Implementation(s)

maybe something like this would work if it was some variable available based in the cli package being used:

```
kind: Command
name: some-command
description:
exec:
 ${if garden.cli.os != 'windows'}
  command: ["/bin/sh", "-c", "./tools/garden/check-files.sh"]
${else}
  command: ["./tools/garden/check-files.bat"]
${endif}
```

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by stefreak** [comment]
hi @kroher! Thanks for the feature request. You can already do this using `$if` objects and the `${local.platform}` variable:

```
kind: Command
name: some-command
description:
exec:
  command:
    $if: ${local.platform == "win32"}
    $then: ["./tools/garden/check-files.bat"]
    $else: ["/bin/sh", "-c", "./tools/garden/check-files.sh"]
```
