### ISSUE TITLE
Crash: highlight is not a function

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5443]
### Error message

```
Unable to resolve status for Deploy foo. It is likely missing or outdated. This can come up if the deployment has runtime dependencies that are not resolvable, i.e. not deployed or invalid.
```

and
```
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20highlight%20is%20not%20a%20function

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

TypeError: highlight is not a function
    at highlightYaml (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:214964:12)
    at renderData (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215093:16)
    at file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215002:40
    at Array.map (<anonymous>)
    at combineRenders (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215002:22)
    at formatForTerminal (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215133:12)
    at TerminalWriter.write (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215499:21)
    at RootLogger.log (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:309828:24)
    at CoreLog.log (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215285:19)
    at CoreLog.info (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:215336:21)

See .garden/error.log for detailed error message
```

### What did you do?

ran `garden get status` with this config:

```
# garden.yml
apiVersion: garden.io/v1
kind: Project
name: foo
environments:
  - name: local

---
kind: Build
type: exec
name: foo
spec:
  command: [echo, "hello world"]


---
kind: Deploy
type: exec
name: foo
spec:
  deployCommand: [echo, "${actions.build.foo.outputs.log}"]

---

kind: Test
type: exec
name: foo
dependencies:
 - deploy.foo
spec:
  command: [echo, "Success"]
```

### Your environment

* **OS:** macOS
* **Garden version:** 0.13.20

### Frequency

Reproducable

### Workaround

Unknown
