### ISSUE TITLE
Unnecessary config version change can happen when the list of excluded paths is modified

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#5519]
## Bug

Container modules get rebuilt when the [exclude](https://docs.garden.io/v/acorn-0.12/reference/module-types/container#exclude) files are modified.

From the docs:
>Files that match these paths or globs are excluded when computing the version of the module, when responding to filesystem watch events, and when staging builds.

However, making changes in the excluded paths list can cause some unnecessary action/module version changes. In that case, the module is rebuilt when it should not be. But the built images have the same digest, therefore no new images are pushed to the registry, instead, the already existing image in the registry is tagged with yet another version.

### Issue

If the `excluded: ` list is modified it's natural to expect some changes in the build context and the module version. However, the modification of the `exclude: ` should not affect the module version if it does not change the actual build context. For instance, if a non-existing file is added to the `excluded: ` list.

### Current Behavior

Adding a non-existing file the the `excluded: ` list triggers the module version change and a new build job.

### Expected Behavior

The module version should remain the same.

### Reproducible example

```yaml
apiVersion: garden.io/v1
kind: Project
name: repro
environments:
  - name: local
  - name: remote
    defaultNamespace: ${var.userId}
providers:
  - name: local-kubernetes
    environments: [local]
variables:
  userId: ${local.username}

---
kind: Build
type: container
name: name
exclude:
  - ./dir1
  - ./file1
```

1. Run `garden build`
2. Add a non-existing file to the `excluded: ` list, e.f. `./dir-that-do-not-exist`
3. Run `garden build again`

### Suggested solution(s)

Module or action config hash is computed based on 2 entities:
- configuration hash
- Git tree version hash

The `include` and `exclude` config entries are resolved while the Git tree version calculation. Thus, those can be excluded from the config hash calculation.

Fix the action config hash calculation to omit `include` and `exclude` config entries. Consider omitting the other config fields that are not important for versioning and can have the same effect. That can help to fix #5501.

See `BaseAction.configVersion()`.

The module version calculation already excludes the necessary config fields, see function `hashModuleVersion`.

### Workaround

Not found.

### Your environment

This is an environment-agnostic issue. It comes from the Core framework and version calculation logic.

`garden version 0.12.66`
`garden version 0.13.18`
