### ISSUE TITLE
Feature request: Clickable URLs on "garden get status"

### ISSUE THREAD

**Issue by l-korbes** [garden-io/garden#557]
`garden get status` gives in output like:

```yaml
    ingresses:
      - path: /hello-go
        port: 80
        hostname: simple-project.192.168.99.101.nip.io
        protocol: http
```

From this I know I can piece things together and use http://simple-project.192.168.99.101.nip.io/hello-go to access my service. Can we make it also output things in such a way that makes the URL clickable in most terminals?
