### ISSUE TITLE
Remote Action broken in version 0.13.20

### ISSUE THREAD

**Issue by sbulman** [garden-io/garden#5624]
## Bug

When I upgraded garden-cli from version 0.13.18 to 0.13.23 my remote container build actions no longer work. I downgraded the versions and found the change in behaviour is from version 0.13.19 (works) to 0.13.20 (does not work).

The config is similar to this

```
kind: Build
    type: container
    name: whatever-proxy-image
    description: Container proxy image for whatever
    source:
      repository:
        url: https://whatever#master
    spec:
      localId: whatever-proxy
```

where the whatever git repository contains a Dockerfile in the root folder.

### Current Behavior

When I run garden build (using 0.13.20) I get the following error message:

```Dockerfile not found at Dockerfile for build whatever-proxy-image.```

### Expected behavior

When I run garden build (using 0.13.19) the build is successful.

### Additional context

I suspect this has something to do with spec.dockerfile. If I set it explicitly I get the same error:

```
kind: Build
    type: container
    name: whatever-proxy-image
    description: Container proxy image for whatever
    source:
      repository:
        url: https://whatever#master
    spec:
      localId: whatever-proxy
      dockerfile: Dockerfile
      ^^^^^^^^^^^^^^^^
```

### Your environment

* **OS:** macOS Sonoma 14.2.1
* **How I'm running Kubernetes:** Docker Desktop
* **garden version:** 0.13.20
