### ISSUE TITLE
0.13: [Bug]: Module conversion: Build dependency missing in Deploy action converted from Module service

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5667]
### Current Behavior
Converted deploy action from module is missing build dependencies.

When running `garden deploy`, the `test-image` build action does not get triggerered.

### Expected behavior

`garden deploy` should also trigger the build `test-image`

### Reproducible example

```
# In foo.dockerfile
FROM nginx:latest
```

```
# In garden.yml
kind: Module
type: container
name: test-image
dockerfile: foo.dockerfile

---

kind: Module
type: container
name: test-deploy
build:
  dependencies: [test-image]
image: '${modules.test-image.outputs.deployment-image-id}'
services:
 - name: "test-deploy"
```

Then run `garden deploy`

### Workaround

Convert to actions

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** local-kubernetes

`garden version` 0.13.23-edge-bonsai-ce02590d3
