### ISSUE TITLE
[FEATURE]: `copyFrom` option for `deploy`  kind actions

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5669]
### Background / Motivation

I need to maintain a patched version of a helm chart to be able to deploy it using garden (see #3962).

I've created a build step to do this that generates the patched chart without needing to check the source code into my repo. I pull the code (using the `vendir` tool) and then apply the patches (using `quilt`):

```yaml
---
kind: Build
type: exec
name: jupyterhub-helm-vendor
description: Set up and patch vendored jupyterhub chart

include:
  - vendir.yml
  - vendir.lock.yml
  - vendor
spec:
  command:
    - bash
    - "-c"
    - |

      # vendor the helm chart, according to vendir.yml
      vendir sync

      pwd

      # apply the patches
      cd vendor/jupyterhub
      quilt push -a
```

I like that this just stays in the build context and I thought I could just request it for downstream jobs.

Before I used the `copyFrom` option in downstream build options to selectively add files from another build step into my current build context. However now I just want to deploy this patched chart and there is no `copyFrom` option. It seems the "correct" way to do this is to instead specify the `build` option which sets your source location to the build context. So I try this:

```yaml
---
kind: Deploy
type: helm
name: jupyterhub-deploy
description: Deployment of JupyterHub

dependencies:
  - build.jupyterhub-helm-vendor

# use this build context
build: jupyterhub-helm-vendor

include:
  - ./jupyter-hub_values_${environment.name}.yaml

spec:
  releaseName: ${var.helm_release_names["jupyter"]}
  chart:
    path: vendor/jupyterhub/jupyterhub/helm

  valueFiles:
    - ./jupyter-hub_values_${environment.name}.yaml

```

However the included `jupyter-hub-values_${environment.name}.yaml` is not in the context.

This makes sense since garden wouldn't know how to cleanly merge the build context and the `jupyterhub-deploy` context.

The workaround is simply to add the values file into the build context, even though it really isn't needed there.

```yaml
---
kind: Build
type: exec
name: jupyterhub-helm-vendor
description: Set up and patch vendored jupyterhub chart

include:
  - vendir.yml
  - vendir.lock.yml
  - vendor
  - ./jupyter-hub_values_${environment.name}.yaml

[...]
```

### What should the user be able to do?

User should be able to specify a `copyFrom` section in Deploy actions, and probably every other kind of action too. 

### Why do they want to do this? What problem does it solve?

This allows for a clear specification of what files are needed in the specific action that is being performed.

This would also allow for non-Build action types to be able to combine multiple Build action results for deployment, without needing an intermediate Build to combine them.

Some other details that should be implemented that were not clear in troubleshooting the above problem:

1. If an explicitly included file is not added to the context this should be an error (e.g. you specify `build`)

### Suggested Implementation(s)

E.g. same syntax as Build action for Deploys:

```yaml
---
kind: Deploy
type: helm
name: jupyterhub-deploy
description: Deployment of JupyterHub

dependencies:
  - build.jupyterhub-helm-vendor

include:
  - ./my-values.yaml
 
copyFrom:
  - build: jupyterhub-helm-vendor
    sourcePath: vendor/jupyterhub/jupyterhub/helm
    targetPath: _chart
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment]
Hi @salotz 

Thanks for the feature request. 

This whole build context business has been a bit painful, both for users (e.g. using `includes` and the `build` field) and maintainers, and we've actually been considering deprecating it. 

It makes sense that you wouldn't want the patched Helm chart in version control but how about putting it in some tmp dir that you can git ignore?

Just from the top of my head:

```
---
kind: Run # <--- Use Run instead of Build
type: exec
name: jupyterhub-helm-vendor
description: Set up and patch vendored jupyterhub chart

# Skip includes and just run the command in the source dir where all the files are available
# Need to ensure that the `vendir` config writes to somethig like `.helm-patches` that are git ignored
spec:
  command:
    - bash
    - "-c"
    - |

      # vendor the helm chart, according to vendir.yml
      vendir sync

      pwd

      # apply the patches
      cd vendor/jupyterhub
      quilt push -a

---
kind: Deploy
type: helm
name: jupyterhub-deploy
description: Deployment of JupyterHub

dependencies:
  - run.jupyterhub-helm-vendor

spec:
  releaseName: ${var.helm_release_names["jupyter"]}
  chart:
    path: vendor/jupyterhub/jupyterhub/helm

  valueFiles:
    - ./.helm-patches/jupyter-hub_values_${environment.name}.yaml
```

I'm not super familiar with `vendir` so maybe I messed something up here but this would be the general idea.

If you can pass the Helm temp dir as CLI flag to `vendir` you can create a variable for it so that it's used consistently in both actions. 

I personally think this is a lot less magic then using the kind of hidden `.garden/build` dir and worrying about getting your includes correctly. 

Also, note that if your Garden config file is in a sub directory relative to the tmp Helm dir you can set the action root to the project root, e.g.:

```
# In ./jupyter-stuff

kind: Deploy
type: helm
name: jupyterhub-deploy
source:
  path: ../ # <-- Set the source to the root

spec: 
  valueFiles: ./.helm-patches/... # <--- Pick the value files relative to the root becaus we set source.path above
```
