### ISSUE TITLE
Improve docs and context of error message for invalid kubernetes-pod configuration

### ISSUE THREAD

**Issue by porterchris** [garden-io/garden#5682]
### Current Behavior

The expected `spec` configuration for `Test` / `kubernetes-pod` is not clearly defined in the docs:
https://docs.garden.io/kubernetes-plugins/actions/run-test/kubernetes-pod

An invalid configuration can lead to a crash. The code as defined expects that the podSpec must have a container defined, if that container is not defined the code hard crashes and leaves a cryptic message:
```
  const spec = action.getSpec()

  let podSpec = spec.podSpec
  let container = spec.podSpec?.containers[0]
```
https://github.com/garden-io/garden/blob/89d5396a671e91879dfb71f0a20a4056a0c38339/core/src/plugins/kubernetes/kubernetes-type/common.ts#L540-L543 

### Expected behavior

1) The `spec` format for `Test` / `kubernetes-pod` should be better defined in the docs to indicate the intended format of `spec.podSpec.containers`, and that only the first container will be used. The docs do provide a list of fields that can exist as children of `podSpec`: https://docs.garden.io/reference/action-types/run/kubernetes-pod#spec.podspec
but a practical example here: https://docs.garden.io/kubernetes-plugins/actions/run-test/kubernetes-pod
could lead to less confusion. The `containers` field should be listed as required if it is intended to be used whenever `podSpec` is used.

2) An invalid `spec` should not crash the application but should give the user feedback on the expected format. A check for the length of `containers` in `spec.podSpec?.containers[0]` could be used to inform the user that the expected configuration was not found.

### Reproducible example

Works
```
kind: Test
name: my-test
type: kubernetes-pod
dependencies:
  - build.my-test
spec:
  podSpec:
    containers:
      - name: my-test
        image: ${actions.build.my-test.outputs.deployment-image-id}
```

Should not work, but should throw a more meaningful error message:
```
kind: Test
name: my-test
type: kubernetes-pod
dependencies:
  - build.my-test
spec:
  podSpec:
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-test-pod
      spec:
        containers:
          - name: my-test
            image: ${actions.build.my-test.outputs.deployment-image-id}
```

### Workaround

Use a _valid_ `podSpec` once you determine what is expected.

### Suggested solution(s)

Add documentation/examples and improve the context provided by the error messaging when the expected configuration format is not found.

### Your environment
```
macOS Ventura 13.6.3
EKS & Orbstack
garden version: 0.13.23
```
