### ISSUE TITLE
Documentation: if-else semantics

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5731]
The description [here](https://docs.garden.io/using-garden/variables-and-templating#if-else-conditional-objects) is really incomplete in using the if/else templating.

For instance its not clear about how this actually gets expanded and the example only covers lists.

For instance it is really confusing that this doesn't work:

```yaml
group:
  normal_key: 1
  $if: true
  $then:
    some_other_key: 0
``` 

or

```yaml
group:
  - item1
  $if: true
  $then:
    - item2
```

When you actually must put in the map/list in all or nothing like:

```yaml
group:
  $if: true
  $then:
    normal_key: 1
    some_other_key: 0
  $else:
    normal_key: 1
```

I don't like the duplication that occurs because of this (another issue perhaps) but would be good to at least have the current behavior documented and show some useful examples of the most common gotcha. Feel free to use these examples!

**Comment by twelvemo** [comment]
Thanks for filing this issue, we really care about documentation and are super happy about feedback there.

**Comment by stefreak** [comment]
@salotz you can use the `$merge` and `$concat` operators to prevent duplication:

```
group:
  normal_key: 1
  $merge:
    $if: true
    $then:
      some_other_key: 0
```

and 
```
group:
  - item1
  - $concat:
      $if: true
      $then:
        - item2
```
