### ISSUE TITLE
[FEATURE]: Template helm values files

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5739]
### Background / Motivation

I was trying to template `values.yaml` files for helm with garden template expansion. This doesn't seem to work.

### What should the user be able to do?

Same as manifests the `valueFiles` should also support garden templates.

### Why do they want to do this? What problem does it solve?

The workaround is to use the `values` section but as mentioned in some other issues (#5738 ) this is severely limited once you have more than 2 different cases/environments.

Also the `values` section can get very large and overtakes the rest of the config.

### Suggested Implementation(s)

N/A

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by thsig** [comment]
Thanks for writing this up!

I wonder if a similar approach to `patchResources` could be taken here, i.e. something like:
```yaml
kind: Deploy
type: helm
name: some-service
spec:
  mergeValues: true # <----
  values:
    some:
      deeply:
        nested:
          value: ${var.someOverride}
```
The `mergeValues` option could be implemented as follows:
* Resolve the `values` in the action config
* Read the values file
* Merge in the paths/values from `values`
* Write the resulting values to a file and pass that to `helm`
That way, you wouldn't have to duplicate your whole values file, and could just override the parts you're interested in.

Does that sound like a reasonable flow?
