### ISSUE TITLE
TypeError when running call command without a path when no ingress is defined

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#580]
## Bug

If a service doesn't have any ingresses and is called with out a specific path via the `call` command, we get the following TypeError: `Cannot read property 'path' of undefined`.

Note that this only applies if the path is missing. E.g.:

```
g call node-service/hello-node

Service node-service does not have an HTTP/HTTPS ingress at /hello-node
```

as expected, whereas:

```sh
g call node-service

Cannot read property 'path' of undefined
```
returns a `TypeError`.

### Current Behavior

`TypeError` if no ingress and path missing.

### Expected behavior

Should return a `GardenError`, same as when calling with a path.

### Reproducible example

1. Open `simple-project``
2. Remove ingresses from `services/node-services/garden.yml`
3. Run `garden call node-service`

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

Latest master

**Comment by JordyBaylac** [comment]
Hi, could you please share the **garden.yml**? I have checked and the error 
`Service ${service.name} has no active ingresses` should be emitted if no ingress is specified. I could replicate the issue but passing `ingress: []`

**Comment by eysi09** [comment]
Here's a `garden.yml` for the `node-service` of the `simple-project` without ingresses:

```yaml
module:
  name: node-service
  description: Node service container
  type: container
  services:
    - name: node-service
      ports:
        - name: http
          containerPort: 8080
      dependencies:
        - go-service
  tests:
    - name: unit
      args: [npm, test]
    - name: integ
      args: [npm, run, integ]
      dependencies:
        - go-service
```

Running `garden call node-service` with this config results in the error.
