### ISSUE TITLE
0.13: [Bug]: Template variables are being interpolated on input values

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5825]
### Current Behavior

The action prints the literal text `I shouldn't be here.`.

### Expected behavior

I expect the action to print the literal text `${local.env.UNINVOLVED_VAR}`

### Reproducible example

Run `UNINVOLVED_VAR="I shouldn't be here." INCONSPICUOUS_VAR='${local.env.UNINVOLVED_VAR}' garden run debug` with this `garden.yml`:
```
apiVersion: garden.io/v1
kind: Project
name: foo

environments:
  - name: dev

providers: []

---
kind: Run
type: exec
name: debug
spec:
  command:
  - echo
  - '${local.env.INCONSPICUOUS_VAR}'
```

### Workaround

None available

### Suggested solution(s)

Parse templates into an abstract representation, and from there do not interpolate template strings anymore on any of the intermediate evaluation results.

### Additional context

Unfinished, but this would fix this: https://github.com/garden-io/garden/pull/5496

### Your environment

* **OS:** all

`garden version` Bonsai and Acorn affected.
