### ISSUE TITLE
[FEATURE]: Run all components of a ConfigTemplate

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5831]
### Background / Motivation

Using ConfigTemplates

### What should the user be able to do?

If I have a ConfigTemplate e.g.:

```yaml
---
kind: ConfigTemplate
name: tanka-export
inputsSchemaPath: tanka-export_schema.json

configs:

  - kind: Build
    name: ${parent.name}
    type: exec
    description: |
      Render K8s manifests using Tanka.

    include:
      - ${inputs.environment}
      # everything we need for tk to run
      - chartfile.yaml
      - charts
      - jsonnetfile.json
      - jsonnetfile.lock.json
      - lib
      # we need this but skip the symlinks that tanka maintains
      - vendor/github.com

    spec:
      shell: true
      command:
        - |
          tk export ./export/${inputs.name} ${inputs.environment}
          # remove this for downstream things that choke on this
          rm ./export/${inputs.name}/manifest.json
  
```

I should be able to run all the sub-components it generates by the name of the action that expands it, e.g. for:

```yaml
---
kind: RenderTemplate
template: tanka-export
name: kapp-example-export
inputs:
  environment: ./environments/kapp-example
  name: kapp-example

```

```
garden do-template kapp-example-export
```

Should run all the generated actions.
Currently I have to know how the name is generated and run that:

```
garden build kapp-example-export
```

Which is why I don't format the name, otherwise its too confusing.

### Why do they want to do this? What problem does it solve?

Using ConfigTemplates could easily become confusing without external documentation. I.e. the `RenderTemplate` isn't self-documenting on usage.

### Suggested Implementation(s)

The ConfigTemplate could figure out the kind and names of the actions and just run them all for you. 

### How important is this feature for you/your team?

Between these two as I'm not depending on ConfigTemplate too much at this point:

🌵 Not having this feature makes using Garden painful

🌹 It’s a nice to have, but nice things are nice 🙂
