### ISSUE TITLE
[FEATURE]: RenderTemplate descriptions.

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5832]
### What should the user be able to do?

```yaml
---
kind: RenderTemplate
template: tanka-export
name: kapp-example-export
description: |
  Render and export the kapp-example
inputs:
  environment: ./environments/kapp-example
  name: kapp-example

```

### Why do they want to do this? What problem does it solve?

The only descriptions left are the ones inside the ConfigTemplate. The descriptions are great for explaining the why of an action and I can't do this in the RenderTemplate.

I can use comments though.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
