### ISSUE TITLE
Unclear overrides of `kubernetes-pod` `podSpec` fields

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#6069]
### Current Behavior

I have a `kubernetes-pod` similar to the following:

```
kind: Run
type: kubernetes-pod
[...]
spec:
  cacheResult: True
  podSpec:
    volumes:
      - name: credentials-vol
        secret:
          secretName: secname

    containers:
      - name: main
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
        volumeMounts:
          - name: credentials-vol
            optional: false
            mountPath: /mnt/secret
            readOnly: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /mnt/secret/credentials.json
        command:

```

And I find that it never mounts the volume in the pod.

### Expected behavior

I would expect that the pod would mount the volume since that is normal behavior.

I tried to understand from the documentation what is supported however it is very vague:

> Note that the spec will be modified for the Run, including overriding with other fields you may set here (such as args and env), and removing certain fields that are not supported.

And I found that the `env` section I gave actually did work, so its also counterfactual AFAIU.

### Workaround

I can do a `kubernetes` Deploy then `kubernetes-exec` action or just write out a deployment for the `spec.file` option in `kubernetes-pod`.

### Suggested solution(s)

At minimum some documentation with warnings about what you can and can't do would help as it wastes a lot of time to have to troubleshoot this even after carefully reading the documentation.

### Your environment

* **OS:** OpenSuse Tumbleweed
* **How I'm running Kubernetes:** GKE

`garden version`
garden version: 0.13.30
