### ISSUE TITLE
[FEATURE]: allow failure for workflow tasks

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#6077]
### Background / Motivation

In some cases I want to run a workflow task that I know might fail for various reasons (see #6076 but also others).

### What should the user be able to do?

In the workflow step you should be able to specify whether a step is allowed to fail without the entire workflow exiting as failure.

### Suggested Implementation(s)

```
kind: Workflow
steps:
  - name: can-fail
    command: [...]
    allowFailure: true
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
