### ISSUE TITLE
Allow multiple module definitions in one file

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#61]
To quote @eysi09 from #55:

Something like:

```
project:
  name: hello-world
  environments: ...
modules:
  - name: module-a
     dir: /path/to/module-a
     description: Module A description
     type: container
  
  - name: module-b
     dir: /path/to/module-b
     description: Module B description
     type: container
```

I think this will make sense especially when we allow referencing other git repos, which we'll need to do soon.
