### ISSUE TITLE
[FEATURE]: Wait to start container until initial file syncs complete

### ISSUE THREAD

**Issue by westrik** [garden-io/garden#6113]
### Background / Motivation

We have configured our Garden local dev setup is run `sleep 30` before starting our backend dev server. We do this to wait until the initial file syncs have completed and avoid errors caused by missing files. 

This is not ideal because we need to hard-code a wait time greater than the worst-case initial sync time, so in most cases we are sleeping an unnecessarily long amount of time. This is also brittle because the initial sync time may increase as more files are added.

### What should the user be able to do?

Users should be able to configure Garden to wait to run a container's startup command until the inital file sync(s) have completed.

### Why do they want to do this? What problem does it solve?

Users may want a reliable way to avoid starting a container until all files it needs to run have been synced. 

### Suggested Implementation(s)

Perhaps a `waitForInitialSync` option could be added to a container spec, e.g.:

```
spec:
  containers:
    - command:
        - bash
        - dev-server.sh
      waitForInitialSync: true
      # ...
```

Or maybe a `blockStartup` option could be added to the sync config:

```
devMode:
  sync:
    - target: /src
      source: '.'
      mode: one-way-replica
      blockStartup: true
    # ...
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
