### ISSUE TITLE
Varfiles with "type: helm" and sources.repository.url not working

### ISSUE THREAD

**Issue by ManAnRuck** [garden-io/garden#6146]
### Current behavior

env file not found (is looking in wrong directory for the varfiles in .garden/sources/…)
```sh
Error processing config for Deploy action redis:
Could not find varfile at path './.env'. Absolute path: /…/garden/examples/redis/.garden/sources/action/deploy.redis--88237447a8/.env
```

### Expected behavior

varfiles should be searched within the action directory

### Reproducible example

garden.yml
```yaml
apiVersion: garden.io/v1
kind: Project
name: redis
environments:
  - name: local
    variables:
      baseHostname: redis.local.demo.garden
providers:
  - name: local-kubernetes
    environments: [local]
variables:
  userId: ${kebabCase(local.username)}

```
redis.garden.yml
```yaml
kind: Deploy
description: Redis service for queueing votes before they are aggregated
type: helm
name: redis
varfiles:
  - ./.env
source:
  repository: 
    url: https://github.com/bitnami/charts#main
spec:
  chart:
    path: bitnami/redis
  values:
    auth:
      enabled: false

```
.env
```
TEST=test
```

```sh
garden dev
garden deploy
```

### Workaround

don't use varfiles

### Suggested solution(s)

varfiles location should be relative to the action yaml definition file

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** docker desktop

`0.13.30`
