### ISSUE TITLE
0.13: [Bug]: Describe here

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#6150]
## Garden Bonsai (0.13) Bug

String template resolution fails with a non-informative error when a variable references a non-existing command-line parameter via`${command.params.<name>}`

### Current behavior

Garden fails with a verbose and too-technical error message.

### Expected behavior

The should message must be clear and user-friendly.

### Reproducible example

<details>

<summary>Click to expand the <b>Garden config `garden.yml`</b></summary>

```yml
kind: Project
apiVersion: garden.io/v1
name: kraken
defaultEnvironment: dev
variables:
  env: ${split(command.params.env, ".")}
environments:
  - name: dev

---

kind: Run
name: print-all
description: Print details
type: exec
spec:
  command: ["sh", "-c", "echo 'The --env is: ${var.env}'"]
```

</details>

Run the command:
```console
garden run print-all
```
and observe the error output:
```console
Failed to resolve project configuration.

Invalid template string (${split(command.params.env, ".")}) at path variables.env: Error validating argument 'string' for split helper function:

value must be a string
```

#### Alternative scenario

If you skip the variables block
```yaml
variables:
  env: ${split(command.params.env, ".")}
```
in the project-level config, and reference the command-line arg direct from the Run-action as follows
```yaml
spec:
  command: ["sh", "-c", "echo 'The --env is: ${command.params.env}'"]
```
then Garden will fail with a different error (raised from a different code place) that is more meaningful and user-friendly:
```console
✖ run.print-all             → Failed processing resolve Run type=exec name=print-all (took 0 sec). This is what happened:

Invalid template string (echo 'The --env is: ${command.params.env}') at path command.2: Could not find key env under command.params. Available keys: $all, --, emoji, force, force-build, force-refresh, help, log-level, names, show-timestamps, silent, skip-dependencies, version, watch and yes.

1 requested run action(s) aborted!
```

### Workaround

Ensure that the value referenced by a variable always exists.

### Suggested solution(s)

* Consider validating the `command.*` references before allowing using them in the variables
* Consider aligning the error message and behaviour between the reproducible example above and its alternative scenario.

### Additional context

See the [original Discord thread](https://discord.com/channels/817392104711651328/1243341282236043294/1243341282236043294).

`garden version 0.13.x`
