### ISSUE TITLE
0.13: [Bug]: Docker Container build is breaking

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#6199]
Getting the following error while running the container build and trying to publish it to artifact registry.
It was running and tested in `0.12` version while breaking in `0.13.31`

> Command "/home/runner/.garden/tools/mutagen/c8f927f6b7e9b6c5/mutagen sync create /runner/_work/workstation/thxcs-shared-services/.garden/build/file-browser-publish-image exec:'/home/runner/.garden/tools/kubectl/1c77e14905cf9f14/kubectl exec -i --context=gke_context --namespace=enabling-services-thx --container util Deployment/garden-util -- /.garden/mutagen-agent synchronizer':/data/96f3e751-1cb5-44a5-9926-ddcf6dc838eb/file-browser-publish-image --name k8s--build-sync--dev--enabling-services-thx--file-browser-publish-image--mo6cjxgg --sync-mode one-way-replica --default-file-mode 0644 --default-directory-mode 0755" failed with code 1:
> 
> Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: error: The gcp auth plugin has been removed.
> Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
> See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details)
> 
> Here's the full output:
> 
> Connecting to agent (POSIX)...
> Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to handshake with agent process: unable to receive server magic number: EOF (error output: error: The gcp auth plugin has been removed.
> Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
> See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details)

Following configuration
```
kind: RenderTemplate
template: scripts-docker-container-module-template
name: file-browser
inputs:
  includeFiles: 
    - "Dockerfile"
    - "start.sh"
  dockerBuildArgs: {service=file-browser}
  customEntryPoint: true
```

```
kind: ConfigTemplate
name: scripts-docker-container-module-template
inputsSchemaPath: rest.schema.json
modules:
  - type: container
    name: ${parent.name}-publish-image
    description: ${parent.name} image build stage
    include: ${inputs.includeFiles}
    image: ${var.dockerRepo}/${parent.name}
    buildArgs: ${inputs.dockerBuildArgs}

```
