### ISSUE TITLE
0.13: [Bug]: Template: Arithmetic binary operators do not work together with variable lookup

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#6201]
### Current behavior
`garden run my-test` prints this error:

```console
Invalid template string (${var.prefix.suffix * 4}) at path spec.command.1: Both terms need to be numbers for * operator (got string and number).
```

### Expected behavior
`garden run my-test -l3` should print this stdout from the run, the multiplication should work:
```
8
```

### Reproducible example

The issue happens with all arithmetic operators, i.e. `+`, `-`, `*`, `/`, and others (modulo, comparison, etc.).

```
apiVersion: garden.io/v1
kind: Project
name: project
defaultEnvironment: local
dotIgnoreFile: .gitignore
environments:
  - name: local
---
kind: Run
type: exec
name: my-test
spec:
  command: [echo, '"${var.prefix.suffix * 4}"']
variables:
  prefix:
    suffix: 2
```

### Workaround
Skipping the variable lookup makes the multuplication work, but that's not really a workaround in most cases

```
  command: [echo, '${2 * 4}']
```

### Additional context
It is not the problem that the YAML value is being read as a string. If you use jsonDecode it also happens:

```
apiVersion: garden.io/v1
kind: Project
name: project
defaultEnvironment: local
dotIgnoreFile: .gitignore
environments:
  - name: local
---
kind: Run
type: exec
name: my-test
spec:
  command: [echo, '${jsonDecode(var.prefix.suffix) * 4}']
variables:
  prefix:
    suffix: 2

```

### Suggested solution(s)
N/A

### Your environment

`garden version: 0.13.31`
