### ISSUE TITLE
0.13: [Bug]: Jib Container picks a wrong deployment image id while building images

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#6204]
The JIB Build action's `name` is used an a local image name in `jib-container` while migration from 0.12.55 to 0.13.31 version. The image name should be taken from `image` config field if it's specified.

### Expected behaviour

The value of the `-Djib.to.image` in the underlying Maven build command should be:

```console
-Djib.to.image=us-docker.pkg.dev/th-thx-common/docker-repo/spring-boot-1:v-a36c7e187b
```

### Current behaviour

The value of the `-Djib.to.image` in the underlying Maven build command is:

```console
-Djib.to.image=us-docker.pkg.dev/th-thx-common/docker-repo/spring-boot-1-image:v-a36c7e187b
```

#### `ConfigTemplate`:
```yaml
modules:
  - type: jib-container
    name: ${parent.name}-image
    description: Backend service
    disabled: ${inputs.disabled}
    include: 
      - ./**/src/**/*
      - pom.xml
      - ./**/pom.xml
    image: ${parent.name}
    extraFlags: 
    - -Djib.useOnlyProjectCache=false
    - "-Djib.from.image=${var.dockerRepo}/${inputs.jdkVersion == '11' ? var.baseImageJava11 : var.baseImageJava8}"
    - "-nsu"
    - "-Dtransitive=false"

    build: 
      jdkVersion: ${inputs.jdkVersion} 
      projectType: maven
      dependencies: ${var.dependencies}?
      mavenPhases: [ "clean", "package" ]
```

#### `RenderTemplate`:
```yaml
kind: RenderTemplate
template: spring-service-module-template
name: spring-boot-1
inputs:
  jdkVersion: "8"
  disabled: ${environment.name != 'dev'}
```

Run the build command:
```console
# Here the 
garden build spring-boot-1-image
```

The output would be:
```
> ℹ build.spring-boot-1-image → [debug] Execing /home/workstation/.garden/tools/maven/cd3b803db0ebc2c5/apache-maven-3.8.8/bin/mvn clean package jib:build -Djib.to.image=us-docker.pkg.dev/th-thx-common/docker-repo/spring-boot-1-image:v-a36c7e187b -Djib.container.args=GARDEN_MODULE_VERSION=v-a36c7e187b,GARDEN_ACTION_VERSION=v-a36c7e187b -Dstyle.color=always -Djansi.passthrough=true -Djib.console=plain -Djib.useOnlyProjectCache=false -Djib.from.image=us-docker.pkg.dev/th-thx-common/-docker-repo/eclipse-temurin:8u382-b05-jre-ubuntu23 -nsu -Dtransitive=false
```

Created the same project having reference of jib-container and docker container which you can use to replicate the issue: https://github.com/ishantagarwal-x213235/garden-sample-project/tree/main

### Your environment

`garden version 0.13.31`

**Comment by vvagaytsev** [comment]
@ishantagarwal-x213235 thanks for reporting this!

At glance, it looks like it might not be related to the `${parent.name}`, it might be related to the Build-handler of the JIB plugin that may use a wrong source to construct the target `deploymentImageId`. 

Unfortunately, the ticker description looks a bit incomplete. In the **Expected/Current Behavior** sections there are references to some generated results, i.e. to the build flags called `-Djib.to.image` that seem to be generated on the basis of the ConfigTemplates and concrete RenderTemplates.

I cannot find anything related to `-Djib.to.image` neither in the issue description, nor in the linked [example project](https://github.com/ishantagarwal-x213235/garden-sample-project/tree/main). Without that, I can't see what variables were used as source values to construct the `-Djib.to.image` outputs.

So, could you please provide a minimalistic reproducible example? Feel free to update the issue description or you test project. In you update the test project, feel free to create a new branch and remote all the irrelevant code and configs. Let's keep the things simple :) It looks like we need 1 project config, 1 config template fir JIB, and 1 render template.

I'll take a closer look on Monday.

By the way, we got another issue report, and it looks very similar.

With a simpler setup, just like
```yaml
kind: Module
type: jib-container
name: service-name-image
image: service-name
```
(and a project config with `deploymentRegistry`),  `garden build` command uses `name` instead of `image` of _JIB_ container  module to publish the built image to the deployment registry.

I'm going to prepare a fix based on a simpler example first, and this one will likely get fixed too.
