### ISSUE TITLE
0.13: [Bug]: --skip-dependencies is not working correctly with garden plugins pulumi preview command

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#6206]
`--skip-dependencies` flag is not working as expected with `garden plugins pulumi preview` command. Ideally, it should ignore the dependencies and execute the module without any dependencies.

Command
`garden plugins pulumi preview --env=dev -- gcs-iam-infra --skip-dependencies`

Expected
Command should only preview the gcs-iam-infra module
Actual
It is looking for the dependencies of gcs-iam-infra and running pulumi preview command for it's dependencies first.

> workstation:~/thx/workspace/infra/gcs-iam$ garden plugins pulumi preview --env=dev -- gcs-iam-infra --skip-dependencies
> Plugins
> 
> ℹ garden                    → Initializing...
> Project is configured with `apiVersion: garden.io/v0`, running with backwards compatibility.
> ⚠ garden-cloud              → You are not logged in. To use Garden Cloud, log in with the garden login command.
> ℹ garden                    → Running in environment dev.default
> Running pulumi preview for actions thx-gcs-iam-infra
> 
> ℹ providers                 → Resolving providers...
> ℹ pulumi                    → Configuring provider...
> ✔ pulumi                    → Provider configured
> ✔ pulumi                    → Provider status cached
> ✔ providers                 → Finished resolving providers (took 0 sec)
> ℹ providers                 → All provider statuses were cached. Run with --force-refresh to force a refresh of provider statuses.
> ℹ providers                 → Resolving providers...
> ℹ exec                      → Configuring provider...
> ✔ exec                      → Provider configured
> ✔ exec                      → Provider status cached
> ✔ providers                 → Finished resolving providers (took 0 sec)
> ℹ providers                 → All provider statuses were cached. Run with --force-refresh to force a refresh of provider statuses.
> ℹ graph                     → Resolving actions and modules...
> ✔ graph                     → Finished resolving graph (took 0.7 sec)
> ℹ garden                    → Finished initializing Garden (took 2.2 sec)
> 
> 
> ℹ deploy.enable-api-infra → Running pulumi preview
> ✖ deploy.enable-api-infra → Failed (took 30.3 sec)
> ℹ deploy.networking-infra → Aborting because upstream dependency failed.
> ℹ deploy.gcs-iam-infra  → Aborting because upstream dependency failed.
> ✖ deploy.enable-api-infra → Failed processing Deploy type=pulumi name=enable-api-infra (from module enable-api-infra) (took 30.35 sec). This is what happened:

Render Template
```
kind: RenderTemplate
template: infrastructure-module-template
name: gcs-iam
inputs:
  dependencies: [networking-infra] 
```

ConfigTemplate
```
kind: ConfigTemplate
name: infrastructure-module-template
inputsSchemaPath: rest.schema.json
modules:
  - type: pulumi
    name: ${parent.name}-infra 
    description: common to all infrastructure deployments
    stack: "${environment.name}"

    createStack: true
    cacheStatus: false
    allowDestroy: true
    autoApply: true
    deployFromPreview: false
    dependencies: ${inputs.dependencies}


    pulumiVarfiles: 
      - "../global.yaml"
      - "config/common.yaml"
      - "config/${environment.name}.yaml"

    build:
      dependencies: ["${parent.name}-package"]

    exclude: ["${parent.name}"]

```

`garden version 0.13.31`
