### ISSUE TITLE
[Bug]: exec run logs duplicate in verbose loglevel

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#6292]
### Current behavior

```
$ garden run proj -l 3
ℹ run.proj                  → [verbose] Hello world
ℹ run.proj                  → [verbose] [echo] Hello world
```

### Expected behavior

```
$ garden run proj -l 3
ℹ run.proj                  → [verbose] [echo] Hello world
```

### Reproducible example

```
apiVersion: garden.io/v1
kind: Project
name: project
defaultEnvironment: local
dotIgnoreFile: .gitignore
environments:
  - name: local
---
kind: Run
type: exec
name: proj
spec:
  command: [echo, "Hello world"]
```

### Workaround
N/A

### Suggested solution(s)

Remove duplicate log emission

### Your environment

* **OS:** Macos

0.13.34
