### ISSUE TITLE
[FEATURE]: Support a Nix Derivation based OCI image builder much like Kaniko is for Dockerfiles

### ISSUE THREAD

**Issue by mattpolzin** [garden-io/garden#6344]
### Background / Motivation

It would be very nice to be able to explore building OCI images via Nix and have that plug into Garden's build/deploy pipeline seamlessly.

I'm not committing to seeing this work through, but I _am_ looking to gauge whether the Garden project would even want such a thing assuming I did find the time to do the implementation myself eventually.

### What should the user be able to do?

Given a Nix file that builds a Docker image (not dissimilar to the very simple one I have pasted immediately below), the user can build & deploy the same as they can today given the simple Dockerfile  shown below.

```nix
{ nixpkgs ? import <nixpkgs> {} }:
nixpkgs.dockerTools.buildImage {
  name = "nginx";
  contents = [nixpkgs.nginx];
}
```

```dockerfile
FROM nginx
```

These examples are of course not representative of how Nix derivations or Dockerfiles handle complexity but there are very real differences between the two approaches for any real-world image.

### Why do they want to do this? What problem does it solve?

Flexibility to not be tied to Dockerfiles as the source code for OCI Images used in deploys.

### Suggested Implementation(s)

I've hacked this together as a proof of concept for myself by reusing most of the Kaniko code. I think the cleanest implementation would indeed look very similar to the Kaniko builder functionality.

The way I've hacked it together is by replacing the Kaniko executor image with the `nixos/nix` image. Then I swapped out the `kanikoCommand` for a `nix-build` command and re-used the `dockerfile` by simply setting it to the name of a `.nix` file. Finally, the `nix-build` command is followed by a `nix-shell` command that runs a `skopeo copy` to copy the OCI tarball produced by Nix to the same destination as Kaniko would have pushed the final image to.

On top of my implementation being hacky and lacking tests, it also disregards Kaniko's ability to push layers for caching -- in an analogous Nix implementation, I would add support for caching all of the Nix store paths used to create the Docker image.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by mattpolzin** [comment]
I cleaned things up a tad on my prototype of this functionality, but it's definitely still prototype quality. If anyone wants to check it out or play with it, it's here: https://github.com/garden-io/garden/compare/main...mattpolzin:garden:remote-nix-builds-exploration

I'll include some files that mostly set up a working Garden project using the new Nix builder. If you build the aforementioned branch and use that Garden executable, the following project works even without Nix installed on your system (after all, the point is that images are built remotely as with Kaniko).

**project.garden.yml**
```yaml
apiVersion: garden.io/v1
kind: Project
name: garden-explorations
defaultEnvironment: local
modules:
  include:
    - "*.garden.yml"
environments:
  - name: local
providers:
  - name: kubernetes
    environments: [local]
    context: docker-desktop
    namespace: test
    imagePullSecrets:
      - name: dockerhub-secret
    nix:
      image: docker.io/nixos/nix
    deploymentRegistry:
      hostname: docker.io
      namespace: <your-dockerhub-namespace>
    buildMode: nix
```

**nginx.garden.yml**
```yaml
kind: Build
description: nginx container
type: container
name: test-nginx
spec:
  nixfile: nginx.nix

---

kind: Deploy
description: nginx
type: container
name: nginx
build: test-nginx
```

This Nix file is not trivial, but only because I went for an `nginx` container that has a simple index.html file packaged in with it. It's actually easier to package e.g. an Elixir service.

**nginx.nix**
```nix
{ nixpkgs ? import <nixpkgs> {} }:
let inherit (nixpkgs) busybox lib writeText runCommand nginx;
    adduser = "${busybox}/bin/adduser";

    files = runCommand "mk-files" {} ''
      mkdir -p $out/share
      echo '<html>hi</html>' > $out/share/index.html
    '';
    nginxConf = writeText "nginx-conf" ''
      events {}
      http {
        server {
          listen        8080;

          location / {
            autoindex on;
            root  ${files}/share;
          }
        }
      }
    '';
in
nixpkgs.dockerTools.buildLayeredImage {
  name = "nginx2";
  enableFakechroot = true;
  fakeRootCommands = ''
    mkdir -p /etc
    touch /etc/passwd
    ${adduser} nginx -H

    mkdir -p /var/log/nginx
    chown nginx /var/log/nginx
    ln -sf /dev/stdout /var/log/nginx/access.log
    ln -sf /dev/stderr /var/log/nginx/error.log

    mkdir -p /tmp
    chown nginx /tmp
  '';
  config = {
    User = "nginx";
    Cmd = [
      "${lib.getExe nginx}"
      "-g"
      "daemon off;"
      "-c"
      "${nginxConf}"
    ];
  };
}
```
