### ISSUE TITLE
[Bug]: Custom Commands Not Working

### ISSUE THREAD

**Issue by txjack** [garden-io/garden#6362]
## Bug
The below custom command is directly taken from the documentation (https://docs.garden.io/advanced/custom-commands):
```yaml
kind: Command
name: api-dev
description:
  short: Start garden with preconfigured options for API development
exec:
  command:
    - sh
    - -c
    - git submodule update --recursive --remote  # Because we keep forgetting to update these, amirite?
gardenCommand:
  - deploy
  - --sync
  - api,worker
  - --log-level
  - debug
  - $concat: ${args.$all}  # Allow any arguments/options on top of the fixed ones above
```

Placing this in `commands.garden.yml` in the project root directory and running `api-dev` in the garden console produces the following error:

```
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ Running setup command... ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20Missing%20cli%20argument%20in%20custom%20command%20wrapper.

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Error: Missing cli argument in custom command wrapper.
    at CustomCommandWrapper.action (file:///Users/jackhall/Library/Application%20Support/io.garden.garden/1718885103-PRoGXub.r/rollup/garden.mjs:430730:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/jackhall/Library/Application%20Support/io.garden.garden/1718885103-PRoGXub.r/rollup/garden.mjs:366623:30
    at async file:///Users/jackhall/Library/Application%20Support/io.garden.garden/1718885103-PRoGXub.r/rollup/garden.mjs:366411:20
    ```

### Your environment
* **OS:** MacOS
* **How I'm running Kubernetes:** GKE
Garden version: 0.13.31
