### ISSUE TITLE
Unable to sync single file with hot-reload

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#652]
### Current Behavior

If I set the `hotReload.sync[].source` value to a filename, as opposed to a directory, hot-reloading fails with an error.

### Expected behavior

I'd expect to be able to sync individual files and not just whole directories.

### Reproducible example

Configure a container module with a field like this:
```
hotReload:
  sync:
  - source: my-file.txt
    target: /app/my-file.txt
```
Note: It does not appear to matter what the target is set to, it will error regardless.

### Suggested solution(s)

We're currently ensuring a trailing path on the source path, no matter what. We might need to reconsider that.

### Your environment

Latest master.
