### ISSUE TITLE
[Bug]: Test exec doesn't copy artifacts if command exits with non-0 code 

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#6524]
### Current behavior

If a the command of a `Test` of type `exec` fails with an exit code, the artifacts are not copied.

### Expected behavior

Garden should try to copy artifacts, at least if any are present.

Example use-case: 
- User runs e2e frontend tests.
- Tests generate comparison screenshots or videos from changes.
- User wants to see the screenshots with the errors in order to debug the tests.

### Reproducible example

```yaml

# example action config

kind: Test
type: exec
name: example-exit-code
description: Example Exit
spec:
  command: 
    - sh
    - example-exit-code.sh
  artifacts:
    - source: tmp/example-exit-code.txt
      target: tests
```

```sh

# example script

echo "data" > tmp/example-exit-code.txt
exit 1
```

### Your environment

* **OS:** 
* **How I'm running Kubernetes:** 

`garden version`
