### ISSUE TITLE
[Bug]: The defaultNamespace should use --var flag

### ISSUE THREAD

**Issue by Daphaz** [garden-io/garden#6528]
### Current behavior

When dynamically defining a namespace name in the `project.garden.yml` using a variable passed through the CLI, the namespace name reverts to the default value instead of the one passed via the command line. For example, in the following configuration:

```Yaml
variables:
  my-variable: ${git.branch}
environments:
  - name: preview
    defaultNamespace: ns-${var.my-variable}
```
When running the command `garden deploy --env preview --var my-variable=test`, 
the expected namespace should be `ns-test`, but it instead uses the default value based on the git branch.

### Expected behavior

The namespace name should be dynamically assigned based on the variable passed via the CLI (--var my-variable=test), not reverting to the default.

### Reproducible example

1. Define the following configuration in your `project.garden.yml`:
```Yaml
variables:
  my-variable: ${git.branch}
environments:
  - name: preview
    defaultNamespace: ns-${var.my-variable}
```
2. Run the command:
```bash
garden deploy --env preview --var my-variable=test
```
3. Observe the namespace generated is not `ns-test`, but based on the default git branch instead.

### Workaround
As a workaround, use environment variables to override the value:
```Yaml
variables:
  source-branch: ${local.env.SOURCE_BRANCH_OVERRIDE || git.branch}
environments:
  - name: preview
    defaultNamespace: ns-${var.source-branch}
```
And run the command with the following:
```bash
SOURCE_BRANCH_OVERRIDE=test garden deploy --env preview
```

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

* **OS:** macOS 14.5 (M1)
* **How I'm running Kubernetes:** EKS

garden version: 0.13.41
