### ISSUE TITLE
[Bug]: Exec action `spec.shell` does not accept a shell specified as a string

### ISSUE THREAD

**Issue by WillDaSilva** [garden-io/garden#6576]
### Current behavior

The documentation for `spec.shell` for every kind of exec action says:

```
If true, runs file inside of a shell. Uses `/bin/sh` on UNIX and `cmd.exe` on Windows. A different shell can be specified as a string. The shell should understand the `-c` switch on UNIX or `/d /s /c` on Windows.
```

### Expected behavior

It's unclear where/how "a different shell can be specified as a string". This issue is either a documentation bug if this feature – using a different shell – is supported but poorly documented, or a bug in the code if the `spec.shell` field is meant to accept strings.

### Reproducible example

```yaml
kind: Run
name: mre
type: exec
spec:
  shell: "bash"
  command:
    - >
      echo "your command here"
```

```
Error validating spec for Run type=exec name=mre:

At path spec.shell: Expected boolean, received string
```

### Workaround

Use `spec.shell: false`, and then manually call the alternative shell in `spec.command`:

```yaml
spec:
  shell: false
  command:
    - "bash"
    - "-c"
    - >
      echo "your command here"
```

### Suggested solution(s)

Make `spec.shell` a `boolean | string` field, and have it interpret string values as the name/path of the shell that will be used. An example added to the documentation would be nice too.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** AWS EKS

`garden version: 0.13.42`
