### ISSUE TITLE
[Bug]: deploymentRegistry.namespace None cause error in kubernetes provider

### ISSUE THREAD

**Issue by phangiabao98** [garden-io/garden#6635]
## Bug

deploymentRegistry.namespace None cause error in kubernetes provider

### My build action
```yaml
kind: Build
name: api
type: container
description: Build the vote API
allowPublish: False
```

### Current behavior

```yaml 
### none workable project.garden.yml
providers:
  - name: kubernetes
    environments: [remote]
    context: "ink-k8s"
    ingressClass: "nginx"
    buildMode: cluster-buildkit
    imagePullSecrets:
      - name: "gitlab-container-registry"
        namespace: default
    deploymentRegistry:
      hostname: "gitlab.inter-k.com:5050/inter-k/internal-software/rnd/kguru"
      # namespace: ${var.userNamespace}
    namespace: ${var.userNamespace}
    defaultHostname: ${var.baseHostname}
```

### workable project.garden.yml
```yaml
providers:
  - name: kubernetes
    environments: [remote]
    context: "ink-k8s"
    ingressClass: "nginx"
    buildMode: cluster-buildkit
    imagePullSecrets:
      - name: "gitlab-container-registry"
        namespace: default
    deploymentRegistry:
      hostname: "gitlab.inter-k.com:5050/inter-k/internal-software/rnd/kguru"
      namespace: ${var.userNamespace}
    namespace: ${var.userNamespace}
    defaultHostname: ${var.baseHostname}
```

Error happend when i run `garden build api`
### Expected behavior

Because providers[].deploymentRegistry.namespace is optional so expect that `Build` action still work even I don't define namespace value.
![image](https://github.com/user-attachments/assets/c2323938-bae0-4c89-b48b-e01296d6ef4b)

The error is about parsing image with invalid `_` character inside 
![image](https://github.com/user-attachments/assets/49572669-0dd6-4ac8-ae95-04c3a9264fdf)

This error cause me plenty of time to trace and debug so hope that I can create a PR to help other spending less time on this issue.
