### ISSUE TITLE
Improve documentation on Plugin Outputs

### ISSUE THREAD

**Issue by benstov** [garden-io/garden#670]
I have just noticed this in the documentation, I don't get exactly how the FUNCTION_ENDPOINT supposed to get its value.

```yml
module:
  description: Hello world container service
  type: container
  name: hello-container
  services:
    ...
      dependencies:
        - hello-function
      env:
        FUNCTION_ENDPOINT: ${modules.hello-function.outputs.endpoint}
```
