### ISSUE TITLE
[FEATURE]: Incorrect merge result of multiple pulumi var files

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#6726]
There is a specification of pulumivarfile where we need to add configs in one or more files and garden merges them all-together during the deployment.
https://docs.garden.io/reference/action-types/deploy/pulumi#spec.pulumivarfiles

There is a also a note added in documentation
`Note: There is no need to nest the variables under a config field as is done in a pulumi config. Simply specify all the config variables at the top level.`

It needs an improvement actually, In pulumi - we've a secret provider containing the `secretsprovider` and `encryptedkey` keys which is not the part of application configuration but these represent the meta-level settings and looks like in the following way:-
Expected result after merge the files

```
secretsprovider: gcpkms://projects/xyz/locations/global/keyRings/pulumi/cryptoKeys/pulumi-secrets
encryptedkey: AQICAHgYk+123...

config:
  someOtherConfig: value

```

Currently the file after merging looks like which is incorrect merged result. 
Actual result after merge the files

```
config:
  secretsprovider: gcpkms://projects/xyz/locations/global/keyRings/pulumi/cryptoKeys/pulumi-secrets
  encryptedkey: AQICAHgYk+123...  # Wrong! Pulumi won't recognize this.
  someOtherConfig: value

```

Please looks into this and provide the optimum solution for this

garden version 0.13.38
pulumi version v3.108.1
Command: garden plugins pulumi preview --env={env-name}
