### ISSUE TITLE
[FEATURE]: Access the Container Build Version inside its own garden.yaml file

### ISSUE THREAD

**Issue by Towerful** [garden-io/garden#6738]
### Background / Motivation

I'm currently customizing some images that require a prefix to the container tag, but keep garden's auto-generated version hash.  
CNPG operator doesn't pay attention to image hashes or anything. It detects changes to the underlying containers by the change of the name. They recommend using image hashes instead of tags in order to facilitate this.  
I figured gardens version has would be sufficient, however CNPG detects the major version of postgres by the start of the tag (eg 15-v-be5ad3 indicates pg version 15)

### What should the user be able to do?

```yaml
kind: Build
name: my-lovely-container
description: Its so lovely
type: container
spec:
  publishId: myregistry/my-lovely-container:15-${build.version}
```

an alternative would be to access the build artefacts specific sha-hash. So I can pin a deployment to an absolute image, not just a tag.  
eg `${actions.build.my-lovely-container.outputs.deploymentImageHash}` 

### Why do they want to do this? What problem does it solve?

I cannot see any method for accessing the current build's garden-version-hash from inside the garden.yaml file.  
The docs hint this is possible ( https://github.com/garden-io/garden/blob/bf74500a91e697b0f3c2de857f487f3cd324c3cb/docs/other-plugins/container.md?plain=1#L163 ), however I now realize these are variables available to the CLI (as I cannot find a relevant varaible I can use).  

Referencing `${actions.build.my-lovely-container.version}` (or `outputs.version`?) results in a circular dependency issue.

### Suggested Implementation(s)

If the version is available to CLI arg inputs, I'm guessing it can be available inside the garden.yaml file?  
Perhaps under the `this` namespace? (ie `this.version`)

It would also be really useful to be able to access the build artifact sha hash from the build actions outputs:

`${actions.build.my-lovely-container.outputs.deploymentImageHash}` for the complete `myregisty/my-lovely-container@sha[...]`    
This matches the existing pattern of deploymentImageId

`${actions.build.my-lovely-container.outputs.deploymentHash}` for just the hash `sha[...]`  
Not sure if this is worth exposing. It could be combined with the deploymentImageName. Which would suggest there should be a deploymentImageTag exposed as well.  
And I'm not sure how useful these actually are. The actual containers rarely care about their tag/sha, whereas I can see the name being useful for ease of templating deployments.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden ~~painful~~ annoying

garden has revolutionized k8s for me and my entire project.  
I am now dreading the idea of having to manually bump a version to trigger

**Comment by Towerful** [comment]
To give an idea of the workaround I am now employing (and incase anyone else wants to use garden to build custom images for (and deploy) CloudNative Postgres (CNPG) )

```yaml
kind: Run
name: db-tag
description: Tags build artefacts to be compatible with CNPG
dependencies: ['build.db-build']
type: exec
variables:
  newTag: ${var.postgres.version}-${actions.build.db-build.version}
  localImageId: ${actions.build.db-build.outputs.deploymentImageId}
  repositryAndImage: ${join(slice(split(actions.build.db-build.outputs.deploymentImageId, ":"), 0, 1), ":")}
  imageId: ${var.repositryAndImage}:${var.newTag}
spec:
  command: [
    "/bin/sh",
    "-c",
    "docker tag ${var.localImageId} ${var.imageId} && docker push ${var.imageId}"
    ]
```

then I am referencing this imageId via `${actions.run.db-tag.var.imageId}`
Which is fine, but it feels like there should be an easier way to do this.
