### ISSUE TITLE
[Bug]: kubernetes-pod test hangs after test execution finished

### ISSUE THREAD

**Issue by har-cpol** [garden-io/garden#6790]
### Current behavior

We have a scheduled run of some long running acceptance tests. This is a huge set of test scenarios so it takes a long time. We have the garden timeout configured to 3h30m.

On some occasions we notice that the test execution has fully ended within the timeout, but:

- The test pod seems to keep  on running 
- Garden CLI process does not detect that the tests have ended.

It takes another hour (or more) past the garden timeout to detect that the error.
In screenshot below:

- Test execution ran for 16225 seconds ( > 4.5 hours)
- But timeout is set to 12600 seconds (3h30m)
- Test execution had ended in this example in less than 3h30m - but this was not detected.

![Image](https://github.com/user-attachments/assets/4ff256fc-a03e-4011-ba96-ad1294e391dd)

I managed once to detect this while it was happening: test execution had ended, but test pod keeps on running.
During that time, following is the process list inside the test pod:

![Image](https://github.com/user-attachments/assets/45611ae3-9060-429c-a133-551ce049b33a)

- The test command configured in the kubernetes-pod test has finished. It is not visible in the process list.
- PID 1 seems to be "stuck" due to the "sleep 86400" command.

### Expected behavior

The test pod should go away and garden test command should end.

### Reproducible example

This does not occur consistently so I cannot give a reproducible scenario. 
Our kubernetes-test pod configuration is quite basic. It just runs a run_tests.sh script that triggers test execution.

```
kind: Test
type: kubernetes-pod
name: acceptance
dependencies:
  - build.acceptance
timeout: 12600 # 3h30m

build: acceptance

spec:
  podSpec:
    containers:
      - name: acceptance-tests
        image: ${actions.build.acceptance.outputs.deploymentImageId}
        imagePullPolicy: IfNotPresent
    podAnnotations:
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

  command:
    - "/home/pwuser/run_tests.sh"

  artifacts:
    - source: /home/pwuser/acceptance/artifacts
      target: acceptance-tests

```

### Workaround

None I can think of

### Suggested solution(s)

No idea. I'm not sure in which direction to search.
I have not been able to find any clear indications in our kubernetes logs or pod events etc.

Can you give any hints as to what could be the cause of this. Some socket timeout ?, network glitch ?, ...
Is there any documentation available on "how" / "who" stops the kubernetes-pod after test succeeded ?

### Your environment

* **Ubuntu** 
* **GKE** 

garden version: 0.13.45
