### ISSUE TITLE
[FEATURE]: template variable which access values for the current provider

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#6791]
### Background / Motivation

I am writing a ConfigTemplate to use a tool not supported by Garden natively. For this I need to forward the correct kube config and context to use.

### What should the user be able to do?

Access a template variable which is already resolved to the current provider.

### Why do they want to do this? What problem does it solve?

For instance to do this now I need to write something like the following (in my ConfigTemplate:

```yaml
[...]
      deployCommand:
        - timoni
        - apply
        - ${inputs.instance}
        - ${inputs.module_url}
        - $concat:
            $if: ${environment == "local"}
            $then:
              - "--kube-context"
              - ${providers.local-kubernetes.config.context}
            $else:
              - "--kube-context"
              - ${providers.kubernetes.config.context}

```

`timoni` is the tool.

Because the config for each provider must be accessed by name I need to first detect which environment I am in and then know which provider that is, which is hardcoded.

### Suggested Implementation(s)

I would prefer something like this:

```yaml
[...]
      deployCommand:
        - timoni
        - apply
        - ${inputs.instance}
        - ${inputs.module_url}
        - --kube-context
        - ${provider.config.context}
```

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful
