### ISSUE TITLE
[Bug]: Templating in sync.paths[].mode not working since 0.13.53

### ISSUE THREAD

**Issue by andreavocado** [garden-io/garden#6843]
### Current behavior

Given following YAML:
```
sync:
  paths:
    - source: .
      target: /app/
      mode: ${var.syncmode || 'one-way-safe'}
```

produces following output when running `deploy service`

```
Error validating spec for Deploy type=container name=service (../service):

spec.sync.paths[0][mode] must be one of [one-way, one-way-safe, one-way-replica, one-way-reverse, one-way-replica-reverse, two-way, two-way-safe, two-way-resolved]
```

### Expected behavior

It evaluates the expresion and uses the variable `syncmode` if given, otherwise the default `'one-way-safe'`

### Reproducible example

s.a.

### Workaround

Use no expresions:

```
sync:
  paths:
    - source: .
      target: /app/
      mode: 'one-way-safe'
```

### Suggested solution(s)

Revert or fix changes made in 0.13.53

### Additional context

Works as expected untill 0.13.52.

### Your environment

garden version: 0.13.53

**Comment by 10ko** [comment]
Hi @andreavocado, thanks for reporting this.
We released some big performance improvements in `0.13.53` that included some substantial changes in the templating system.
Unfortunately it looks our tests didn't catch this specific edge case. 
We'll take a look at this since we are currently working on fixing a bunch of these regressions. Ideally, we are aiming at pushing a new release the latest next week.

Apologies for the issues this might be causing.

**Comment by vvagaytsev** [comment]
Thanks for reporting this @andreavocado!

How to you define the variables? Do you use `variables` or `varfile`?

**Comment by andreavocado** [comment]
I'm using both:

In the `garden.yml` of the project is following defined:

```
varfiles:
  - garden.sync.yaml
``` 

The `garden.sync.yaml` contains:
```
sync:
  paths:
    - source: .
      target: /app/
      mode: ${var.syncmode || 'one-way-safe'}
```

The variable `var.syncmode` is defined in the `garden.remote.env`
```
syncmode=two-way-resolved
```

**Comment by vvagaytsev** [comment]
@andreavocado how to you import the `garden.remote.env` file into your Garden configuration?

It should be declared as:
```yml
kind: Project
varfile: garden.remote.env
...
```
in the Project-config or
```yml
kind: Deploy
varfiles: [garden.remote.env]
...
```
in the Action-config.

The config
```yml
varfiles:
  - garden.sync.yaml
```
looks looks like a snippet of a `garden.yml` config file, and not like a YAML file that declares variables. That's a bit weird.

Unfortunately, I still cannot reproduce it.

Can you please share the Project-level config and the Action-config that declares the deployment in sync-mode? Feel free to omit all sensitive data. It would be very helpful to have a minimal config to proroduce the issue.

**Comment by andreavocado** [comment]
@vvagaytsev I do my best of showing my setup ;)

The `garden.remote.env` should be loaded via your 4th step of [Variable precedence order](https://docs.garden.io/using-garden/variables-and-templating#variable-precedence-order) The environment-specific varfile (defaults to garden.< env-name >.env)

Here are the other project files:

project.garden.yml
```
kind: Project
apiVersion: garden.io/v1
name: marketplace
defaultEnvironment: remote
environments:
  - name: remote
providers:
  - name: kubernetes
    environments: ["remote"]
    context: gke_*
    namespace: any_namespace
    defaultHostname: any_hostname
    buildMode: cluster-buildkit
    deploymentRegistry:
      hostname: *docker.pkg.dev
      namespace: any_namespace
    imagePullSecrets:
      - name: gcr-config
        namespace: default
      - name: gar-config
        namespace: default
dotIgnoreFile: .gardenignore
sources:
  - name: service
    repositoryUrl: "git@github.com:service.git#main"
```

garden.yml
```
kind: Deploy
type: container
name: service
description: any description
dependencies:
  - build.service
  - deploy.redis
  - deploy.selenium-chrome
varfiles:
  - garden.envs.yaml
  - garden.sync.yaml
spec:
  image: some_image
  command: ["/bin/sh", "-c"]
  args:
    - "bundle exec rails server -b 0.0.0.0 -p 3000"
  ports:
    - name: http
      containerPort: 3000
      servicePort: 3000
  limits:
    cpu: 1500
    memory: 2048
  sync: ${var.sync}
  env: ${var.envVars}
```

garden.sync.yaml
```
sync:
  paths:
    - source: .
      target: /app/
      mode: ${var.syncmode || 'one-way-safe'}
```
