### ISSUE TITLE
[Bug]: Validation incosistency between Run and Deploy container actions

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#6878]
## Bug

There is  behaviour discrepancy between `Deploy` and `Run/Test` actions validation in `container` plugin.

### Current behavior

The config entry `spec.volumes` is not validated in Deploy action kind, and only validated in Run/Test action kinds.

### Expected behavior

The config entry `spec.volumes` should be validated in Deploy and Run/Test action kinds.

### Reproducible example

**Reproducible example:**

<details>
<summary>Click to see the configuration</summary>

```yml
apiVersion: garden.io/v1
kind: Project
name: validation-issue
environments:
  - name: local
providers:
  - name: local-kubernetes
    environments: [local]

---
kind: Build
name: my-build
type: container

---
kind: Deploy
description: Desc
name: my-deploy
type: container
dependencies:
  - build.my-build
spec:
  image: ${actions.build.my-build.outputs.deploymentImageId}
  volumes:
    - name: "my-volume"
      containerPath: "my-container-path"
      action: deploy.config # <-- reference to an action that is not listed in the dependencies list

---
kind: Run
description: Desc
name: my-run
type: container
dependencies:
  - build.my-build
spec:
  args: [ "echo", "foo" ]
  image: ${actions.build.my-build.outputs.deploymentImageId}
  volumes:
    - name: "my-volume"
      containerPath: "my-container-path"
      action: deploy.config # <-- reference to an action that is not listed in the dependencies list
```

</details>

Validate each action with the `--resolve` flag:

```console
garden validate --resolve=my-run
garden validate --resolve=my-deploy
```

**Expected result.**

Both actions should fail with the same error:

<details>
<summary>Click to see Run action validation outputs</summary>

```console
✖ run.my-run                → Failed processing resolve Run type=container name=my-run (took 0.01 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Run type=container name=my-run references action deploy.config under `spec.volumes` but does not declare a dependency on it. Please add an explicit dependency on the volume action.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed to resolve Run type=container name=my-run: Error: resolve Run type=container name=my-run failed: Error: Run type=container name=my-run references action deploy.config under `spec.volumes` but does not declare a dependency on it. Please add an explicit dependency on the volume action.
```

</details>

<details>
<summary>Click to see Deploy action validation outputs</summary>

```console
✖ deploy.my-deploy          → Failed processing resolve Deploy type=container name=my-deploy (took 0.01 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Deploy type=container name=my-deploy references action [object Object] under `spec.volumes` but does not declare a dependency on it. Please add an explicit dependency on the volume action.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed to resolve Deploy type=container name=my-deploy: Error: resolve Deploy type=container name=my-deploy failed: Error: Deploy type=container name=my-deploy references action [object Object] under `spec.volumes` but does not declare a dependency on it. Please add an explicit dependency on the volume action.
```

</details>

**Actual result.**

Without this fix, command `garden validate --resolve=my-deploy` passes without errors.
### Additional context

An attempt to fix it was done in #6606 and reverted on #6641 because of some regression.

### Your environment

`garden version 0.13.54`
