### ISSUE TITLE
Crash: TypeError: Cannot read properties of undefined (reading 'servicePort')

### ISSUE THREAD

**Issue by 0xvlado** [garden-io/garden#6892]
### Error message

```
Failed resolving status for Deploy type=container name=pgadmin (took 0.04 sec). This is what happened:
TypeError: Cannot read properties of undefined (reading 'servicePort')
    at file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:859938:97
    at Array.map (<anonymous>)
    at createIngressResources (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:859905:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async createContainerManifests (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:864180:23)
    at async AsyncFunction.k8sGetContainerDeployStatus (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:864020:37)
    at async Object.assign.handlerType.handlerType (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:871033:28)
    at async Router.callHandler (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:871004:24)
    at async getStatus (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:871727:24)
    at async DeployTask.getStatus (file:///home/vs/.local/share/garden/1740173511-3185Xg6.r/rollup/garden.mjs:450139:36)
```

### What did you do?

Was trying to deploy a container with ingresses: 
```
kind: Deploy
description: PgAdmin web interface for PostgreSQL
type: container
name: pgadmin
metadata:
  namespace: ${var.local-env-name}
dependencies:
  - deploy.postgres
spec:
  image: dpage/pgadmin4
  env:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: admin
    PGADMIN_LISTEN_PORT: "5050"
  ports:
    - name: pgadmin
      containerPort: 5050
      servicePort: 5050
  cpu:
    min: 250
    max: 1000
  memory:
    min: 128
    max: 512
  ingresses:
    - hostname: pgadmin.${var.hostname}
      path: /
      port: "5050"
```

### Your environment

* **OS:Arch Linux** 
* **How I'm running Kubernetes:rancher-desktop** 
* **Garden version:0.13.54** 

### Frequency

All the time

### Workaround

Use kubernetes context
```
  ingresses:
    - path: /
      port: pgadmin
      hostname: pgadmin.${var.hostname}
      annotations:
        kubernetes.io/ingress.class: nginx
```
