### ISSUE TITLE
[Bug]: Disabled action causing "Unrecognized action type" error

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#6957]
### Current behavior

Garden fails with an `Unrecognized action type` error when running in an environment that doesn't have the required provider, even though the action in question is disabled.

### Expected behavior

Disabled actions should not cause errors.

### Reproducible example

First, create a project level Garden config file with the following config:

```yaml
apiVersion: garden.io/v1
kind: Project
name: my-project
environments:
  - name: no-k8s
  - name: k8s

providers:
  - name: local-kubernetes
    namespace: env-repro
    environments: [k8s]
---
kind: Deploy
name: k8s-deploy
type: kubernetes
environments: ["k8s"] # also fails with disabled: true
spec:
  manifests:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: my-configmap
      data:
        foo: bar
---
kind: Run
name: say-hi
type: exec
spec:
  command: ["echo", "Hi ${local.username}"]
```

Then run `garden run say-hi --env no-k8s` and notice that it fails because the `no-k8s` environment doesn't have a K8s provider which the `k8s-deploy` action requires, even though that one is disabled.

### Workaround

Configure all required providers in all envs, which may not be viable. 

### Suggested solution(s)

My naive first suggestion would be to check if the action is disabled in [`processActionConfig` function](https://github.com/garden-io/garden/blob/main/core/src/graph/actions.ts#L430) and skip it if it is.

And/Or alternatively filter out disabled actions before calling that function. 

### Your environment

Running of latest `main` as of writing, using Orbstack for local K8s.
