### ISSUE TITLE
[FEATURE]: Allow configuring the build timeout (and other timeouts) globally

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#7141]
### Background / Motivation

Instead of having to configure the build timeout for each action separately, allow users to configure default timeouts globally, for example in their project configuration file.

### What should the user be able to do?

```
kind: project
apiVersion: garden.io/v2
name: foo

# Either we allow configuring timeouts globally like this
timeouts:
  ...

providers:
  - name: container
    # Or we allow configuring it on the provider-level
     buildTimeout: 500
```

Allow configuring timeouts on the project level, the provider level or both.

### Why do they want to do this? What problem does it solve?

Keeping action configuration DRY.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂
