### ISSUE TITLE
[Bug]: `imagePullSecrets` not used for util images when using `utilImageRegistryDomain`

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#7321]
### Current behavior

For the deployment of the `default-backend`, Garden does not use the `imagePullSecrets` setting when using `utilImageRegistryDomain`. This means if the image resides in a private repository, the `default-backend` will fail to start.

### Expected behavior

The `default-backend` deployment should successfully download the image from a private util image repository when using `utilImageRegistryDomain` together with `imagePullSecrets`.

### Reproducible example

```
kind: Project
apiVersion: garden.io/v2
name: repro

environments:
  - name: dev

providers:
- name: local-kubernetes
  imagePullSecrets:
  - name: image-pull-credentials
    namespace: default
  utilImageRegistryDomain: docker.pkg.dev/myprivate/utilimagerepository
```

### Workaround

Publishing the util image repository.

### Additional context

Originally reported by the Discord user Bo: https://discord.com/channels/817392104711651328/1367751402444820541/1367751402444820541

### Your environment

`garden version` v0.14.3
