### ISSUE TITLE
[Bug]: Remote container builder fails with `failed to resolve source metadata` when using base images and not specifying a remote container registry

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#7409]
### Current behavior

If a given Dockerfile has a base image that's passed to it as build arg via Garden, building it with the remote container builder fails with something like:

```console
ERROR: failed to solve: base:v-3510e58f52: failed to resolve source metadata for docker.io/library/base:v-3510e58f52: docker.io/library/base:v-3510e58f52: not found
```

I've only seen this happen when a remote registry isn't defined. 

### Expected behavior

It should build the image without failing.

### Reproducible example

Create a Garden project with the following structure:

```
├── base.Dockerfile
├── main.Dockerfile
└── project.garden.yml
```

And the following file contents:

In `project.garden.yml`:

```yaml
apiVersion: garden.io/v2
kind: Project
name: base-image-repro
organizationId: <insert-org-id>
environments:
  - name: local-build
  - name: remote-build

providers:
  - name: container
    gardenContainerBuilder:
      enabled: ${environment.name == 'remote-build'}
---
kind: Build
type: container
name: base
spec:
  dockerfile: base.Dockerfile
---
kind: Build
type: container
name: main
dependencies: [build.base]
spec:
  dockerfile: main.Dockerfile
  buildArgs:
    BASE_IMAGE: ${actions.build.base.outputs.deploymentImageId}
```

In `base.Dockerfile`:

```Dockerfile
FROM alpine:3.18
WORKDIR /app
RUN echo "Base image" > /app/base-info.txt
```

In `main.Dockerfile`:

```Dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN echo "Main image" > /app/main-info.txt
```

Now run `garden login` to login and populate the project ID. Then run `garden build --env remote-build` and notice how it fails. 

For comparison, you can run `garden build --env local-build` and it should work.

### Workaround

Do not use base images (not feasible in many cases) or always use a remote registry.
