### ISSUE TITLE
Deploy action could not be found for PersistentVolumeClaim

### ISSUE THREAD

**Issue by RISHAVIITKGP** [garden-io/garden#7444]
Getting error:
Deploy type=container name=my-container-svc specifies action 'my-volume' on volume 'my-volume' but the Deploy action could not be found. Please make sure it is specified as a dependency on the action.

garden.yml:

```
kind: Deploy
name: my-volume
type: persistentvolumeclaim
spec:
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 8Gi
---
kind: Deploy
name: my-container-svc
type: container
spec:
  replicas: 1
  image: <some-postgres-image>
  volumes:
    - name: my-volume
      action: deploy.my-volume
      containerPath: /var/lib/postgresql
  ports:
    - name: db
      containerPort: 5432
      servicePort: 5432
  env:
    <env-variables-for-postgres>
  limits:
    cpu: 1000
    memory: 2048

```
garden version: 0.13.54

Is there a different way to handle persistentvolumeclaim?

**Comment by RISHAVIITKGP** [comment]
> Hi [@RISHAVIITKGP](https://github.com/RISHAVIITKGP)
> 
> I'm looking into the issue to see if I can reproduce. (FYI: I removed the secret values from your original post.)

Sure, thanks for that @eysi09 , it was for dev but thank you.

**Comment by RISHAVIITKGP** [comment]
Hey @eysi09 did you get a chance to look into it?

**Comment by RISHAVIITKGP** [comment]
Hey @eysi09 did you get time to look into this?

**Comment by eysi09** [comment]
Hey @RISHAVIITKGP 

I think for your use case it'd be best to use a Deploy action of kind `kubernetes` to create the PVC and a separate Deploy action of kind `kubernetes` for Postgres. (You can also use a `helm` action if you prefer).

We basically recommend users pick the `kubernetes` or `helm` actions which are a lot more flexible and at the end of the day and allow you to do anything you can otherwise do with Kubernetes. The `container` abstraction turned out to be quite leaky.

A complete example for what you're trying to do could look like this:

```
apiVersion: garden.io/v2
kind: Project
name: volume-hacks

environments:
  - name: local-dev
providers:
  - name: local-kubernetes
    namespace: volume-hacks
    environments: [local-dev]

---
kind: Deploy
name: my-volume
type: kubernetes
spec:
  manifests:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: my-volume
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 8Gi

---
kind: Deploy
name: db
type: kubernetes
spec:
  manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: postgres
        labels:
          app: postgres
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: postgres
        template:
          metadata:
            labels:
              app: postgres
          spec:
            containers:
              - name: postgres
                image: postgres:15
                env:
                  - name: POSTGRES_DB
                    value: mydb
                  - name: POSTGRES_USER
                    value: postgres
                  - name: POSTGRES_PASSWORD
                    value: password
                  - name: PGDATA
                    value: /var/lib/postgresql/data/pgdata
                ports:
                  - containerPort: 5432
                    name: postgres
                volumeMounts:
                  - name: postgres-storage
                    mountPath: /var/lib/postgresql/data
                resources:
                  requests:
                    memory: "256Mi"
                    cpu: "250m"
                  limits:
                    memory: "512Mi"
                    cpu: "500m"
            volumes:
              - name: postgres-storage
                persistentVolumeClaim:
                  claimName: my-volume

    - apiVersion: v1
      kind: Service
      metadata:
        name: postgres-service
        labels:
          app: postgres
      spec:
        type: ClusterIP
        ports:
          - port: 5432
            targetPort: 5432
            protocol: TCP
            name: postgres
        selector:
          app: postgres
```

This worked for me when I tried it on local K8s via Orbstack. 

We actually just added a similar example to our examples dir here: https://github.com/garden-io/garden/tree/main/examples/k8s-deploy-simple

Let me know if this helps :)
