### ISSUE TITLE
v1/List not supported

### ISSUE THREAD

**Issue by timonbimon** [garden-io/garden#905]
## Bug

This issue comes out of a discussion in #814 
The resource type `v1/List` does not seem to be supported by garden currently.

```
Failed deploying service seldon-core-operator (from module seldon-core-operator). Here is the output:
————————————————————————————————————————————————————————————————————————————————
Unrecognized resource type v1/List
————————————————————————————————————————————————————————————————————————————————


1 deploy task(s) failed!
```

### Your environment

garden version: 0.10.0-1

**Comment by edvald** [comment]
Ah. I believed this had been fixed, but we may have missed a case or regressed back. I'll take a look.

**Comment by edvald** [comment]
I'm seeing a different issue when I try to deploy `seldon-core-operator`: 
```
CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: 
...
...properties[matchLabels].additionalProperties: Forbidden: additionalProperties cannot be set to false
...
```

**Comment by edvald** [comment]
I'd need to investigate further, but that particular issue doesn't _seem_ Garden related, but I won't rule it out yet. I'll take a closer look tomorrow, and flag this for our next patch release, which will no doubt happen quickly.

**Comment by timonbimon** [comment]
hmm that's weird.
here is the minimum example I need to reproduce the bug (needed to reset my Kubernetes cluster on Docker for Mac to make sure there is nothing else left from before)

garden.yml

```
project:
  name: test
  environments:
    - name: local
      providers:
        - name: local-kubernetes
          setupIngressController: false
```

seldon-core-operator/garden.yml
```
module:
  description: Seldon Core operator running Seldon Core CRD and Controller
  name: seldon-core-operator
  type: helm
  repo: https://storage.googleapis.com/seldon-charts
  chart: seldon-core-operator
  version: 0.3.0
  values:
    ambassador:
      enabled: true
      singleNamespace: true
    usageMetrics:
      enabled: true
```
