### ISSUE TITLE
Kubernetes in-cluster builder storage not respected

### ISSUE THREAD

**Issue by to266** [garden-io/garden#956]
### Current Behavior
Garden config:
```yaml
kind: Project
name: my-project
providers:
  - name: kubernetes
    context: my-context
    buildMode: cluster-docker
    namespace: ${project.name}-${environment.name}-${local.env.CI_COMMIT_REF_NAME || local.username}
    defaultHostname: ${project.name}-${environment.name}-${local.env.CI_COMMIT_REF_NAME || local.username}.domain
    resources:
        builder:
            requests:
                cpu: 1000
                memory: 1024

    storage:
        builder:
            size: 204800
        registry:
            size: 204800

environments:
    - name: dev
    - name: ci
defaultEnvironment: dev
```
After initializing the kubernetes cluster with `garden plugins kubernetes cluster-init` I see the following pvcs:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                  STORAGECLASS        REASON   AGE
pvc-07864677-a3e8-11e9-92dd-068c1f80c2bc   20Gi       RWO            Delete           Bound    garden-system/garden-docker-data       gp2                          117s
pvc-59c593d7-a3e7-11e9-92dd-068c1f80c2bc   200Gi      RWO            Delete           Bound    garden-system/garden-docker-registry   gp2                          6m57s
pvc-d3eee8f0-a3e7-11e9-92dd-068c1f80c2bc   10Gi       RWX            Delete           Bound    garden-system/garden-build-sync        garden-system-nfs            3m27s
```

### Expected behavior

I would expect the `garden-system/garden-docker-data` pvc to be 200Gi just like `garden-system/garden-docker-registry`
