### ISSUE TITLE
Automatic port-forwarding/tunneling

### ISSUE THREAD

**Issue by baspetersdotjpeg** [garden-io/garden#967]
Adding feature request here for visibility of a user.

@edvald please expand your thoughts here!

**Comment by psoares** [comment]
I have a use case like this. I run a java application with remote-debugging arguments. Those expose a remote debugger on port 5005.

This is what the dockerfile for my java project looks like:
```
FROM adoptopenjdk/openjdk11-openj9:jdk-11.0.1.13-alpine-slim
COPY build/libs/*.jar /app/backend.jar
EXPOSE 8080 5005
CMD java  -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dcom.sun.management.jmxremote -noverify ${JAVA_OPTS} -jar /app/backend.jar
```

And this is what my garden.yml file looks like for that module:
```
kind: Module
name: backend
description: Backend service container
type: container
hotReload:
  sync:
    - target: /app/build
      source: build
services:
  - name: backend
    env:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=intro-to-micronaut.local.app.garden:5005
    ports:
      - name: http
        containerPort: 8080
        # Maps service:80 -> container:8080
        servicePort: 80
      - name: debug
        containerPort: 5005
    ingresses:
      - path: /
        port: http
```

Now... when I run `garden dev`, I need to do an extra step of `kubectl -n my-namespace port-forward backend-xyz 5005`. Only then am I able to attach a remote debugger on localhost:5005 to the project from my IDE (IntelliJ).
